"""The generated Akari sources: NAME.akr (the pack embed, a loader and the world's constants)
and GAME.game.akr (the game's entity types: numbers, parameter structs and enums), which every
world of one game imports, so a cart holding several worlds defines them once."""


def upper(name): return name.upper()
def camel(name): return ''.join(part[:1].upper()+part[1:] for part in name.split('_'))


AKARI_TYPE = {'bool':'bool','u8':'u8','s16':'s16','s32':'s32','fixed':'fixed','vec3':'vec3',
              'name':'u32','entity_ref':'u32','world_ref':'u32'}


def game_source(game):
    g = upper(game['name'])
    lines = [f'// Generated by the Mei World Kit from game schema "{game["name"]}". Do not edit.',
             '// Entity type numbers (WpEntity.type_id) and parameter records (wp_entity_params(e) as *T).',
             '// name: a string offset in the pack (the world\'s _string() turns it into *u8); entity_ref: an',
             '// entity number (0xFFFFFFFF: none); world_ref: one of the _WORLD_ numbers below.', '']
    for k,tname in enumerate(game['types']):
        lines.append(f'const {g}_TYPE_{upper(tname)} = {k}')
    lines.append(f'const {g}_TYPES = {len(game["types"])}')
    for k,wname in enumerate(game.get('worlds',[])):
        lines.append(f'const {g}_WORLD_{upper(wname)} = {k}')
    probe = game['probe']
    lines += ['',f'// The body the kit classified collision for (units; degrees): every field the schema gives,',
              '// and the ceiling angle the kit used (45 when the schema leaves it out).']
    for key in ('radius','height','step','floor_max_degrees'):
        if key in probe: lines.append(f'const {g}_PROBE_{upper(key)}: fixed = {float(probe[key])}')
    from .world import DEFAULT_CEILING_DEGREES
    lines.append(f'const {g}_PROBE_CEILING_MAX_DEGREES: fixed = '
                 f'{float(probe.get("ceiling_max_degrees",DEFAULT_CEILING_DEGREES))}')
    for tname,t in game['types'].items():
        params = t.get('params',{})
        if not params: continue
        lines.append('')
        for pname,p in params.items():
            if p['type'] == 'enum':
                values = ', '.join(camel(v) for v in p['values'])
                lines.append(f'enum {camel(game["name"])}{camel(tname)}{camel(pname)}: u8 {{ {values} }}')
        lines.append(f'struct {camel(game["name"])}{camel(tname)} {{')
        for pname,p in params.items():
            kind = (f'{camel(game["name"])}{camel(tname)}{camel(pname)}' if p['type'] == 'enum' else AKARI_TYPE[p['type']])
            lines.append(f'    {pname}: {kind}')
        lines.append('}')
    return '\n'.join(lines)+'\n'


def fog_lines(w, palettes):
    """world_NAME_fog(region, variant) when a variant declares fog (a proposal: DECISIONS.md, "Proposal:
    fog toward a colour"); nothing otherwise, so a world without fog generates what it always did."""
    from kitcore.errors import pointer
    from .schema import WorldError
    n = w['name']
    calls = []
    for k,rname in enumerate(palettes):
        for v,(vname,spec) in enumerate((w['regions'][rname].get('variants') or {}).items()):
            fog = spec.get('fog')
            if not fog: continue
            if fog['far'] - fog['near'] < 1:
                raise WorldError(pointer(pointer(pointer(pointer('/regions',rname),'variants'),vname),'fog'),
                                 f'Fog far ({fog["far"]}) must be at least 1 unit past near ({fog["near"]}).')
            r,g,b = (int(fog['color'][i:i+2],16) for i in (1,3,5))
            calls.append(f'    if region == {k} && variant == {v} {{ gpu_fog(rgb({r}, {g}, {b}), {float(fog["near"])}, '
                         f'{float(fog["far"])}); return }}   // {rname} {vname}')
    if not calls: return []
    return ['','// Fog toward a colour for region k\'s palette variant v, as the recipe declares it (gpu_fog() in',
            '// gfx.akr; a proposal, docs/DECISIONS.md). Call it with wp_region_enter(k, v); a variant without',
            '// fog turns it off. It fogs packets with depth only (render_depth() or render_perspective()).',
            f'fn world_{n}_fog(region: s32, variant: s32) {{',*calls,'    gpu_fog_off()','}']


def world_source(source, compiled, palettes, slot, row, numbers, groups):
    w, game = source.world, source.game
    n, N = w['name'], upper(w['name'])
    report = compiled.report
    lines = [f'// Generated by the Mei World Kit from world "{n}": {report["pack"]["cells"]} cell(s), '
             f'{report["pack"]["bytes"]} bytes. Do not edit.',
             'import "worldpack.akr"',*(['import "wpbackdrop.akr"'] if any(rp.sky for rp in palettes.values()) else []),
             *(['import "wpwater.akr"'] if compiled.water else []),
             f'import "{game["name"]}.game.akr"','',
             f'embed WORLD_{N}: u8 = "{n}.world.bin"',
             f'const WORLD_{N}_CELL_SIZE = {w["grid"]["cell_size"]}']
    if compiled.swatch:
        lines.append(f'embed WORLD_{N}_SWATCH: u8 = "{n}.swatch"')
    if compiled.water:
        lines += [f'// Water surfaces for wp_water() (wpwater.akr): {(len(compiled.water) - 4) // 56} triangles.',
                  f'embed WORLD_{N}_WATER: u8 = "{n}.water.bin"']
    lines += ['','// Regions (wp_region(k)), their palette variants (wp_palette_load(k, v)) and colour ranges.',
              '// SURFACE and EMISSIVE ranges run from the first to the last entry of the class.']
    for k,(rname,rp) in enumerate(palettes.items()):
        R = f'WORLD_{N}_{upper(rname)}'
        lines.append(f'const WORLD_{N}_REGION_{upper(rname)} = {k}')
        if not rp.entries and not rp.extra: continue
        variants = list(w['regions'][rname].get('variants') or {'default':{}})
        for v,vname in enumerate(variants):
            lines.append(f'const {R}_VARIANT_{upper(vname)} = {v}')
        lines += [f'const {R}_COLOUR = {rp.first_colour}',f'const {R}_COLOURS = {rp.colours}']
        for kind,info in rp.describe()['classes'].items():
            lines += [f'const {R}_{upper(kind)} = {info["first_colour"]}',f'const {R}_{upper(kind)}_COUNT = {info["colours"]}']
    layers = list(w.get('layers',{}))
    if layers:
        lines += ['','// Layers (wp_layer_set(id, on)); exclusive groups switch each other off.']
        for k,lname in enumerate(layers): lines.append(f'const WORLD_{N}_LAYER_{upper(lname)} = {k}')
    if 'near_far' in w.get('runtime',{}):
        lines += ['',f'// The near pass\'s far depth the pack asks for (wp_open() sets wp_near_far to it).',
                  f'const WORLD_{N}_NEAR_FAR: fixed = {float(w["runtime"]["near_far"])}']
    paths = list(w.get('paths',{}))
    if paths:
        lines += ['','// Paths (wp_path(n); by name: wp_path_find(name)), in the order of the recipe.']
        for k,pname in enumerate(paths): lines.append(f'const WORLD_{N}_PATH_{upper(pname)} = {k}')
        lines.append(f'const WORLD_{N}_PATHS = {len(paths)}')
    if numbers:
        lines += ['','// Entity numbers (wp_entity(n)) in this pack; not stable across edits: saves use SAVED_ bits.']
        for eid,num in sorted(numbers.items(),key=lambda kv: kv[1]): lines.append(f'const WORLD_{N}_ENTITY_{upper(eid)} = {num}')
    lines += fog_lines(w, palettes)
    lock = compiled.lock
    lines += ['','// Saved bits (WpEntity.saved_bit), from the ID lock file: stable across edits.',
              f'const WORLD_{N}_SAVED_BITS = {lock["next_bit"]}   // bits ever given out, retired ones included']
    for eid,bit in lock['bits'].items(): lines.append(f'const WORLD_{N}_SAVED_{upper(eid)} = {bit}')
    lines += ['','// The address of a name parameter\'s string.',
              f'fn world_{n}_string(offset: u32) -> *u8 {{',
              f'    let base: *u8 = WORLD_{N}',
              '    return (base as u32 + offset) as *u8','}','',
              '// Opens the pack, copies the palette swatch into VRAM and loads every region\'s first variant.'
              +(' Enters the first region with textures or a backdrop (wp_region_enter).' if any(rp.extra for rp in palettes.values()) else ''),
              f'fn world_{n}_load() -> bool {{',
              f'    if !wp_open(WORLD_{N}) {{ return false }}']
    if compiled.swatch:
        lines.append(f'    memcpy((VRAM_TEXTURES + {slot} * TEXTURE_SLOT_SIZE + {row * 128}) as *u8, WORLD_{N}_SWATCH, {len(compiled.swatch)})')
        for k,(rname,rp) in enumerate(palettes.items()):
            if rp.entries and not rp.extra: lines.append(f'    wp_palette_load({k}, 0)')
    extra = [k for k,rp in enumerate(palettes.values()) if rp.extra]
    for k,(rname,rp) in enumerate(palettes.items()):
        if rp.extra and k != extra[0]: lines.append(f'    wp_variant_load({k}, 0)')
    if extra:
        # the first region with textures or a backdrop is entered: its texture set, backdrop art
        # and animations (the game enters another with wp_region_enter(k, v))
        lines.append(f'    wp_region_enter({extra[0]}, 0)')
    if compiled.water:
        lines.append(f'    wp_water_open(WORLD_{N}_WATER)')
    lines += ['    return true','}']
    return '\n'.join(lines)+'\n'
