"""Native preview renders of a built world: for every region, one of its cells seen from a fixed
camera, once per palette variant, through the real compiler, the reader and the headless GPU.

The renders help an agent judge layout and colour; they are not a gate. They use the reader's own
two passes, so far cells show as their stand-ins exactly as a game would draw them.
"""
import os
from pathlib import Path

from kitcore import native
from .schema import WorldError


def views(source, compiled, cell=None):
    """[(label, cell recipe, region index, variant index, variant name)] to render."""
    cells = [cs.recipe for cs in source.cells]
    if cell is not None:
        cells = [c for c in cells if c['id'] == cell]
        if not cells: raise WorldError('/arguments',f'No cell {cell!r}.')
    out = []
    for k,rname in enumerate(source.world['regions']):
        pick = [c for c in cells if c['region'] == rname]
        if not pick: continue
        # The region's busiest cell (most placements), the first of equals.
        pick.sort(key=lambda c: -len(c.get('placements',[])))
        variants = list(source.world['regions'][rname].get('variants') or {'default':{}})
        rp = compiled.report['regions'][rname]
        if not rp.get('palette') and 'textures' not in rp and 'backdrop' not in rp: variants = variants[:1]
        for v,vname in enumerate(variants):
            out.append((f'{pick[0]["id"]}_{vname}',pick[0],k,v,vname))
    return out


def source_for(name, cell, size, region, variant, vname, extra=None):
    i,j = cell['at']
    cx,cz = i*size+size/2,j*size+size/2
    eye = (cx,size*0.45,cz-size*0.85)
    f = lambda n: f'{n:.4f}'
    if extra is not None:
        return extra_source(name, cell, region, variant, vname, eye, extra)
    return f'''// Generated by the Mei World Kit: a preview of cell "{cell["id"]}".
cart "World preview"
import "{name}.akr"

fn init() {{
    assert(world_{name}_load())
    wp_palette_load({region}, {variant})
    wp_far_ring = 4
}}

fn draw() {{
    cls(rgb(24, 28, 36))
    wp_draw(vec3({f(eye[0])}, {f(eye[1])}, {f(eye[2])}), 0.0, -0.42)
    text(8, 8, "{cell["id"].upper()} {vname.upper()}", rgb(224, 230, 240))
}}
'''


def extra_source(name, cell, region, variant, vname, eye, extra):
    """A preview of a world with textures or a backdrop: the region entered (its texture set,
    palettes and backdrop art), the backdrop shown, drawn as the game draws (depth and
    perspective when the world says so), its animations advanced."""
    f = lambda n: f'{n:.4f}'
    depth, persp, backdrop = extra
    lines = ''.join(f'    {l}\n' for l in (['render_depth(true)'] if depth else []) + (['render_perspective(true)'] if persp else []))
    return f'''// Generated by the Mei World Kit: a preview of cell "{cell["id"]}".
cart "World preview"
import "{name}.akr"
{'import "depth.akr"' if depth or persp else ''}

fn init() {{
    assert(world_{name}_load())
    wp_region_enter({region}, {variant})
    wp_far_ring = 4
{f"    wp_backdrop_show({region})" if backdrop else ""}
{f"    wp_backdrop_variant({variant}, {variant}, 0.0)" if backdrop else ""}
}}

fn draw() {{
{"    wp_backdrop_draw(0.0, -0.3)" if backdrop else "    cls(rgb(24, 28, 36))"}
{lines}    wp_animate(frame() as s32)
    wp_draw(vec3({f(eye[0])}, {f(eye[1] * 0.5)}, {f(eye[2])}), 0.0, -0.3)
    text(8, 8, "{cell["id"].upper()} {vname.upper()}", rgb(224, 230, 240))
}}
'''


def render(stage, source, compiled, compiler, runner, cell=None):
    """Renders into stage/preview/ (PNGs, GPU CSVs, contact.png); returns the report entry."""
    native.require('/preview',(compiler,runner),error=WorldError)
    stage = Path(stage)
    out = stage/'preview'
    out.mkdir(exist_ok=True)
    name, size = source.world['name'], source.world['grid']['cell_size']
    images, rows = [],[]
    for label,c,region,variant,vname in views(source,compiled,cell):
        cart = stage/f'.preview_{label}.akr'
        rinfo = compiled.report['regions'][c['region']]
        runtime = source.world.get('runtime',{})
        extra = ((runtime.get('depth',False),runtime.get('perspective',False),'backdrop' in rinfo)
                 if 'textures' in rinfo or 'backdrop' in rinfo else None)
        cart.write_text(source_for(name,c,size,region,variant,vname,extra))
        mei = stage/f'.preview_{label}.mei'
        env = dict(os.environ,MEI_STDLIB=str(Path(__file__).resolve().parents[2]/'stdlib'))
        native.compile_cart(compiler,cart,mei,'/preview',env=env,error=WorldError)
        ppm, csv = stage/f'.preview_{label}.ppm', out/f'{label}.csv'
        native.run_cart(runner,mei,'/preview',frames=4,dump=ppm,gpu_stats=csv,error=WorldError)
        pixels = native.read_ppm(ppm,'/preview',error=WorldError)
        (out/f'{label}.png').write_bytes(native.png_bytes(native.WIDTH,native.HEIGHT,pixels))
        images.append(pixels)
        rows.append({'cell':c['id'],'region':c['region'],'variant':vname,'image':f'preview/{label}.png',
                     'stats':native.last_frame_stats(csv)})
        for tmp in (cart,mei,ppm): tmp.unlink()
    if images: (out/'contact.png').write_bytes(native.contact_sheet(images))
    return {'contact':'preview/contact.png' if images else None,'views':rows}
