#!/usr/bin/env python3
"""Independent subdivision regression: uniform tints must remain uniform.

Constructs a wall whose opposite depth-varying edges split together. Its
reference bisects object-space intervals, averages each channel independently,
then sends only these authored reference inputs to the specification rasterizer.
"""
import argparse, json, struct, subprocess
from pathlib import Path
import numpy as np
from PIL import Image, ImageDraw
import common
from meshlib import Mesh, rgb, DOUBLE, GOURAUD
import oracle
CART=common.cart_dir('subdivision')
S=65536


def generate():
    for kind in ('flat','gouraud','gradient'):
        gouraud=kind!='flat'
        m=Mesh()
        ids=[m.vertex(*v) for v in [(-1,-1,1),(1,-1,5),(-1,1,1),(1,1,5)]]
        colours=[rgb(1,31,127),rgb(255,222,5)]*2 if kind=='gradient' else [rgb(65,65,65)]*4
        m.quad(ids,colours,[(0,255),(255,255),(0,0),(255,0)],flags=DOUBLE|(GOURAUD if gouraud else 0),slot=4,four_bit=True)
        (CART/(kind+'.bin')).write_bytes(m.pack())
    (CART/'texture.bin').write_bytes(bytes([0x11])*32768)
    (CART/'palette.bin').write_bytes(struct.pack('<16H',0,*([32767]*15)))
    (CART/'subdivision.akr').write_text('''// Generated by tests/reference_renderer/geometry_check.py; A cycles 0..3 subdivision levels.
cart "Reference Renderer: subdivision"
embed FLAT: Mesh = "flat.bin"
embed GOURAUD: Mesh = "gouraud.bin"
embed GRADIENT: Mesh = "gradient.bin"
embed PALETTE: u16 = "palette.bin"
embed TEX: u8 = "texture.bin"
var selected: s32
fn init() {
    camera_clip(0.5, 32.0)
    load_palette(0, PALETTE, len(PALETTE))
    load_texture(4, TEX, len(TEX))
}
fn update() { if btnp(A) { selected = (selected + 1) % 12 } }
fn draw() {
    cls(rgb(24,32,48))
    dither(false)
    fog_off()
    var view: mat4
    view[0] = vec4(1.0, 0.0, 0.0, 0.0)
    view[1] = vec4(0.0, 1.0, 0.0, 0.0)
    view[2] = vec4(0.0, 0.0, 1.0, 0.0)
    view[3] = vec4(0.0, 0.0, 1.0, 0.0)
    camera_matrix(view)
    subdivide(selected % 4)
    if selected < 4 { mesh(FLAT) }
    else if selected < 8 { mesh(GOURAUD) }
    else { mesh(GRADIENT) }
}
''')


def reference(level,kind):
    gouraud=kind!='flat'
    verts=[{'v':[-S,-S,S,S],'col':[65]*3,'uv':[0,255]},
           {'v':[S,-S,5*S,S],'col':[65]*3,'uv':[255,255]},
           {'v':[-S,S,S,S],'col':[65]*3,'uv':[0,0]},
           {'v':[S,S,5*S,S],'col':[65]*3,'uv':[255,0]}]
    if kind=='gradient':
        for i,v in enumerate(verts):v['col']=[1,31,127] if i%2==0 else [255,222,5]
    def midpoint(a,b):
        return {key:[(x+y)//2 for x,y in zip(a[key],b[key])] for key in a}
    packets=[]
    def visit(v,g):
        near,far=sorted([v[0]['v'][2],v[1]['v'][2]])
        if g<level and near<8*S and far>near+(near*(S//4)//S):
            b,t=midpoint(v[0],v[1]),midpoint(v[3],v[2])
            # Worklist draws left before right; OT reverses equal-depth pieces.
            visit([v[0],b,v[2],t],g+1)
            visit([b,v[1],t,v[3]],g+1)
            return
        corners=[{'c':[a['v'][0],a['v'][1],a['v'][2],a['v'][2]]} for a in v]
        scale=oracle.trunc(1024*S*S,32*S-S//2)
        depth=sum(a['v'][2]-S//2 for a in v)
        packets.append({'flags':6|(1 if gouraud else 0),'blend':0,'slot':4,'four':True,'pal':0,
                        'pos':[oracle.project(a['c']) for a in corners],
                        'cols':[a['col'] for a in v],'uv':[a['uv'] for a in v],
                        'bucket':max(0,min(1023,depth*(scale//4)//(S*S))),'sequence':len(packets)})
    visit(verts,0)
    packets.sort(key=lambda p:(p['bucket'],p['sequence']),reverse=True)
    tex=np.zeros(524288,dtype=np.uint8);tex[4*32768:5*32768]=0x11
    pal=np.zeros(4096,dtype=np.int64);pal[1:16]=32767
    return packets,oracle.rgb_image(oracle.render({'background':[24,32,48]},{'dither':False},packets,tex,pal))


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out',type=Path,default=common.OUT/'subdivision')
    args=parser.parse_args();args.out.mkdir(parents=True,exist_ok=True)
    generate()
    rom=common.compile_cart('subdivision')
    results=[];gallery=[]
    for number in range(12):
        kind=('flat','gouraud','gradient')[number//4];level=number%4;name=f'{kind}_level{level}'
        packets,expected=reference(level,kind)
        expected.save(args.out/f'{name}_oracle.png')
        events=[]
        for i in range(number):events.extend([f'{20+i*20}:10',f'{25+i*20}:0'])
        ppm=args.out/f'{name}_mei.ppm'
        subprocess.run([str(common.HEADLESS),str(rom),'--frames',str(40+number*20),'--input',','.join(events) or '0:0','--dump',str(ppm),'--quiet'],check=True)
        actual=Image.open(ppm).convert('RGB');actual.save(args.out/f'{name}_mei.png')
        expected_array=np.array(expected);actual_array=np.array(actual)
        report={'case':name,'reference_quads':len(packets),**oracle.compare(expected_array,actual_array)}
        results.append(report);print(json.dumps(report),flush=True)
        diff=np.zeros_like(expected_array);diff[np.any(expected_array!=actual_array,axis=2)]=[255,40,90]
        Image.fromarray(diff).save(args.out/f'{name}_diff.png')
        sheet=Image.new('RGB',(960,260),(15,19,28));draw=ImageDraw.Draw(sheet)
        for i,(label,img) in enumerate([('Independent reference',expected),('Mei',actual),('Difference',Image.fromarray(diff))]):
            draw.text((i*320+5,4),f'{name}: {label}',fill='white');sheet.paste(img,(i*320,20))
        sheet.resize((1920,520),Image.Resampling.NEAREST).save(args.out/f'{name}_comparison.png')
        gallery.append(sheet)
    combined=Image.new('RGB',(960,260*len(gallery)))
    for i,sheet in enumerate(gallery):combined.paste(sheet,(0,260*i))
    combined.save(args.out/'all_views.png')
    (args.out/'report.json').write_text(json.dumps(results,indent=2)+'\n')
    return 1 if any(r['different_pixels'] for r in results) else 0

if __name__=='__main__':raise SystemExit(main())
