#!/usr/bin/env python3
"""Compare an animated, textured mesh sequence to authored fixed-point inputs.

Matrices come from the deterministic scene trajectory, never emulator packets.
Every presented frame is checked; tick captures are associated through the
headless presentation CSV so CPU/GPU overruns cannot shift the reference.
"""
import argparse, csv, json, math, struct, subprocess
from pathlib import Path
import numpy as np
from PIL import Image, ImageDraw
import common
from meshlib import Mesh, rgb, DOUBLE, GOURAUD
import oracle
CART=common.cart_dir('motion')
S=65536
LENGTH=64
BACKGROUND=[24,32,48]


def matrix(angle=0,position=(0,0,0)):
    c,s=math.cos(angle),math.sin(angle)
    return [[round(c*S),0,round(s*S),round(position[0]*S)],
            [0,S,0,round(position[1]*S)],
            [round(-s*S),0,round(c*S),round(position[2]*S)],[0,0,0,S]]


def trajectory(frame):
    phase=2*math.pi*frame/LENGTH
    # Translation changes by fractions of a pixel; yaw tests all four transform rows.
    view=matrix(0.075*math.sin(phase),(0.025*math.sin(2*phase),0,0.08*math.cos(phase)))
    view[3]=view[2][:]
    models=[]
    for i in range(10):
        x=(i%5-2)*1.42+0.19*math.sin(phase+i)
        y=-0.22+(i//5)*1.5+0.17*math.cos(phase*2+i)
        z=4.0+(i//5)*1.7+0.55*math.sin(phase+i*0.8)
        models.append(matrix(phase+i*0.35,(x,y,z)))
    # Perspective wall: its opposing horizontal edges split identically.
    models.append(matrix(0,(0,-1.3,0.8+2.0*(1+math.sin(phase)))))
    # A moving triangle crosses near w=0.5 and the projection guard band.
    models.append(matrix(0,(0.1*math.sin(phase),0,0.48*math.cos(phase))))
    return view,models


def generate():
    cube=Mesh()
    points=[(-.46,-.46,-.46),(.46,-.46,-.46),(-.46,.46,-.46),(.46,.46,-.46),
            (-.46,-.46,.46),(.46,-.46,.46),(-.46,.46,.46),(.46,.46,.46)]
    for p in points:cube.vertex(*p)
    for i,indices in enumerate(([0,1,2,3],[5,4,7,6],[4,0,6,2],[1,5,3,7],[2,3,6,7],[4,5,0,1])):
        colours=[rgb(65+20*i,129,181),rgb(153,67+10*i,127),rgb(191,141,79),rgb(91,183,145)]
        cube.quad(indices,colours,[(0,255),(255,255),(0,0),(255,0)],slot=4,four_bit=True)
    (CART/'cube.bin').write_bytes(cube.pack())
    wall=Mesh()
    for p in [(-2,-.45,.8),(2,-.45,5.2),(-2,.45,.8),(2,.45,5.2)]:wall.vertex(*p)
    wall.quad([0,1,2,3],[rgb(65,129,181)]*4,[(0,255),(255,255),(0,0),(255,0)],flags=DOUBLE|GOURAUD,slot=4,four_bit=True)
    (CART/'wall.bin').write_bytes(wall.pack())
    near=Mesh()
    for p in [(-.18,-.23,.18),(.24,-.26,1.2),(-.04,.15,1.0)]:near.vertex(*p)
    near.tri([0,1,2],[rgb(155,127,65),rgb(65,191,127),rgb(127,65,191)],[(0,255),(255,255),(128,0)],flags=DOUBLE,slot=4,four_bit=True)
    (CART/'near.bin').write_bytes(near.pack())
    # Transparent index-zero holes, fine UV boundaries and odd/even 4-bit nibbles.
    yy,xx=np.mgrid[:256,:256]
    idx=(1+(xx//9+yy//7)%15).astype(np.uint8)
    idx[(xx//19+yy//23)%7==0]=0
    texture=(idx[:,::2]|(idx[:,1::2]<<4)).tobytes()
    (CART/'texture.bin').write_bytes(texture)
    palette=[0]+[(((i*7)%32)|(((i*13)%32)<<5)|(((i*23)%32)<<10)) for i in range(1,16)]
    (CART/'palette.bin').write_bytes(struct.pack('<16H',*palette))
    views=[];models=[]
    for frame in range(LENGTH):
        view,model=trajectory(frame);views.extend(sum(view,[]));models.extend(sum((sum(m,[]) for m in model),[]))
    (CART/'views.bin').write_bytes(struct.pack('<'+'i'*len(views),*views))
    (CART/'models.bin').write_bytes(struct.pack('<'+'i'*len(models),*models))
    source='''// Generated by tests/reference_renderer/motion_check.py. 64-step texture motion loop.
cart "Reference Renderer: motion"
embed CUBE: Mesh = "cube.bin"
embed WALL: Mesh = "wall.bin"
embed NEAR: Mesh = "near.bin"
embed PALETTE: u16 = "palette.bin"
embed TEX: u8 = "texture.bin"
embed VIEWS: mat4 = "views.bin"
embed MODELS: mat4 = "models.bin"
var step: s32
var paused: bool
fn init() {
    step = -1
    camera_clip(0.5, 32.0)
    load_palette(0, PALETTE, len(PALETTE))
    load_texture(4, TEX, len(TEX))
}
fn update() {
    if btnp(A) { paused = !paused }
    if !paused || step < 0 { step = (step + 1) % 64 }
}
fn draw() {
    cls(rgb(24,32,48))
    dither(true)
    fog_off()
    camera_matrix(VIEWS[step])
    subdivide(0)
    for i in 0..10 { mesh_xf(CUBE, MODELS[step * 12 + i]) }
    subdivide(3)
    mesh_xf(WALL, MODELS[step * 12 + 10])
    subdivide(0)
    mesh_xf(NEAR, MODELS[step * 12 + 11])
    // Deliberately hold four frames across extra ticks to test capture alignment.
    if step % 16 == 8 {
        let ready = FRAME + 2
        while FRAME < ready { }
    }
}
'''
    (CART/'motion.akr').write_text(source)
    tex=np.zeros(524288,dtype=np.uint8);tex[4*32768:5*32768]=np.frombuffer(texture,dtype=np.uint8)
    pal=np.zeros(4096,dtype=np.int64);pal[:16]=palette
    return tex,pal


def packets_for(frame):
    view,models=trajectory(frame)
    packets=[];counts={'faces':0,'clipped':0,'subdivision_pieces':0}
    near=S//2;scale=oracle.trunc(1024*S*S,32*S-near)
    def emit(face,corners,clipped=False):
        pos=[oracle.project(v['c']) for v in corners]
        a,b,c=pos[:3]
        area=(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0])
        if not face['flags']&DOUBLE and area>=0:return
        n=len(corners)
        def rounded(values):return [(x+S//2)//S if clipped else x//S for x in values]
        packets.append({**face,'flags':(face['flags']&~4)|(4 if n==4 else 0),
                        'pos':pos,'cols':[rounded(v['col']) for v in corners],
                        'uv':[rounded(v['uv']) for v in corners],
                        'bucket':max(0,min(1023,sum(v['c'][3]-near for v in corners)*(scale//n)//(S*S))),
                        'sequence':len(packets)})
    def finish(face,cs):
        if all(v['c'][3]<near for v in cs):return
        pos=[oracle.project(v['c']) for v in cs]
        crosses=any(v['c'][3]<near for v in cs)
        clip=crosses or any(not(-1000<=p[0]<=999 and -1000<=p[1]<=999) for p in pos)
        if not clip:emit(face,cs);return
        if oracle.offview(cs):return
        if not face['flags']&DOUBLE and not oracle.clip_front(cs):return
        counts['clipped']+=1
        polygon=[cs[i] for i in ([0,1,3,2] if len(cs)==4 else [0,1,2])]
        planes=[4,0,1,2,3] if crosses else [p for p in range(4) if any(
            (q[0]>999 if p==0 else q[0]<-1000 if p==1 else q[1]>999 if p==2 else q[1]<-1000) for q in pos)]
        for p in planes:
            polygon=oracle.clip_polygon(polygon,p,near)
            if len(polygon)<3 or (p==4 and oracle.offview(polygon)):return
        i=1
        while i+1<len(polygon):
            ids=[i,i+1,0,i+2] if i+2<len(polygon) else [0,i,i+1]
            emit(face,[polygon[k] for k in ids],True);i+=2 if len(ids)==4 else 1
    for instance,model in enumerate(models):
        name='cube' if instance<10 else 'wall' if instance==10 else 'near'
        vertices,faces=oracle.read_mesh(CART/(name+'.bin'))
        # The public mat4 expression adds four fixed-point scaled rows;
        # each scale rounds before addition, unlike vxfm's fused dot.
        mvp=[[sum(view[i][k]*model[k][j]//S for k in range(4)) for j in range(4)] for i in range(4)]
        for face in faces:
            counts['faces']+=1
            corners=[{'obj':vertices[idx], 'c':oracle.transform(mvp,vertices[idx]),
                      'col':[v*S for v in face['cols'][i if face['flags']&1 else 0]],
                      'uv':[v*S for v in face['uv'][i]]} for i,idx in enumerate(face['idx'])]
            if name!='wall':finish(face,corners);continue
            def midpoint(a,b):
                obj=[(x+y)//2 for x,y in zip(a['obj'],b['obj'])]
                return {'obj':obj,'c':oracle.transform(mvp,obj),
                        'col':[((x//S+y//S)//2)*S for x,y in zip(a['col'],b['col'])],
                        'uv':[((x//S+y//S)//2)*S for x,y in zip(a['uv'],b['uv'])]}
            def split(cs,level):
                lo,hi=sorted([cs[0]['c'][3],cs[1]['c'][3]])
                if level<3 and lo<8*S and hi>lo+lo//4:
                    b,t=midpoint(cs[0],cs[1]),midpoint(cs[3],cs[2])
                    split([cs[0],b,cs[2],t],level+1);split([b,cs[1],t,cs[3]],level+1)
                else:counts['subdivision_pieces']+=1;finish(face,cs)
            split(corners,0)
    packets.sort(key=lambda p:(p['bucket'],p['sequence']),reverse=True)
    counts['packets']=len(packets)
    return packets,counts


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out',type=Path,default=common.OUT/'motion')
    parser.add_argument('--frames',type=int,default=65,help='Consecutive presented frames, 2..128; 65 checks loop closure')
    args=parser.parse_args()
    if not 2<=args.frames<=128:parser.error('--frames must be 2..128')
    args.out.mkdir(parents=True,exist_ok=True)
    texture,palette=generate()
    rom=common.compile_cart('motion')
    # Give CPU initialization and occasional long frames enough time to finish.
    stats=args.out/'stats.csv';prefix=args.out/'capture'
    subprocess.run([str(common.HEADLESS),str(rom),
                    '--frames',str(args.frames*5+20),'--dump-every','1',str(prefix),
                    '--gpu-stats',str(stats),'--quiet'],check=True)
    rows=list(csv.DictReader(stats.open()))
    if len(rows)<args.frames:raise RuntimeError(f'Only {len(rows)} frames presented')
    results=[];animation=[];held=[];expected_before=actual_before=None;tick_before=None
    for frame,row in enumerate(rows[:args.frames]):
        if int(row['tris_dropped']):raise RuntimeError('GPU triangle capacity exceeded')
        tick=int(row['tick']);name=f'frame_{frame:03}'
        packets,counts=packets_for(frame % LENGTH)
        expected=np.array(oracle.rgb_image(oracle.render({'background':BACKGROUND},{'dither':True},packets,texture,palette)))
        actual=np.array(Image.open(args.out/f'capture_{tick:05}.ppm').convert('RGB'))
        diff=np.zeros_like(expected);diff[np.any(expected!=actual,axis=2)]=[255,40,90]
        result={'frame':frame,'step':frame % LENGTH,'tick':tick,'geometry':counts,'image':oracle.compare(expected,actual),
                'cpu_cycles':int(row['cpu_cycles']),'gpu_cycles':int(row['gpu_cycles']),'ticks':int(row['ticks'])}
        if actual_before is not None:
            for held_tick in range(tick_before+1,tick):
                held_image=np.array(Image.open(args.out/f'capture_{held_tick:05}.ppm').convert('RGB'))
                held.append({'tick':held_tick,'previous_presented_frame':frame-1,
                             **oracle.compare(actual_before,held_image)})
        if expected_before is not None:
            ed=expected.astype(int)-expected_before.astype(int);ad=actual.astype(int)-actual_before.astype(int)
            result['temporal']={'different_delta_pixels':int(np.any(ed!=ad,axis=2).sum()),
                                'expected_changed_pixels':int(np.any(ed!=0,axis=2).sum()),
                                'actual_changed_pixels':int(np.any(ad!=0,axis=2).sum()),
                                'stale_frame_detected_pixels':oracle.compare(expected,expected_before)['different_pixels']}
        results.append(result)
        for label,pixels in [('oracle',expected),('mei',actual),('diff',diff)]:Image.fromarray(pixels).save(args.out/f'{name}_{label}.png')
        sheet=Image.new('RGB',(960,264),(15,19,28));draw=ImageDraw.Draw(sheet)
        for i,(label,pixels) in enumerate([('Independent motion reference',expected),('Mei',actual),('Difference (pink)',diff)]):
            draw.text((320*i+6,6),f'{label} | step {frame % LENGTH:02} | tick {tick}',fill='white');sheet.paste(Image.fromarray(pixels),(320*i,24))
        animation.append(sheet)
        expected_before,actual_before,tick_before=expected,actual,tick
        print(json.dumps(result),flush=True)
    summary={'presented_frames':args.frames,'sequence_steps':64,
             'different_pixels':sum(r['image']['different_pixels'] for r in results),
             'different_temporal_delta_pixels':sum(r.get('temporal',{}).get('different_delta_pixels',0) for r in results),
             'clipped_frames':sum(r['geometry']['clipped']>0 for r in results),
             'subdivision_piece_counts':sorted(set(r['geometry']['subdivision_pieces'] for r in results)),
             'held_ticks':sum(max(0,r['ticks']-1) for r in results),
             'checked_held_display_ticks':len(held),
             'held_display_error_pixels':sum(r['different_pixels'] for r in held),
             'stale_frame_detection_pixels':sum(r.get('temporal',{}).get('stale_frame_detected_pixels',0) for r in results)}
    (args.out/'report.json').write_text(json.dumps({'summary':summary,'frames':results,'held_display':held},indent=2)+'\n')
    animation[0].save(args.out/'comparison.gif',save_all=True,append_images=animation[1:],duration=80,loop=0,optimize=False)
    chosen=np.linspace(0,len(animation)-1,min(8,len(animation)),dtype=int)
    gallery=Image.new('RGB',(960,264*len(chosen)))
    for i,f in enumerate(chosen):gallery.paste(animation[f],(0,264*i))
    gallery.save(args.out/'contact_sheet.png')
    # Exact PNGs and JSON retain presented and held-display evidence.
    # Remove the larger transient tick dumps once they have been checked.
    for path in args.out.glob('capture_*.ppm'):path.unlink()
    print(json.dumps(summary),flush=True)
    return int(bool(summary['different_pixels'] or summary['different_temporal_delta_pixels'] or summary['held_display_error_pixels']))

if __name__=='__main__':raise SystemExit(main())
