#!/usr/bin/env python3
"""Temporal texture oracle for a real Akari cart, mapped to presented frames.

Texture/palette state and animated corners are authored independently here;
only the existing integer barycentric specification rasterizer is shared.
"""
import argparse
import csv
import json
import subprocess
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw
import common
import oracle

CART = common.cart_dir('textures')
BG = [24, 32, 48]


def palette_key(which):
    colours = np.array([((i * (3 + which * 2) + 1) % 32) |
                     (((i * (7 - which * 2) + 3) % 32) << 5) |
                     (((i * (11 + which * 2) + 5) % 32) << 10)
                     for i in range(256)], dtype='<u2')
    colours[7] = 0  # A nonzero texture index selecting black must still draw.
    return colours


def art(four, phase):
    y, x = np.mgrid[:256, :256]
    a = ((x // (3 + phase * 2) + y // (5 - phase * 2) +
          (x * y % 13) + phase * 7) % (16 if four else 256)).astype(np.uint8)
    a[(x // 16 + y // 16) % 7 == 0] = 0
    return (a[:, ::2] | a[:, 1::2] << 4).tobytes() if four else a.tobytes()


def generate():
    for four in (True, False):
        for phase in range(2):
            (CART / f'tex{4 if four else 8}_{phase}.bin').write_bytes(art(four, phase))
    for key in range(2):
        (CART / f'pal{key}.bin').write_bytes(palette_key(key).tobytes())
    source = '''// Generated by tests/reference_renderer/texture_check.py. Hold A for GPU overload.
cart "Reference Renderer: textures"
embed T40: u8 = "tex4_0.bin"
embed T41: u8 = "tex4_1.bin"
embed T80: u8 = "tex8_0.bin"
embed T81: u8 = "tex8_1.bin"
embed P0: u16 = "pal0.bin"
embed P1: u16 = "pal1.bin"
var seq: s32 = -1
var stress: bool
fn init() {
    // The 8-bit slot-15 page wraps at the end of texture RAM. Upload its
    // halves explicitly; load_texture itself is an ordinary memory copy.
    load_texture(15, T81, 32768)
    load_texture(0, T81 + 32768, 32768)
    load_palette(2560, P1, 256)
}
fn update() {
    seq += 1
    stress = btn(A)
    if seq % 8 == 0 {
        if (seq / 8) % 2 == 0 { load_texture(8, T40, len(T40)) }
        else { load_texture(8, T41, len(T41)) }
    }
    if seq % 12 == 0 {
        if (seq / 12) % 2 == 0 { load_texture(3, T80, len(T80)) }
        else { load_texture(3, T81, len(T81)) }
    }
    let pixels = (VRAM_TEXTURES + 8 * TEXTURE_SLOT_SIZE) as *u8
    for j in 0..32 { pixels[(seq % 32) * 128 + j] = ((seq * 17 + j * 11 + 1) % 256) as u8 }
    let t = from_bits((seq % 33) * 2048)
    palette_lerp(0, P0, P1, 16, t)
    palette_lerp(256, P1, P0, 256, t)
    load_palette(112, P0, 16)
    palette_rotate(112, 16, (seq % 35) - 17)
}
fn draw() {
    cls(rgb(24,32,48))
    dither(seq % 2 == 1)
    if stress {
        for layer in 0..8 {
            sprite_ex(tex_page(3, 1, false), seq % 32, seq % 24, 192, 192,
                      0, 4, 320, 232, rgb(128,128,128), layer % 4)
        }
    }
    for i in 0..20 {
        let x = (i % 5) * 64 - 5 + (seq * (i % 3 + 1)) % 17
        let y = (i / 5) * 58 + 12 + (seq * (i % 2 + 1)) % 11
        let skew = (seq + i * 3) % 19 - 9
        var u = (seq * 7 + i * 13) % 180
        var v = (seq * 5 + i * 17) % 180
        if i % 5 == 4 && i % 3 != 0 { u = 224 + seq % 32; v = 230 + seq % 26 }
        var page = tex_page(8, 0, true)
        if i % 4 == 1 { page = tex_page(3, 1, false) }
        if i % 4 == 2 { page = tex_page(15, 250, false) }
        if i % 4 == 3 { page = tex_page(8, 7, true) }
        let tint = rgb(65 + (seq * 3 + i * 11) % 190,
                       63 + (seq * 5 + i * 7) % 190,
                       67 + (seq * 7 + i * 3) % 188)
        let mode = ((seq / 8 + i) % 5) - 1
        if i % 3 == 0 {
            // Exact 1:1 mirror, plus scaled mirrored cases.
            if i % 6 == 0 {
                u = 224 + seq % 32
                sprite_ex(page, u, v, -47, 43, x, y, 47, 43, tint, mode)
            } else {
                v = 230 + seq % 26
                sprite_ex(page, u, v, 47, -43, x, y, 53, 49, tint, mode)
            }
        } else {
            var xs: [4]s32
            var ys: [4]s32
            xs[0] = x + skew
            xs[1] = x + 57
            xs[2] = x
            xs[3] = x + 57 - skew
            ys[0] = y
            ys[1] = y + skew
            ys[2] = y + 49 - skew
            ys[3] = y + 49
            sprite_corners(page, u, v, 47, 43, &xs[0], &ys[0], tint, mode)
        }
    }
    // Pixel marker independently checks the presentation-to-sequence mapping.
    for bit in 0..16 {
        var colour = rgb(0,0,0)
        if ((seq >> bit) & 1) != 0 { colour = rgb(255,255,255) }
        rect(bit * 4, 0, 4, 4, colour)
    }
}
'''
    (CART / 'textures.akr').write_text(source)


class State:
    def __init__(self):
        self.texture = np.zeros(524288, dtype=np.uint8)
        wrap = np.frombuffer(art(False, 1), dtype=np.uint8)
        self.texture[15 * 32768:] = wrap[:32768]
        self.texture[:32768] = wrap[32768:]
        self.palette = np.zeros(4096, dtype=np.int64)
        self.palette[2560:2816] = palette_key(1)
        self.keys = [palette_key(i).astype(np.int64) for i in range(2)]

    def advance(self, seq):
        if seq % 8 == 0:
            self.texture[8 * 32768:9 * 32768] = np.frombuffer(art(True, (seq // 8) % 2), dtype=np.uint8)
        if seq % 12 == 0:
            self.texture[3 * 32768:5 * 32768] = np.frombuffer(art(False, (seq // 12) % 2), dtype=np.uint8)
        addresses = 8 * 32768 + (seq % 32) * 128 + np.arange(32)
        self.texture[addresses] = (seq * 17 + np.arange(32) * 11 + 1) % 256
        for start, count, a, b in [(0, 16, 0, 1), (256, 256, 1, 0)]:
            channels = np.array([0, 5, 10])
            ac = (self.keys[a][:count, None] >> channels) & 31
            bc = (self.keys[b][:count, None] >> channels) & 31
            out = ac + ((bc - ac) * (seq % 33)) // 32
            self.palette[start:start + count] = out @ np.array([1, 32, 1024])
        self.palette[112:128] = np.roll(self.keys[0][:16], -((seq % 35) - 17))


def quad(positions, uv, tint, slot=0, four=False, pal=0, mode=-1, textured=True):
    return {'flags': 4 | (2 if textured else 0) | (8 if mode >= 0 else 0),
            'pos': positions, 'uv': uv, 'cols': [tint] * 4,
            'slot': slot, 'four': four, 'pal': pal, 'blend': max(0, mode)}


def packets(seq, stress):
    result = []
    if stress:
        for layer in range(8):
            u, v = seq % 32, seq % 24
            result.append(quad([[0, 4], [320, 4], [0, 236], [320, 236]],
                               [[u, v], [u + 192, v], [u, v + 192], [u + 192, v + 192]],
                               [128] * 3, 3, False, 1, layer % 4))
    for i in range(20):
        x = (i % 5) * 64 - 5 + (seq * (i % 3 + 1)) % 17
        y = (i // 5) * 58 + 12 + (seq * (i % 2 + 1)) % 11
        skew = (seq + i * 3) % 19 - 9
        u, v = (seq * 7 + i * 13) % 180, (seq * 5 + i * 17) % 180
        if i % 5 == 4 and i % 3 != 0:
            u, v = 224 + seq % 32, 230 + seq % 26
        slot, four, pal = [(8, True, 0), (3, False, 1),
                           (15, False, 250), (8, True, 7)][i % 4]
        tint = [65 + (seq * 3 + i * 11) % 190,
                63 + (seq * 5 + i * 7) % 190,
                67 + (seq * 7 + i * 3) % 188]
        mode = ((seq // 8 + i) % 5) - 1
        if i % 3 == 0:
            w, h = (47, 43) if i % 6 == 0 else (53, 49)
            pos = [[x, y], [x + w, y], [x, y + h], [x + w, y + h]]
            if i % 6 == 0:
                u = 224 + seq % 32
                ua = min(u + 46, 255)
                uv = [[ua, v], [u, v], [ua, v + 43], [u, v + 43]]
            else:
                v = 230 + seq % 26
                va = min(v + 42, 255)
                uv = [[u, va], [u + 47, va], [u, v], [u + 47, v]]
        else:
            pos = [[x + skew, y], [x + 57, y + skew],
                   [x, y + 49 - skew], [x + 57 - skew, y + 49]]
            ub, vb = min(u + 47, 255), min(v + 43, 255)
            uv = [[u, v], [ub, v], [u, vb], [ub, vb]]
        result.append(quad(pos, uv, tint, slot, four, pal, mode))
    for bit in range(16):
        x = bit * 4
        result.append(quad([[x, 0], [x + 4, 0], [x, 4], [x + 4, 4]],
                           [[0, 0]] * 4, [255 if seq & (1 << bit) else 0] * 3, textured=False))
    return result


def marker(image):
    a = np.array(image)
    return sum((1 << bit) for bit in range(16) if a[1, bit * 4 + 1, 0] > 128)


def run_case(rom, out, stress, ticks):
    name = 'overload' if stress else 'normal'
    directory = out / name
    directory.mkdir(exist_ok=True)
    stats = directory / 'stats.csv'
    prefix = directory / 'actual'
    subprocess.run([str(common.HEADLESS), str(rom),
                    '--frames', str(ticks), '--input', '0:10' if stress else '0:0',
                    '--dump-every', '1', str(prefix), '--gpu-stats', str(stats), '--quiet'],
                   check=True)
    rows = [{k: int(v) for k, v in row.items()} for row in csv.DictReader(stats.open())]
    if not rows:
        raise RuntimeError('No frames presented')
    state, frames, reports = State(), [], []
    negative_controls = {}
    last_image = None
    last_tick = -1
    hold_errors = []
    for seq, row in enumerate(rows):
        tick = row['tick']
        # Every non-presentation tick must retain the preceding displayed image.
        for held in range(last_tick + 1, tick):
            if last_image is not None:
                image = Image.open(directory / f'actual_{held:05d}.ppm').convert('RGB')
                if image.tobytes() != last_image.tobytes():
                    hold_errors.append(held)
        previous_texture, previous_palette = state.texture.copy(), state.palette.copy()
        state.advance(seq)
        expected = oracle.rgb_image(oracle.render({'background': BG}, {'dither': bool(seq % 2)},
                                                 packets(seq, stress and seq > 0), state.texture, state.palette))
        actual = Image.open(directory / f'actual_{tick:05d}.ppm').convert('RGB')
        if seq == 8:
            for label, texture, palette in [('stale_texture_upload', previous_texture, state.palette),
                                             ('one_frame_palette_lag', state.texture, previous_palette)]:
                broken = oracle.rgb_image(oracle.render({'background': BG}, {'dither': bool(seq % 2)},
                                                       packets(seq, stress), texture, palette))
                negative_controls[label] = oracle.compare(np.array(expected), np.array(broken))['different_pixels']
                if not negative_controls[label]:
                    raise RuntimeError(f'Negative control did not detect {label}')
        report = {'sequence': seq, 'presented_tick': tick, 'marker': marker(actual),
                  **oracle.compare(np.array(expected), np.array(actual))}
        report['mapping_ok'] = report['marker'] == seq
        reports.append(report)
        expected.save(directory / f'oracle_{seq:05d}.png')
        actual.save(directory / f'mei_{seq:05d}.png')
        diff = np.zeros((240, 320, 3), dtype=np.uint8)
        diff[np.any(np.array(expected) != np.array(actual), axis=2)] = [255, 40, 90]
        sheet = Image.new('RGB', (960, 264), (15, 19, 28))
        draw = ImageDraw.Draw(sheet)
        for i, (label, image) in enumerate([('Independent texture/time oracle', expected),
                                          ('Mei', actual), ('Difference (pink)', Image.fromarray(diff))]):
            draw.text((i * 320 + 4, 4), f'{label}: frame {seq}, tick {tick}', fill='white')
            sheet.paste(image, (i * 320, 24))
        sheet.save(directory / f'comparison_{seq:05d}.png')
        frames.append((tick, sheet))
        last_image, last_tick = actual, tick
    for held in range(last_tick + 1, ticks):
        image = Image.open(directory / f'actual_{held:05d}.ppm').convert('RGB')
        if image.tobytes() != last_image.tobytes():
            hold_errors.append(held)
    duration = [max(17, (frames[i + 1][0] - tick) * 17) if i + 1 < len(frames) else 100
                for i, (tick, _) in enumerate(frames)]
    frames[0][1].save(out / f'{name}_comparison.gif', save_all=True,
                      append_images=[image for _, image in frames[1:]],
                      duration=duration, loop=0, optimize=False)
    picks = sorted(set([0, min(7, len(frames) - 1), min(15, len(frames) - 1),
                        min(31, len(frames) - 1), len(frames) - 1]))
    gallery = Image.new('RGB', (960, 264 * len(picks)))
    for i, pick in enumerate(picks):
        gallery.paste(frames[pick][1], (0, i * 264))
    gallery.save(out / f'{name}_contact.png')
    summary = {'case': name, 'ticks': ticks, 'presented_frames': len(rows),
               'different_pixels': sum(r['different_pixels'] for r in reports),
               'mapping_errors': sum(not r['mapping_ok'] for r in reports),
               'hold_errors': hold_errors, 'gpu_wait_ticks': sum(r['gpu_lag'] for r in rows),
               'max_frame_ticks': max(r['ticks'] for r in rows),
               'max_gpu_cycles': max(r['gpu_cycles'] for r in rows),
               'dropped_triangles': sum(r['tris_dropped'] for r in rows),
               'negative_controls': negative_controls, 'frames': reports}
    (directory / 'report.json').write_text(json.dumps(summary, indent=2) + '\n')
    print(json.dumps({k: v for k, v in summary.items() if k != 'frames'}), flush=True)
    return summary


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out', type=Path, default=common.OUT / 'textures')
    parser.add_argument('--frames', type=int, default=96)
    parser.add_argument('--stress-ticks', type=int, default=64)
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    generate()
    rom = common.compile_cart('textures')
    results = [run_case(rom, args.out, False, args.frames),
               run_case(rom, args.out, True, args.stress_ticks)]
    (args.out / 'report.json').write_text(json.dumps(results, indent=2) + '\n')
    return int(any(r['different_pixels'] or r['mapping_errors'] or r['hold_errors'] or
                   r['dropped_triangles'] for r in results))


if __name__ == '__main__':
    raise SystemExit(main())
