"""Render the exported mesh with Mei's real compiler and headless GPU, not a proxy."""
import math
from pathlib import Path

from kitcore import native
from kitcore.native import png_bytes  # noqa: F401 (re-exported for visibility.py)
from .geometry import AssetError


VIEWS = [('isometric',-0.65,-0.35),('front',0,0),('right',-math.pi/2,0),
         ('back',math.pi,0),('top',0,-math.pi/2),('rear_quarter',2.5,-0.35)]


def source(name, bounds, yaw=-0.65, pitch=-0.35, view='isometric', distance_scale=1.0, load=False):
    lo,hi = bounds['min'],bounds['max']
    center = [(a+b)/2 for a,b in zip(lo,hi)]
    scale = min(8192,2/max(b-a for a,b in zip(lo,hi)))
    radius = math.sqrt(sum(((b-a)*scale/2)**2 for a,b in zip(lo,hi)))
    distance = max(1, radius*2.6)*distance_scale
    eye = (-math.sin(yaw)*math.cos(pitch)*distance,-math.sin(pitch)*distance,-math.cos(yaw)*math.cos(pitch)*distance)
    f = lambda n: f'{n:.7f}'
    # Palette-backed assets load their swatch and default palette once.
    init = f'fn init() {{ asset_{name}_load() }}\n\n' if load else ''
    return f'''// Generated by Mei Asset Kit. This displays the original exported mesh.
cart "Asset preview"
import "{name}.akr"

{init}fn draw() {{
    cls(rgb(24, 28, 36))
    camera_clip(0.1, {f(distance+radius+1)})
    camera_look(vec3({', '.join(f(n) for n in eye)}), {f(yaw)}, {f(pitch)})
    var model = mat4_scale(vec3({f(scale)}, {f(scale)}, {f(scale)}))
    model[0].w = {f(-center[0]*scale)}
    model[1].w = {f(-center[1]*scale)}
    model[2].w = {f(-center[2]*scale)}
    mesh_xf(ASSET_{name.upper()}, model)
    text(8, 8, "{name.upper()}", rgb(224, 230, 240))
    text(8, 224, "{view.upper()}", rgb(140, 165, 190))
}}
'''


def render(directory, name, bounds, compiler, runner, load=False):
    directory = Path(directory).resolve()
    native.require('/preview',(compiler,runner),error=AssetError)
    def run(args): native.run(args,'/preview',error=AssetError)
    images, reports = [],[]
    for view,yaw,pitch in VIEWS:
        stem = directory/f'view_{view}'
        stem.with_suffix('.akr').write_text(source(name,bounds,yaw,pitch,view,load=load))
        run([compiler,stem.with_suffix('.akr'),'-o',stem.with_suffix('.mei')])
        run([runner,stem.with_suffix('.mei'),'--frames','4','--dump',stem.with_suffix('.ppm'),
             '--gpu-stats',stem.with_suffix('.csv')])
        pixels = native.read_ppm(stem.with_suffix('.ppm'),'/preview',error=AssetError)
        stem.with_suffix('.png').write_bytes(png_bytes(320,240,pixels))
        images.append(pixels)
        latest = native.last_frame_stats(stem.with_suffix('.csv'))
        if latest is None:
            raise AssetError('/preview',f'No presented frame for {view}.')
        reports.append({'view':view,'image':stem.with_suffix('.png').name,'stats':latest})
    contact = directory/'contact.png'
    contact.write_bytes(native.contact_sheet(images))
    return {'contact':str(contact),'views':reports}
