"""Render the exported mesh with Mei's real compiler and headless GPU, not a proxy."""
import csv
import math
from pathlib import Path
import struct
import subprocess
import zlib

from .geometry import AssetError


VIEWS = [('isometric',-0.65,-0.35),('front',0,0),('right',-math.pi/2,0),
         ('back',math.pi,0),('top',0,-math.pi/2),('rear_quarter',2.5,-0.35)]


def source(name, bounds, yaw=-0.65, pitch=-0.35, view='isometric', distance_scale=1.0):
    lo,hi = bounds['min'],bounds['max']
    center = [(a+b)/2 for a,b in zip(lo,hi)]
    scale = min(8192,2/max(b-a for a,b in zip(lo,hi)))
    radius = math.sqrt(sum(((b-a)*scale/2)**2 for a,b in zip(lo,hi)))
    distance = max(1, radius*2.6)*distance_scale
    eye = (-math.sin(yaw)*math.cos(pitch)*distance,-math.sin(pitch)*distance,-math.cos(yaw)*math.cos(pitch)*distance)
    f = lambda n: f'{n:.7f}'
    return f'''// Generated by Mei Asset Kit. This displays the original exported mesh.
cart "Asset preview"
import "{name}.akr"

fn draw() {{
    cls(rgb(24, 28, 36))
    camera_clip(0.1, {f(distance+radius+1)})
    camera_look(vec3({', '.join(f(n) for n in eye)}), {f(yaw)}, {f(pitch)})
    var model = mat4_scale(vec3({f(scale)}, {f(scale)}, {f(scale)}))
    model[0].w = {f(-center[0]*scale)}
    model[1].w = {f(-center[1]*scale)}
    model[2].w = {f(-center[2]*scale)}
    mesh_xf(ASSET_{name.upper()}, model)
    text(8, 8, "{name.upper()}", rgb(224, 230, 240))
    text(8, 224, "{view.upper()}", rgb(140, 165, 190))
}}
'''


def png_bytes(width, height, pixels):
    def chunk(kind, data):
        return struct.pack('>I',len(data))+kind+data+struct.pack('>I',zlib.crc32(kind+data)&0xffffffff)
    rows = b''.join(b'\0'+pixels[y*width*3:(y+1)*width*3] for y in range(height))
    return (b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR',struct.pack('>2I5B',width,height,8,2,0,0,0))+
            chunk(b'IDAT',zlib.compress(rows,9))+chunk(b'IEND',b''))


def render(directory, name, bounds, compiler, runner):
    directory = Path(directory).resolve()
    for executable in (compiler,runner):
        if not Path(executable).is_file():
            raise AssetError('/preview',f'Missing {executable}. Run make to build Mei, or pass --compiler/--runner.')
    def run(args):
        try:
            result = subprocess.run([str(a) for a in args],capture_output=True,text=True,timeout=45)
        except (OSError,subprocess.TimeoutExpired) as error:
            raise AssetError('/preview',str(error)) from error
        if result.returncode:
            raise AssetError('/preview',(result.stderr+'\n'+result.stdout).strip()[-4000:])
    images, reports = [],[]
    for view,yaw,pitch in VIEWS:
        stem = directory/f'view_{view}'
        stem.with_suffix('.akr').write_text(source(name,bounds,yaw,pitch,view))
        run([compiler,stem.with_suffix('.akr'),'-o',stem.with_suffix('.mei')])
        run([runner,stem.with_suffix('.mei'),'--frames','4','--dump',stem.with_suffix('.ppm'),
             '--gpu-stats',stem.with_suffix('.csv')])
        header,width_height,maxval,pixels = stem.with_suffix('.ppm').read_bytes().split(b'\n',3)
        if (header,width_height,maxval,len(pixels)) != (b'P6',b'320 240',b'255',320*240*3):
            raise AssetError('/preview','Headless runner produced an unexpected image format.')
        stem.with_suffix('.png').write_bytes(png_bytes(320,240,pixels))
        images.append(pixels)
        with stem.with_suffix('.csv').open() as stream:
            frames = list(csv.DictReader(stream))
        if not frames:
            raise AssetError('/preview',f'No presented frame for {view}.')
        latest = {k:int(v) for k,v in frames[-1].items()}
        reports.append({'view':view,'image':stem.with_suffix('.png').name,'stats':latest})
    pixels = bytearray(960*480*3)
    for i,img in enumerate(images):
        x,y = (i%3)*320,(i//3)*240
        for row in range(240):
            start = ((y+row)*960+x)*3
            pixels[start:start+960] = img[row*960:(row+1)*960]
    contact = directory/'contact.png'
    contact.write_bytes(png_bytes(960,480,pixels))
    return {'contact':str(contact),'views':reports}
