"""The CLI's published JSON Schema and its dependency-free validation subset.

Keep the recipe contract and validation together: unknown properties are errors,
so a misspelled modeling instruction never silently disappears from an asset.
"""
from kitcore.schema import (number, integer, array, obj, choice, ref, NAME, BOOL, COLOR,  # noqa: F401
                            validator)
from .geometry import AssetError


NUM = number(-32767,32767)
POS = dict(number(0,32767), exclusiveMinimum=0)
VEC = array(NUM,3,3)
POINT = array(NUM,2,2)
TRANSFORM = obj({'translate':VEC,'rotate':VEC,'scale':VEC,'pivot':VEC})
MATERIAL = obj({'color':{'type':'string','pattern':r'^#[0-9a-fA-F]{6}$'},
                'smooth':BOOL,'double_sided':BOOL,
                'palette':dict(BOOL,description='Draw through a 4-bit palette entry (a textured swatch face tinted by the baked shade), so rewriting the palette recolours it. Default false; true for emissive.'),
                'class':dict(choice('surface','emissive'),description='emissive: own palette entries, never shaded, reported separately. Default surface.'),
                'tag':dict(NAME,description='Opaque surface tag carried to the material manifest; not interpreted by the kit.'),
                'share':dict(BOOL,description='Palette-backed materials only. Default true: share a palette entry with every material of the same class and colour. false: an entry of its own, so it can be recoloured separately.')}, ['color'])
TEXTURE = dict(obj({
    'pattern':dict(choice('brick','tile','planks','grain','checker','stripes','lattice','speckle'),
                   description='A procedural pattern generated by the kit (deterministic); colours from colors, parameters in params.'),
    'params':dict({'type':'object','maxProperties':16,'additionalProperties':{}},
                  description='Pattern parameters; each pattern has its own (docs/ASSETKIT.md). Unknown ones are errors.'),
    'size':dict({},description='Pattern size in texels: one integer (square) or [width, height], 1-255. Default 16.'),
    'texels':dict(array({'type':'string','pattern':r'^[0-9a-fA-F]{1,255}$'},1,255),
                  description='Rows of hex digits, top row first; digit k is colors[k].'),
    'colors':dict(array(COLOR,1,16),description='Colours of a pattern (in the order the pattern names them) or of a texel grid.'),
    'clear':dict(COLOR,description='Pattern or texel grid: this colour (one of colors) is a hole (texel 0). Cutouts need verification.depth.'),
    'image':dict({'type':'string','minLength':1,'maxLength':200},description="A PNG file, relative to the recipe's folder. Pixels with alpha below one half are holes."),
    'sheet':dict(NAME,description="A sheet declared in the recipe's sheets, with cell, or frames and ticks."),
    'cell':dict({},description="A grid sheet's [column, row], or the name of a cell in the sheet's NAME.sheet.json."),
    'frames':dict(array({},2,64),description='Cells of an animation, in order; every frame the same size.'),
    'ticks':dict(integer(1,255),description='Ticks (60 a second) each frame of an animation shows.'),
    'bits':dict(choice(4,8),description='4 (default): at most 15 colours, a 16-colour palette. 8: at most 255 colours, twice the VRAM.'),
    'projection':dict(choice('planar','box','cylindrical','disc','fit'),
                      description="How faces get texture coordinates, from their primitive's own coordinates. planar, box and cylindrical repeat the texture (scale: world units per repeat); disc and fit draw it once. Default box."),
    'axis':dict(choice('x','y','z'),description='planar: the axis it projects along (default z); disc: the axis of the disc (default y).'),
    'scale':dict(array(POS,2,2),description="planar, box, cylindrical: world units per repeat along the texture's u and v (default [1, 1]); cylindrical rounds the repeats around to a whole number. disc: the world units the texture spans (default the primitive's diameter)."),
    'offset':dict(array(number(-256,256),2,2),description='Added to the coordinates, in repeats (fractions of the texture).'),
    'rotate':dict(choice(0,90,180,270),description='Turn the texture clockwise on the surface.'),
    'flip':dict(choice('u','v','both'),description='Mirror the texture along u, v or both.'),
}),description='A texture on the material\'s faces (docs/ASSETKIT.md, "Textures"). The material\'s color is its colour in exchange formats.')
MATERIAL['properties']['texture'] = TEXTURE
SHEET = dict(obj({'image':{'type':'string','minLength':1,'maxLength':200},
                  'grid':dict(array(integer(1,256),2,2),description="Cell width and height: cells are named [column, row]. Without it, cells are named in the image's NAME.sheet.json.")},['image']),
             description='A PNG holding many textures: an authoring container that the kit slices.')
PALETTE_LAYOUT = dict(obj({'slot':integer(0,31),'row':integer(0,255),'first':integer(0,510)}),
                      description='Where palette-backed materials live: swatch texels u 0-15 of row `row` in texture slot `slot` (0-31 but not 15, the fonts\'; default 14, 0); entries from 4-bit palette `first` (0-511, not running into 255, the fonts\'; default 0).')
VERIFICATION = obj({'required':BOOL,'yaw_steps':integer(4,120),
                    'pitches':array(number(-1.4,1.4),1,5),
                    'distances':array(number(.8,3),1,3),'far':number(1,1000),'geometry':choice('error','warn'),
                    'yaw_range_degrees':dict(array(number(-360,360),2,2),description='Sample camera yaws from the first to the second (degrees, both included) instead of the whole circle: a camera at yaw 0 stands on the -Z side looking toward +Z, at 90 on the -X side. For an asset seen from one side only (one mounted on a wall).'),
                    'edge_margin':dict(number(0,4),description='Pixels: depth order is judged only where the nearest face covers a pixel at least this far inside and no other face within this distance is nearer, as the World Checker\'s ordering.edge_margin (default 1). 0 judges every pixel. Coverage is always exact.'),
                    'depth':dict(BOOL,description='The asset is drawn with the depth buffer (render_depth(true), docs/RENDERING.md): depth order is judged as the depth test draws it, with a tie tolerance of two steps of the depth key; surface intersections and ordering cycles are reported but do not fail; coplanar overlaps and duplicates still do. Default false.'),
                    'depth_views':dict(integer(1,600),description='With depth: how many views of the sweep the reference judges, chosen from what the console draws in every view so that they draw every face (and cutout texel) the sweep draws, more if the cover needs it (docs/ASSETKIT.md, "Depth mode"). Default 16; the sweep\'s size or more judges every view. Without depth every view is judged.'),
                    'perspective':dict(BOOL,description='The asset is drawn with perspective-correct texturing (render_perspective(true)); the verification cart draws so. Default false.'),
                    'scale':dict(choice('fit','world'),description='fit (default): the mesh scaled to about 2 units, as a prop. world: at its own size, so its faces sort in buckets of far/1024 units as in a world (far: the world\'s near range, about 96).')})


def operation(name, props, required=(), common=None):
    return obj(dict(common or {}, op={'const':name}, **props), ['op', *required])


MODIFIERS = {'oneOf':[
    operation('mirror', {'axis':choice('x','y','z'),'offset':NUM,'keep_original':BOOL}, ['axis']),
    operation('array', {'count':integer(1,128),'step':VEC}, ['count','step']),
    operation('radial', {'count':integer(1,128),'axis':choice('x','y','z'),'degrees':NUM}, ['count']),
    operation('taper', {'top':POS,'bottom':POS}, ['top']),
    operation('twist', {'degrees':NUM}, ['degrees']),
    operation('subdivide', {'levels':integer(1,3)}, ['levels']),
]}
BOX_SIDES = ('top','bottom','left','right','back','front')
BOX_AXES = ('+y','-y','-x','+x','-z','+z')       # the same sides by axis
COMMON = {'id':NAME,'material':NAME,'transform':TRANSFORM,'modifiers':array(MODIFIERS,0,16)}


def faces_map(*sides):
    return dict(obj({side:NAME for side in sides}),
                description='A material per side, replacing the node\'s material there: '+', '.join(sides)+
                            '. Sides not named keep the node\'s material. Adds no triangles.')


DECAL = obj({'id':NAME,
             'face':dict({},description='The flat face the decal lies on: a side name (a box\'s top, bottom, left, right, '
                                         'back, front or +y, -y, -x, +x, -z, +z; a cylinder, cone, lathe or loft\'s top or bottom; '
                                         'an extrusion\'s front or back), or a mesh node\'s polygon index.'),
             'material':NAME,
             'at':dict(POINT,description='The decal\'s centre, from the face\'s centre (the middle of its bounding rectangle), '
                                         'right and up as the face is seen from outside, in the primitive\'s own units. Default [0, 0].'),
             'size':dict(array(POS,2,2),description='Width and height in the primitive\'s own units.')},
            ['face','material','size'])
DECALS = dict(array(DECAL,1,32),
              description='Rectangles baked into flat faces of this primitive: each becomes two faces of its material, '
                          'and its face is cut around it (8 more triangles and 4 vertices a decal). In the face\'s plane, '
                          'so nothing overlaps. A textured decal material draws its texture once over the rectangle '
                          '(projection fit).')
CAPPED = {**COMMON,'faces':faces_map('top','bottom','side','+y','-y'),'decals':DECALS}
NODE = {'oneOf':[
    operation('box', {'size':array(POS,3,3),
                      'open':dict(array(choice(*BOX_SIDES,*BOX_AXES),1,5),description='Faces to leave out: top (+Y), bottom (-Y), left (-X), right (+X), back (-Z), front (+Z), or by axis: +y, -y, -x, +x, -z, +z. For a ground tile ["bottom"], for a building standing on the ground ["bottom"].')},
              ['size'], {**COMMON,'faces':faces_map(*BOX_SIDES,*BOX_AXES),'decals':DECALS}),
    operation('sphere', {'radius':POS,'rings':integer(2,64),'segments':integer(3,128)}, ['radius'], COMMON),
    operation('cylinder', {'radius':POS,'height':POS,'segments':integer(3,128),'caps':BOOL}, ['radius','height'], CAPPED),
    operation('cone', {'radius':POS,'height':POS,'segments':integer(3,128),'caps':BOOL}, ['radius','height'], CAPPED),
    operation('lathe', {'profile':array(POINT,2,128),'segments':integer(3,128),'caps':BOOL}, ['profile'], CAPPED),
    operation('extrude', {'points':array(POINT,3,256),'depth':POS}, ['points','depth'],
              {**COMMON,'faces':faces_map('front','back','side','+z','-z'),'decals':DECALS}),
    operation('loft', {'sections':array(obj({'y':NUM,'points':array(POINT,3,256)}, ['y','points']),2,128),'caps':BOOL}, ['sections'], CAPPED),
    operation('mesh', {'vertices':array(VEC,3,8192),'faces':array(array(integer(0,8191),3,256),1,8192),
                       'decals':DECALS,
                       'face_materials':array(NAME,1,8192),
                       'uvs':dict(array(array(number(-256,256),2,2),3,8192),description="Hand texture coordinates, one [u, v] per vertex, in repeats (1 = the texture's width or height), top-left 0: used instead of the material's projection on textured faces.")},
              ['vertices','faces'], COMMON),
    operation('group', {'children':array(ref('node'),1,128)}, ['children'], COMMON),
    operation('instance', {'ref':NAME}, ['ref'], COMMON),
]}
LOD = dict(obj({
    'levels':dict(array(obj({'distance':dict(POS,description='Drawn from this distance (units, from the viewer to the placed mesh\'s centre) out to the next level\'s.'),
                             'nodes':array(ref('node'),1,128)},['distance','nodes']),1,7),
                  description='Coarser levels after the recipe\'s own nodes (level 0), at increasing distances. Each shares the recipe\'s materials, prototypes, lighting, budget and verification policy.'),
    'cull':dict(POS,description='Not drawn at all from this distance on. Default: never culled by distance.'),
    'band':dict(number(0,1000),description='Hysteresis (units): a level changes only once the distance is this far past its switch distance. Default 1.'),
}),description='Levels of detail: simpler meshes for the same asset farther away. Generic; a consumer such as the World Kit chooses the level.')
SCHEMA = {
    '$schema':'https://json-schema.org/draft/2020-12/schema',
    'title':'Mei agent asset recipe v1',
    'description':'Y-up, units in Mei world units. Degrees. Transforms: scale about pivot, rotate X/Y/Z, translate. Geometry uses outward right-handed normals; exporter converts to Mei winding.',
    **obj({
        'format':{'const':'mei-asset'},'version':{'const':1},'name':NAME,
        'materials':{'type':'object','propertyNames':NAME,'additionalProperties':MATERIAL,'maxProperties':128},
        'prototypes':{'type':'object','propertyNames':NAME,'additionalProperties':ref('node'),'maxProperties':128},
        'nodes':array(ref('node'),1,128),
        'lighting':obj({'direction':VEC,'ambient':number(0,1),'bake':BOOL,
                        'mode':dict(choice('directional','vertical'),description='vertical: shade by the face normal\'s Y only (tops light, walls mid, undersides dark), unchanged by any yaw. Default directional.')}),
        'palette_layout':PALETTE_LAYOUT,
        'sheets':{'type':'object','propertyNames':NAME,'additionalProperties':SHEET,'maxProperties':32},
        'budget':obj({'vertices':integer(3,2048),'triangles':integer(1,4000)}),
        'verification':VERIFICATION,
        'lod':LOD,
    }, ['format','version','name','nodes']),
    '$defs':{'node':NODE},
}


# validate(value, schema=SCHEMA, path='', depth=0) raises AssetError at the first problem.
validate = validator(SCHEMA, AssetError)
