/* Audio: sixteen sample channels (8-bit, 16-bit or 4-bit ADPCM) and a global reverb,
 * mixed to 22,050 Hz stereo, integer-only. docs/DECISIONS.md ("Audio upgrade") is the reference. */
#include "machine.h"

#include <string.h>

/* floor(x / 2^s) without relying on implementation-defined >> of negatives. */
static inline int32_t asr8(int32_t x) { return x >= 0 ? x >> 8 : ~((~x) >> 8); }
static inline int64_t asr64(int64_t x, int s) { return x >= 0 ? x >> s : ~((~x) >> s); }
/* x / 2^15 rounded toward zero: what every feedback product in the reverb uses, so a
 * silent reverb always decays to exactly zero. */
static inline int32_t q15t(int64_t x) { return (int32_t)(x >= 0 ? x >> 15 : -((-x) >> 15)); }
static inline int32_t clampi(int64_t x, int32_t lim) { return (int32_t)(x < -lim ? -lim : x > lim ? lim : x); }

/* ------------------------------------------------------------------ reverb presets */

/* Presets 1-4 are an 8-line feedback delay network: predelay, four Schroeder allpass
 * diffusers, then eight delay lines, each with a one-pole damping filter and a gain, mixed
 * by an 8x8 Hadamard matrix. Gains and damping follow Jot's absorbent-filter design for the
 * RT60 and high-frequency ratio below; tools/gen_reverb_tables.py computes them. Preset 5
 * is a ping-pong echo on lines 0-1. All values are Q15. */
typedef struct {
    uint16_t pre;          /* predelay, samples (>= 1) */
    uint16_t ap[4];        /* diffuser allpass delays */
    int32_t ap_g;          /* diffuser coefficient */
    uint16_t len[8];       /* delay line lengths */
    int32_t damp[8];       /* damping filter coefficient a: lp += a (x - lp) */
    int32_t gain[8];       /* loop gain (FDN: includes the matrix's 1/sqrt(8)) */
    int32_t out;           /* output gain */
    int echo;
} RevPreset;

#ifndef REV_TABLE_CONST
#define REV_TABLE_CONST const
#endif
/* BEGIN generated by tools/gen_reverb_tables.py */
static REV_TABLE_CONST RevPreset rev_presets[6] = {
    {0},
    /* 1 room: RT60 0.65 s at DC, HF ratio 0.45, predelay 4 ms */
    {88, {71, 113, 163, 229}, 22938, {419, 461, 523, 587, 659, 727, 811, 887},
     {26253, 25600, 24636, 23641, 22521, 21464, 20158, 18976},
     {9467, 9277, 9004, 8730, 8433, 8161, 7837, 7555}, 6812, 0},
    /* 2 studio: RT60 1.2 s at DC, HF ratio 0.6, predelay 8 ms */
    {176, {97, 131, 193, 277}, 22938, {557, 613, 701, 787, 881, 977, 1087, 1201},
     {30650, 30437, 30103, 29776, 29418, 29053, 28635, 28202},
     {10017, 9872, 9648, 9434, 9205, 8977, 8723, 8467}, 5718, 0},
    /* 3 hall: RT60 2.6 s at DC, HF ratio 0.4, predelay 20 ms */
    {441, {142, 107, 379, 277}, 22938, {1153, 1327, 1559, 1801, 2087, 2311, 2633, 2903},
     {26793, 25891, 24689, 23435, 21953, 20792, 19124, 17724},
     {10083, 9873, 9601, 9325, 9009, 8769, 8436, 8166}, 6626, 0},
    /* 4 space: RT60 6.5 s at DC, HF ratio 0.5, predelay 45 ms */
    {992, {173, 233, 409, 557}, 22938, {1559, 1801, 2087, 2311, 2633, 2903, 3229, 3571},
     {30921, 30635, 30296, 30031, 29649, 29329, 28943, 28538},
     {10747, 10622, 10477, 10364, 10205, 10073, 9916, 9753}, 4889, 0},
    /* 5 echo: ping-pong, 5512 samples per side, feedback 0.6 */
    {1, {0, 0, 0, 0}, 0, {5512, 5512, 0, 0, 0, 0, 0, 0},
     {19661, 19661, 0, 0, 0, 0, 0, 0},
     {19661, 19661, 0, 0, 0, 0, 0, 0}, 30107, 1},
};
/* END generated */

#define REV_PRESETS 6
#define REV_IN_LIMIT   (1 << 20)   /* send bus clamp */
#define REV_SHIFT      6           /* internal precision: the network runs on samples x 64 */
#define REV_LINE_LIMIT (1 << 30)   /* delay line clamp (never reached by real signals) */
#define REV_OUT_LIMIT  (1 << 20)   /* wet output clamp, before the wet volume */
#define REV_DC_POLE    32604       /* input DC blocker, about 17 Hz */

static void reverb_gains(MeiReverb *rv) {
    const RevPreset *p = &rev_presets[rv->preset];
    uint32_t d = rv->decay & 0xFF;
    for (int i = 0; i < 8; i++)
        rv->gain[i] = d ? (int32_t)(((int64_t)p->gain[i] * d) >> 8) : p->gain[i];
}

/* Selects a preset; a change clears all reverb memory. */
static void reverb_select(MeiReverb *rv, uint32_t ctrl) {
    int p = (int)(ctrl & 15);
    if (p >= REV_PRESETS) p = 0;
    rv->ctrl = ctrl;
    if (p == rv->preset) return;
    rv->preset = p;
    rv->dc_x = rv->dc_y = 0;
    memset(rv->lp, 0, sizeof rv->lp);
    memset(rv->at, 0, sizeof rv->at);
    memset(rv->buf, 0, sizeof rv->buf);
    reverb_gains(rv);
}

/* Reads the oldest sample of a ring (base, len) at position *at and writes v in its place. */
static inline int32_t ring(int32_t *buf, uint32_t *at, uint32_t len, int32_t v) {
    int32_t *p = buf + *at;
    int32_t old = *p;
    *p = v;
    if (++*at == len) *at = 0;
    return old;
}

/* One stereo sample through the active preset. in_l/in_r are the summed send of the
 * channels (post-volume); the wet output is clamped to +-2^20. */
static void reverb_sample(MeiReverb *rv, int32_t in_l, int32_t in_r, int32_t *out_l, int32_t *out_r) {
    const RevPreset *p = &rev_presets[rv->preset];
    int32_t *buf = rv->buf;

    /* Mono input (the mean of the two sends) through a DC blocker. */
    int32_t x = clampi(asr64((int64_t)in_l + in_r, 1), REV_IN_LIMIT) * (1 << REV_SHIFT);
    int32_t y = x - rv->dc_x + q15t((int64_t)rv->dc_y * REV_DC_POLE);
    rv->dc_x = x;
    rv->dc_y = y;

    if (p->echo) {
        /* Ping-pong: the left line takes the input and the right line's damped output;
         * the right line takes the left's. */
        x = y;
        uint32_t n = p->len[0];
        int32_t dl = buf[rv->at[5]], dr = buf[n + rv->at[6]];
        rv->lp[0] = q15t((int64_t)dl * p->damp[0] + (int64_t)rv->lp[0] * (32768 - p->damp[0]));
        rv->lp[1] = q15t((int64_t)dr * p->damp[1] + (int64_t)rv->lp[1] * (32768 - p->damp[1]));
        int32_t wl = clampi((int64_t)x + q15t((int64_t)rv->lp[1] * rv->gain[1]), REV_LINE_LIMIT);
        int32_t wr = q15t((int64_t)rv->lp[0] * rv->gain[0]);
        ring(buf, &rv->at[5], n, wl);
        ring(buf + n, &rv->at[6], n, wr);
        *out_l = clampi(asr64((int64_t)dl * p->out, 15 + REV_SHIFT), REV_OUT_LIMIT);
        *out_r = clampi(asr64((int64_t)dr * p->out, 15 + REV_SHIFT), REV_OUT_LIMIT);
        return;
    }

    /* The predelay and the diffusers. */
    uint32_t base = 0;
    x = ring(buf, &rv->at[0], p->pre, y);
    base += p->pre;
    for (int k = 0; k < 4; k++) {
        int32_t d = buf[base + rv->at[1 + k]];
        int32_t v = clampi((int64_t)x + q15t((int64_t)d * p->ap_g), REV_LINE_LIMIT);
        x = clampi((int64_t)d - q15t((int64_t)v * p->ap_g), REV_LINE_LIMIT);
        ring(buf + base, &rv->at[1 + k], p->ap[k], v);
        base += p->ap[k];
    }

    /* The eight lines: damp, scale, mix (Hadamard butterflies), feed back with the input. */
    int32_t o[8];
    int64_t u[8];
    uint32_t lb[8];
    for (int i = 0; i < 8; i++) {
        lb[i] = base;
        o[i] = buf[base + rv->at[5 + i]];
        base += p->len[i];
        rv->lp[i] = q15t((int64_t)o[i] * p->damp[i] + (int64_t)rv->lp[i] * (32768 - p->damp[i]));
        u[i] = q15t((int64_t)rv->lp[i] * rv->gain[i]);
    }
    for (int h = 1; h < 8; h <<= 1)
        for (int i = 0; i < 8; i += h << 1)
            for (int j = i; j < i + h; j++) {
                int64_t a = u[j], b = u[j + h];
                u[j] = a + b;
                u[j + h] = a - b;
            }
    static const int8_t sign_in[8] = {1, 1, 1, 1, -1, -1, -1, -1};
    for (int i = 0; i < 8; i++)
        ring(buf + lb[i], &rv->at[5 + i], p->len[i], clampi(u[i] + sign_in[i] * x, REV_LINE_LIMIT));
    int64_t l = (int64_t)o[0] - o[1] + o[2] - o[3] + o[4] - o[5] + o[6] - o[7];
    int64_t r = (int64_t)o[0] + o[1] - o[2] - o[3] + o[4] + o[5] - o[6] - o[7];
    *out_l = clampi(asr64(l * p->out, 15 + REV_SHIFT), REV_OUT_LIMIT);
    *out_r = clampi(asr64(r * p->out, 15 + REV_SHIFT), REV_OUT_LIMIT);
}

/* ------------------------------------------------------------------ registers */

void audio_reset(Mei *m) {
    memset(m->ch, 0, sizeof m->ch);
    memset(m->audio_out, 0, sizeof m->audio_out);
    m->audio_frames = 0;
    m->audio_phase = 0;
    memset(&m->rev, 0, sizeof m->rev);
}

/* Channel for an I/O offset (relative to IO_BASE), or NULL. */
static MeiAudioChannel *chan_at(Mei *m, uint32_t off) {
    if (off - IO_AUDIO < 8 * 0x20) return &m->ch[(off - IO_AUDIO) >> 5];
    if (off - IO_AUDIO_HI < 8 * 0x20) return &m->ch[8 + ((off - IO_AUDIO_HI) >> 5)];
    return NULL;
}

int audio_io_read(Mei *m, uint32_t off, uint32_t *out) {
    if (off & 3) return -1;
    const MeiAudioChannel *c = chan_at(m, off);
    if (!c) {
        switch (off) {
        case IO_REV_CTRL:  *out = m->rev.ctrl; return 0;
        case IO_REV_VOL:   *out = m->rev.vol; return 0;
        case IO_REV_DECAY: *out = m->rev.decay; return 0;
        case IO_AUD_ACTIVE: {
            uint32_t v = 0;
            for (int i = 0; i < AUD_CHANNELS; i++) v |= (uint32_t)(m->ch[i].playing != 0) << i;
            *out = v;
            return 0;
        }
        default: return -1;
        }
    }
    switch (off & 0x1F) {
    case IO_AUD_ADDR:  *out = c->addr; return 0;
    case IO_AUD_LEN:   *out = c->len; return 0;
    case IO_AUD_LOOP:  *out = c->loop; return 0;
    case IO_AUD_PITCH: *out = c->pitch; return 0;
    case IO_AUD_VOL:   *out = c->vol; return 0;
    case IO_AUD_CTRL:  *out = (c->playing ? 1u : 0u) | (c->ctrl & 0x1E); return 0;
    case IO_AUD_POS:   *out = (uint32_t)(c->pos >> 16); return 0;
    default:           return -1;   /* +1C reserved */
    }
}

int audio_io_write(Mei *m, uint32_t off, uint32_t val) {
    if (off & 3) return -1;
    MeiAudioChannel *c = chan_at(m, off);
    if (!c) {
        switch (off) {
        case IO_REV_CTRL:  reverb_select(&m->rev, val); return 0;
        case IO_REV_VOL:   m->rev.vol = val; return 0;
        case IO_REV_DECAY: m->rev.decay = val; reverb_gains(&m->rev); return 0;
        case IO_AUD_ACTIVE: return -2;
        default: return -1;
        }
    }
    switch (off & 0x1F) {
    case IO_AUD_ADDR:  c->addr = val; return 0;
    case IO_AUD_LEN:   c->len = val; return 0;
    case IO_AUD_LOOP:  c->loop = val; return 0;
    case IO_AUD_PITCH: c->pitch = val; return 0;
    case IO_AUD_VOL:   c->vol = val; return 0;
    case IO_AUD_CTRL:
        if (val & AUD_CTRL_UPDATE) {   /* loop and reverb send only; keeps playing */
            const uint32_t live = AUD_CTRL_LOOP | AUD_CTRL_REVERB;
            c->ctrl = (c->ctrl & ~live) | (val & live);
            return 0;
        }
        c->ctrl = val;
        if (val & 1) { c->pos = 0; c->playing = 1; c->dec = 0; c->h1 = c->h2 = 0; }
        else c->playing = 0;
        return 0;
    case IO_AUD_POS:   return -2;
    default:           return -1;
    }
}

/* ------------------------------------------------------------------ channels */

/* Byte of sample memory (RAM or ROM), or -1 outside them. */
static inline int sample_byte(const Mei *m, uint64_t a) {
    if (a < RAM_BASE + RAM_SIZE) return m->ram[a];
    if (a >= ROM_BASE && a < ROM_BASE + ROM_WINDOW) return a - ROM_BASE < m->rom_len ? m->rom[a - ROM_BASE] : 0;
    return -1;
}

/* PS1 SPU predictor coefficients (/64); filters 5-15 predict nothing. */
static const int32_t ADPCM_K0[16] = {0, 60, 115, 98, 122};
static const int32_t ADPCM_K1[16] = {0, 0, -52, -55, -60};

int32_t audio_adpcm_sample(uint32_t header, uint32_t nibble, int32_t *h1, int32_t *h2) {
    int shift = (int)(header & 15);
    if (shift > 12) shift = 9;                     /* as on the PS1 */
    int f = (int)((header >> 4) & 15);
    int32_t t = (int32_t)(nibble & 15) - ((nibble & 8) ? 16 : 0);
    int32_t s = t * (1 << (12 - shift))
              + (int32_t)asr64((int64_t)*h1 * ADPCM_K0[f] + (int64_t)*h2 * ADPCM_K1[f] + 32, 6);
    if (s < -32768) s = -32768;
    if (s > 32767) s = 32767;
    *h2 = *h1;
    *h1 = s;
    return s;
}

/* Pointer to the 16 bytes of an ADPCM block if they all lie in RAM or all in the cart image. */
static inline const uint8_t *block_ptr(const Mei *m, uint64_t a) {
    if (a + 16 <= RAM_BASE + RAM_SIZE) return m->ram + a;
    if (a >= ROM_BASE && a + 16 <= ROM_BASE + (uint64_t)m->rom_len) return m->rom + (a - ROM_BASE);
    return NULL;
}

/* Decodes ADPCM samples up to and including idx (every one in order, so skipped samples
 * still update the history). Returns -1 if a byte it needs lies outside RAM/ROM. */
static int adpcm_decode_to(const Mei *m, MeiAudioChannel *c, uint64_t idx) {
    while (c->dec <= idx) {
        uint32_t n = c->dec;
        uint64_t a = (uint64_t)c->addr + (uint64_t)(n / 28) * 16;
        uint32_t j = n % 28;
        uint32_t last = idx - n < 27 - j ? j + (uint32_t)(idx - n) : 27;   /* last nibble needed */
        const uint8_t *p = block_ptr(m, a);
        if (p) {   /* the same steps as audio_adpcm_sample, with the header decoded once */
            int shift = p[0] & 15, f = p[0] >> 4;
            int32_t step = 1 << (12 - (shift > 12 ? 9 : shift)), k0 = ADPCM_K0[f], k1 = ADPCM_K1[f];
            int32_t h1 = c->h1, h2 = c->h2;
            for (; j <= last; j++) {
                uint32_t nib = ((j & 1) ? p[2 + (j >> 1)] >> 4 : p[2 + (j >> 1)]) & 15;
                int32_t v = ((int32_t)nib - ((nib & 8) ? 16 : 0)) * step
                          + (int32_t)asr64((int64_t)h1 * k0 + (int64_t)h2 * k1 + 32, 6);
                h2 = h1;
                h1 = v < -32768 ? -32768 : v > 32767 ? 32767 : v;
            }
            c->h1 = h1;
            c->h2 = h2;
        } else {   /* a block straddling the end of RAM or of the cart image: byte by byte */
            int h = sample_byte(m, a);
            for (; j <= last; j++) {
                int b = sample_byte(m, a + 2 + (j >> 1));
                if (h < 0 || b < 0) { c->dec = n + (j - n % 28); return -1; }
                audio_adpcm_sample((uint32_t)h, (uint32_t)((j & 1) ? b >> 4 : b), &c->h1, &c->h2);
            }
        }
        c->dec = n + (last + 1 - n % 28);
    }
    return 0;
}

/* Current sample of a playing channel as signed 16-bit; stops the channel and
 * returns 0 when the read falls outside RAM/ROM or past LEN. */
static int32_t channel_sample(const Mei *m, MeiAudioChannel *c) {
    uint64_t idx = c->pos >> 16;
    if (idx >= c->len) { c->playing = 0; return 0; }
    if (c->ctrl & AUD_CTRL_ADPCM) {
        if (adpcm_decode_to(m, c, idx)) { c->playing = 0; return 0; }
        return c->h1;
    }
    if (c->ctrl & AUD_CTRL_16BIT) {
        uint64_t a = c->addr + idx * 2;
        int lo = sample_byte(m, a), hi = sample_byte(m, a + 1);
        if (lo < 0 || hi < 0) { c->playing = 0; return 0; }
        return (int32_t)(lo | hi << 8) - ((hi & 0x80) ? 0x10000 : 0);
    }
    int b = sample_byte(m, (uint64_t)c->addr + idx);
    if (b < 0) { c->playing = 0; return 0; }
    return ((int32_t)b - ((b & 0x80) ? 0x100 : 0)) * 256;
}

static void channel_advance(MeiAudioChannel *c) {
    uint32_t step = c->pitch;
    if ((c->ctrl & AUD_CTRL_ADPCM) && step > AUD_ADPCM_MAX_PITCH) step = AUD_ADPCM_MAX_PITCH;
    c->pos += step;
    uint64_t len = (uint64_t)c->len << 16;
    if (c->pos < len) return;
    if ((c->ctrl & AUD_CTRL_LOOP) && c->loop < c->len) {
        uint64_t loop = (uint64_t)c->loop << 16;
        c->pos = loop + (c->pos - len) % (len - loop);
        c->dec = c->loop;   /* ADPCM resumes decoding at LOOP; the history carries on */
    } else {
        c->playing = 0;
    }
}

/* ------------------------------------------------------------------ mixer */

void audio_mix_tick(Mei *m) {
    /* 22,050 / 60 = 367.5: the remainder carries, so ticks alternate 367, 368. */
    m->audio_phase += MEI_AUDIO_RATE;
    int n = (int)(m->audio_phase / MEI_FPS);
    m->audio_phase -= (uint32_t)n * MEI_FPS;
    MeiReverb *rv = &m->rev;
    int reverb = rv->preset != 0 && !m->fault.kind;
    int32_t wet_l = (int32_t)(rv->vol & 0xFF), wet_r = (int32_t)((rv->vol >> 8) & 0xFF);

    for (int i = 0; i < n; i++) {
        int32_t l = 0, r = 0, sl = 0, sr = 0;
        for (int k = 0; k < AUD_CHANNELS; k++) {
            MeiAudioChannel *c = &m->ch[k];
            if (!c->playing) continue;
            int32_t s = channel_sample(m, c);
            if (!c->playing) continue;
            int32_t cl = asr8(s * (int32_t)(c->vol & 0xFF));
            int32_t cr = asr8(s * (int32_t)((c->vol >> 8) & 0xFF));
            l += cl;
            r += cr;
            if (c->ctrl & AUD_CTRL_REVERB) { sl += cl; sr += cr; }
            channel_advance(c);
        }
        if (reverb) {
            int32_t wl, wr;
            reverb_sample(rv, sl, sr, &wl, &wr);
            l += asr8(wl * wet_l);
            r += asr8(wr * wet_r);
        }
        m->audio_out[2 * i] = (int16_t)(l < -32768 ? -32768 : l > 32767 ? 32767 : l);
        m->audio_out[2 * i + 1] = (int16_t)(r < -32768 ? -32768 : r > 32767 ? 32767 : r);
    }
    m->audio_frames = n;
}
