#!/usr/bin/env python3
"""Generates the assets of the Sound Lab cart in carts/soundlab/ (the sounds in audio/):

  clip16.raw   a 2.4 s musical phrase, signed 16-bit at 22,050 Hz
  clip8.raw    the same clip as signed 8-bit
  clip.adp     the same clip as Mei ADPCM (tools/mei_adpcm.py)
  snap.adp     a short dry clap and pluck, for hearing the reverb presets
  pad.adp      a soft tone with a seamless loop (84-sample period), for the 16-channel chord
  assets.akr   embeds plus sizes, sample counts and measured SNRs (generated code)
"""
import math, os, sys
import numpy as np
from scipy import signal

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mei_adpcm as A

SR = 22050
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'carts', 'soundlab')
AUDIO = os.path.join(OUT, 'audio')
rng = np.random.default_rng(7)


def tt(n):
    return np.arange(n) / SR


def pluck(f, dur, bright=0.6):
    n = int(dur * SR)
    t = tt(n)
    x = np.zeros(n)
    for h in range(1, 12):
        if f * h > SR / 2 - 300:
            break
        x += (bright ** (h - 1)) / h * np.sin(2 * np.pi * f * h * t) * np.exp(-t * (3 + h * 2.2))
    return x * np.clip(t / 0.002, 0, 1)


def bell(f, dur):
    n = int(dur * SR)
    t = tt(n)
    idx = 2.2 * np.exp(-t / 0.2)
    return np.sin(2 * np.pi * f * t + idx * np.sin(2 * np.pi * f * 3.5 * t)) * np.exp(-t / 0.7) * np.clip(t / 0.003, 0, 1)


def kick(dur=0.3):
    n = int(dur * SR)
    t = tt(n)
    ph = 2 * np.pi * np.cumsum(48 + 110 * np.exp(-t / 0.025)) / SR
    return np.sin(ph) * np.exp(-t / 0.12)


def snare(dur=0.25):
    n = int(dur * SR)
    t = tt(n)
    b, a = signal.butter(2, [1200 / (SR / 2), 8000 / (SR / 2)], 'band')
    nz = signal.lfilter(b, a, rng.standard_normal(n)) * np.exp(-t / 0.06)
    return 0.8 * nz + 0.4 * np.sin(2 * np.pi * 190 * t) * np.exp(-t / 0.05)


def place(buf, x, t0, g=1.0):
    i0 = int(round(t0 * SR))
    n = min(len(x), len(buf) - i0)
    buf[i0:i0 + n] += g * x[:n]


def norm16(x, peak=0.9):
    return np.rint(x / np.abs(x).max() * peak * 32767).astype(np.int64)


def clip():
    """Eight eighth-notes at 100 BPM: a bell melody over plucked bass and a small kit."""
    n = int(2.4 * SR)
    x = np.zeros(n)
    step = 0.3
    mel = [659.3, 784.0, 880.0, 784.0, 659.3, 587.3, 523.3, 587.3]
    bass = [130.8, 130.8, 174.6, 174.6, 196.0, 196.0, 130.8, 130.8]
    for i in range(8):
        place(x, bell(mel[i], 1.2), i * step, 0.35)
        place(x, pluck(bass[i], 0.5, 0.5), i * step, 0.6)
        if i % 4 == 0:
            place(x, kick(), i * step, 0.8)
        if i % 4 == 2:
            place(x, snare(), i * step, 0.45)
        place(x, snare(0.05) * 0.4, i * step + step / 2, 0.3)
    fade = np.clip((n - np.arange(n)) / (0.15 * SR), 0, 1)
    return norm16(x * fade)


def snap():
    n = int(0.45 * SR)
    x = np.zeros(n)
    place(x, snare(0.2), 0.0, 0.9)
    place(x, pluck(392.0, 0.4, 0.7), 0.0, 0.7)
    place(x, pluck(587.3, 0.3, 0.7), 0.0, 0.4)
    return norm16(x)


def pad():
    """A soft tone at 22050 / 84 = 262.5 Hz (about C4): a 0.4 s attack, then 84 samples that
    repeat exactly. 84 = 3 blocks of 28, so the loop starts and ends on block boundaries."""
    period = 84
    attack = 28 * 315            # 0.4 s, a whole number of blocks
    n = attack + period
    t = np.arange(n)
    x = np.zeros(n)
    for h, g in ((1, 1.0), (2, 0.35), (3, 0.18), (4, 0.08), (5, 0.04)):
        x += g * np.sin(2 * np.pi * h * t / period + h * 0.7)
    x *= np.clip(t / (0.08 * SR), 0, 1)               # fade in; flat (periodic) at the loop
    x += 0.4 * np.sin(2 * np.pi * 3 * t / period) * np.exp(-t / (0.05 * SR))   # a brighter onset
    return norm16(x, 0.7), attack


def main():
    os.makedirs(AUDIO, exist_ok=True)
    c = clip()
    c8 = np.clip(np.rint(c / 256), -128, 127).astype(np.int8)
    cadp = A.encode(c)
    s = snap()
    sadp = A.encode(s)
    p, loop = pad()
    padp = A.encode(p, loop_start=loop)
    files = {'clip16.raw': c.astype('<i2').tobytes(), 'clip8.raw': c8.tobytes(), 'clip.adp': cadp,
             'snap.adp': sadp, 'pad.adp': padp}
    for name, data in files.items():
        with open(os.path.join(AUDIO, name), 'wb') as f:
            f.write(data)
    snr8 = A.snr(c, c8.astype(np.int64) * 256)
    snra = A.snr(c, A.decode(cadp, len(c)))
    assert len(padp) // 16 * 28 == len(p)
    akr = f"""// Generated by tools/gen_soundlab_assets.py: do not edit.
embed CLIP16: s16 = "audio/clip16.raw"
embed CLIP8: s8 = "audio/clip8.raw"
embed CLIP_ADPCM: u8 = "audio/clip.adp"
embed SNAP: u8 = "audio/snap.adp"
embed PAD: u8 = "audio/pad.adp"

const CLIP_SAMPLES = {len(c)}
const SNAP_SAMPLES = {len(s)}
const PAD_SAMPLES = {len(p)}
const PAD_LOOP = {loop}
const CLIP8_SNR = {round(snr8)}       // dB against the 16-bit clip
const CLIP_ADPCM_SNR = {round(snra)}
"""
    with open(os.path.join(OUT, 'assets.akr'), 'w') as f:
        f.write(akr)
    print(f"clip: {len(c)} samples; 16-bit {2 * len(c)} B, 8-bit {len(c)} B (SNR {snr8:.1f} dB), "
          f"ADPCM {len(cadp)} B (SNR {snra:.1f} dB)")
    print(f"snap {len(sadp)} B, pad {len(padp)} B (loop at {loop})")


if __name__ == '__main__':
    main()
