#!/usr/bin/env python3
"""Generates the data tables of the Mei standard library:
  stdlib/font_data.akr   - the 8x8 font (src/core/font8x8.h) pre-expanded to a 4-bit texture
  stdlib/sin_table.akr   - 1025-entry sine table over one full turn, 16.16 fixed point
Run from the repository root: python3 tools/gen_stdlib_data.py [output directory]
(the output directory defaults to stdlib/)"""
import math, re, os, sys

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(root, 'stdlib')

def write(name, text):
    with open(os.path.join(out_dir, name), 'w') as f:
        f.write(text)

# ---- font: 95 glyphs (ASCII 32..126), 16 per row -> 128 x 48 texels, 4-bit, 64 bytes per row
src = open(os.path.join(root, 'src/core/font8x8.h')).read()
glyphs = [[int(x, 16) for x in re.findall(r'0x([0-9A-Fa-f]{2})', m)]
          for m in re.findall(r'\{((?:\s*0x[0-9A-Fa-f]{2},?){8})\s*\}', src)]
assert len(glyphs) == 95, len(glyphs)
rows = []
for ty in range(48):
    row = bytearray(64)
    for tx in range(128):
        g = (ty // 8) * 16 + tx // 8
        bit = 0
        if g < 95:
            bit = (glyphs[g][ty % 8] >> (tx % 8)) & 1
        if bit:
            row[tx // 2] |= 1 << ((tx & 1) * 4)
    rows.append(row)
data = b''.join(rows)
words = [int.from_bytes(data[i:i + 4], 'little') for i in range(0, len(data), 4)]
lines = []
for i in range(0, len(words), 8):
    lines.append('    ' + ', '.join('0x%08X' % w for w in words[i:i + 8]) + ',')
write('font_data.akr',
      '// Generated by tools/gen_stdlib_data.py from src/core/font8x8.h - do not edit.\n'
      '// ASCII 32..126 as a 4-bit texture: 16 glyphs per row, 128 x 48 texels, 64 bytes per row.\n'
      'const __FONT_TEX: [%d]u32 = [\n%s\n]\n' % (len(words), '\n'.join(lines)))

# ---- sine table
vals = [round(math.sin(2 * math.pi * i / 1024) * 65536) for i in range(1025)]
lines = []
for i in range(0, len(vals), 12):
    lines.append('    ' + ', '.join(str(v) for v in vals[i:i + 12]) + ',')
write('sin_table.akr',
      '// Generated by tools/gen_stdlib_data.py - do not edit.\n'
      '// sin(2*pi*i/1024) as raw 16.16 values, i = 0..1024.\n'
      'const __SIN_TAB: [1025]s32 = [\n%s\n]\n' % '\n'.join(lines))
print('wrote stdlib/font_data.akr and stdlib/sin_table.akr')
