#!/usr/bin/env python3
"""Writes tests/adpcm_vectors.h: ADPCM reference vectors for tests/test_audio.c, made with
the independent Python decoder in tools/mei_adpcm.py and a Python model of an ADPCM
channel (pitch, loop, history), so the C core is checked against a second implementation.
Run: python3 tools/gen_adpcm_vectors.py"""
import os, sys
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mei_adpcm as A

MAX_PITCH = 0x100000


def all_headers_blocks():
    """256 blocks, header = 0..255 (every shift and filter, including the reserved ones),
    pseudo-random nibbles; the flags byte is non-zero to show it is ignored."""
    rng = np.random.default_rng(1234)
    out = bytearray()
    for h in range(256):
        out.append(h)
        out.append((h * 37 + 11) & 255)
        out += bytes(rng.integers(0, 256, 14, dtype=np.uint8))
    return bytes(out)


def channel_model(data, length, loop, pitch, looping, vol_l, vol_r, nout):
    """Python model of one ADPCM channel through the mixer (docs/DECISIONS.md)."""
    pos = dec = h1 = h2 = 0
    step = min(pitch, MAX_PITCH)
    playing = True
    L, R = [], []
    for _ in range(nout):
        s = 0
        if playing:
            idx = pos >> 16
            if idx >= length:
                playing = False
            else:
                while dec <= idx:
                    b = (dec // 28) * 16
                    j = dec % 28
                    byte = data[b + 2 + j // 2]
                    v = A.decode_sample(data[b], byte >> 4 if j & 1 else byte & 15, h1, h2)
                    h2, h1 = h1, v
                    dec += 1
                s = h1
                pos += step
                if pos >= length << 16:
                    if looping and loop < length:
                        pos = (loop << 16) + (pos - (length << 16)) % ((length - loop) << 16)
                        dec = loop
                    else:
                        playing = False
        L.append((s * vol_l) >> 8)
        R.append((s * vol_r) >> 8)
    return L, R


# (data: 0 = all-headers blocks, 1 = encoded music; channel, len, loop, pitch, looping,
#  vol_l, vol_r, output samples). The music blocks all predict (filters 2 and 4), so loops
#  into them depend on the history carried over the wrap.
SCENARIOS = [
    (0, 0, 7168, 0, 0x10000, 0, 255, 128, 1500),
    (1, 9, 1000, 300, 0x28000, 1, 255, 77, 2205),     # pitch 2.5, LOOP not a multiple of 28
    (1, 3, 400, 57, 0xC000, 1, 200, 255, 1470),       # pitch 0.75
    (0, 15, 7168, 1000, 0x140000, 1, 255, 1, 1102),   # pitch 20.0 runs at the 16.0 cap
    (1, 14, 2900, 100, 0x140000, 1, 255, 255, 1102),  # the same on real data
    (1, 8, 100, 99, 0x10000, 1, 128, 255, 735),       # one-sample loop: history keeps evolving
    (0, 12, 90, 0, 0x30000, 0, 255, 255, 367),        # pitch 3.0 off the end: stops
    (1, 6, 3000, 2990, 0x1C000, 1, 255, 255, 2205),   # short loop at the end, pitch 1.75
]


def carr(name, ctype, vals, per=16):
    lines = []
    vals = list(vals)
    for i in range(0, len(vals), per):
        lines.append('    ' + ', '.join(str(int(v)) for v in vals[i:i + per]) + ',')
    return f"static const {ctype} {name}[{len(vals)}] = {{\n" + '\n'.join(lines) + "\n};\n"


def main():
    blocks = all_headers_blocks()
    dec = A.decode(blocks)
    sig = A.test_signals(1.0)['music'][2000:5000]
    music = A.encode(sig)
    music_dec = A.decode(music, len(sig))
    out = ["/* Generated by tools/gen_adpcm_vectors.py from the Python reference decoder. */",
           "#define ADPCM_VEC_BLOCKS_N 256", f"#define ADPCM_VEC_MUSIC_N {len(sig)}", ""]
    out.append(carr('ADPCM_VEC_BLOCKS', 'uint8_t', blocks))
    out.append(carr('ADPCM_VEC_DECODED', 'int16_t', dec))
    out.append(carr('ADPCM_VEC_MUSIC', 'uint8_t', music))
    out.append(carr('ADPCM_VEC_MUSIC_DECODED', 'int16_t', music_dec))
    out.append("typedef struct { int music, ch; uint32_t len, loop, pitch; int looping, vol_l, vol_r, n; "
               "const int16_t *l, *r; } AdpcmScenario;\n")
    names = []
    for i, (mus, ch, ln, lp, pitch, looping, vl, vr, n) in enumerate(SCENARIOS):
        L, R = channel_model(music if mus else blocks, ln, lp, pitch, looping, vl, vr, n)
        out.append(carr(f'ADPCM_SC{i}_L', 'int16_t', L))
        out.append(carr(f'ADPCM_SC{i}_R', 'int16_t', R))
        names.append(f"    {{{mus}, {ch}, {ln}, {lp}, 0x{pitch:X}, {looping}, {vl}, {vr}, {n}, ADPCM_SC{i}_L, ADPCM_SC{i}_R}},")
    out.append("static const AdpcmScenario ADPCM_SCENARIOS[] = {\n" + '\n'.join(names) + "\n};\n")
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'tests', 'adpcm_vectors.h')
    open(path, 'w').write('\n'.join(out))
    print(f"wrote {os.path.normpath(path)}")


if __name__ == '__main__':
    main()
