#!/usr/bin/env python3
"""Generates stdlib/faces.akr: the hand-written face loop used by mesh().

For every face: the near-plane test, the guard-band test, back-face culling, ordering-table
depth, then a straight-line packet writer specialised for the packet layout (Gouraud x
textured x quad, with and without fog), reached through a jump table. A face with every
corner behind the near plane is dropped; one with only some of them behind it, or with a
vertex outside the guard band (where vproj would clamp it, or nearly), is handed to
__clip_face (clip.akr) before culling, since its screen positions cannot be trusted; the
pieces come back through __draw_faces.

Transformed vertices (__sv, 16 bytes each, written by __xform with vxp3):
  +0 1 when the vertex is inside the guard band (screen x and y in -1000..999), else 0
  +4 fog amount 0..1.0 (16.16, for clerp; unused when fog is off)
  +8 packed screen position (x & 0xFFFF) | (y << 16), as vxp3 leaves it
  +12 w (view depth, 16.16)
__draw_faces_sub is the same loop for carts that enabled subdivide(): front-facing,
on-screen textured faces near the camera whose depth spreads by more than the tolerance
are handed to __subdivide_face (subdiv.akr), which splits them and feeds the pieces back
through __draw_faces. The test is a superset of the per-edge test in __sub_split, so a face
it skips never has an edge its neighbour splits. A face crossing the near plane goes to
__clip_face_sub, which drops it if it cannot be seen and otherwise subdivides it (textured)
or clips it.

Run from the repository root: python3 tools/gen_faces_asm.py [output path]"""
import os, sys

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
P = ['r5', 'r6', 'r7', 'r8']     # vertex pointers
out = []
def e(s=''):
    out.append(s)

def variant(g, t, q, fog):
    n = 4 if q else 3
    stride = 4 * (1 + g + t)
    size = 4 + (n if g else 1) * 4 + n * 4 + (n * 4 if t else 0)
    label = '.v%d%d%d%d' % (g, t, q, fog)
    e('%s:   ; %s%s%s%s, %d bytes' % (label, 'gouraud ' if g else 'flat ', 'textured ' if t else '',
                                     'quad' if q else 'triangle', ' fog' if fog else '', size))
    e('    addi r11, r15, %d' % size)
    e('    sw   r11, [r0+{__arena_ptr}]')
    if fog:
        # colour source stride: 4 if the face itself is Gouraud, else 0 (all use col[0])
        e('    andi r13, r4, 1')
        e('    shli r13, r13, 2')
        e('    addi r10, r1, 12')
        e('    lw   r9, [r0+{%s}]' % ('__fogt_col' if t else '__fog_col'))
    for k in range(n):
        base = 8 + stride * k
        # colour
        if k == 0 or g:
            coff = base - 4
            if fog:
                e('    lw   r11, [r10]')
                e('    add  r10, r10, r13')
                e('    lw   r12, [%s+4]          ; fog amount' % P[k])
                e('    clerp r11, r9, r12        ; toward the fog colour')
            else:
                e('    lw   r11, [r1+%d]' % (12 + 4 * k))
            if k == 0:
                e('    shri r12, r4, 8           ; blend mode -> bits 24-25')
                e('    andi r12, r12, 3')
                e('    shli r12, r12, 24')
                e('    or   r11, r11, r12')
            e('    sw   r11, [r15+%d]' % coff)
        # position
        e('    lw   r11, [%s+8]' % P[k])
        e('    sw   r11, [r15+%d]' % base)
        # texture coordinate
        if t:
            e('    lhu  r11, [r1+%d]' % (28 + 2 * k))
            if k == 0:
                e('    shri r12, r4, 16          ; slot, depth and palette -> bits 16-31')
                e('    andi r12, r12, 0xFF1F')
                e('    shli r12, r12, 16')
                e('    or   r11, r11, r12')
            e('    sw   r11, [r15+%d]' % (base + 4))
    e('    jmp  .next')
    return label

e('// Generated by tools/gen_faces_asm.py - do not edit.')
e('// The face loops of mesh(): culling, depth sorting and packet building.')
e('')
e('var __fog_col: u32       // fog colour (untextured faces)')
e('var __fogt_col: u32      // half of it, for textured faces (their colour is a tint)')
e('var __ot_bias: s32')
e('')
HEAD_PLAIN = """    addi sp, sp, -32
    sw   r9, [sp+0]
    sw   r10, [sp+4]
    sw   r11, [sp+8]
    sw   r12, [sp+12]
    sw   r13, [sp+16]
    sw   ra, [sp+20]
    la   r3, {__sv}
    beq  r2, r0, .done
.face:
    lw   r4, [r1]               ; flags, blend, texture, palette
    lw   r9, [r0+{__cam_near}]
    lhu  r5, [r1+4]
    shli r5, r5, 4
    add  r5, r5, r3
    lw   r10, [r5+12]
    blt  r10, r9, .nb
    lhu  r6, [r1+6]
    shli r6, r6, 4
    add  r6, r6, r3
    lw   r11, [r6+12]
    blt  r11, r9, .near
    add  r10, r10, r11
    lhu  r7, [r1+8]
    shli r7, r7, 4
    add  r7, r7, r3
    lw   r11, [r7+12]
    blt  r11, r9, .near
    add  r10, r10, r11          ; w0 + w1 + w2"""

# The guard-band test for the first three corners, before culling (the fourth corner of a quad
# is tested in REST once its pointer is loaded; culling only looks at the first three). The
# marks are 1 inside the band, so their AND is 0 when a corner is outside.
GUARD = """    lw   r11, [r5]
    lw   r12, [r6]
    and  r11, r11, r12
    lw   r12, [r7]
    and  r11, r11, r12
    beq  r11, r0, %s         ; a corner outside the guard band"""
GUARD_PLAIN = GUARD % '.clip'
GUARD4 = """    lw   r12, [r8]
    beq  r12, r0, .clip         ; the fourth corner is outside the guard band
"""
# with subdivide(): a face to be split goes to __subdivide_face (unculled) and its pieces
# are clipped as they are drawn; any other face is clipped
GUARD_SUB = GUARD % '.gb'
GB_SUB = """.gb:
    lw   r11, [sp+24]
    bne  r11, r0, .sub
    jmp  .clip"""


def OUTCODE(k):
    """ANDs into r11 the screen outcode of corner k (left 1, right 2, above 4, below 8)."""
    return """    lhu  r5, [r1+%d]
    shli r5, r5, 4
    add  r5, r5, r3
    lw   r5, [r5+8]
    shli r6, r5, 16
    sari r6, r6, 16             ; x
    sari r5, r5, 16             ; y
    slt  r7, r6, r0
    slti r8, r6, 320
    xori r8, r8, 1
    shli r8, r8, 1
    or   r7, r7, r8
    slt  r8, r5, r0
    shli r8, r8, 2
    or   r7, r7, r8
    slti r8, r5, 240
    xori r8, r8, 1
    shli r8, r8, 3
    or   r7, r7, r8
    and  r11, r11, r7""" % (4 + 2 * k)


def OUTCODE_W(k):
    """ANDs into r11 the side of the view that corner k is beyond (as OUTCODE), for a corner
    that may be behind the camera: there x > w (right of the view, in clip space) means
    screen x < 320 and so on (the projection is mirrored through the centre, and vproj's
    clamping keeps the side), so the bits flip."""
    return OUTCODE(k).replace("""    lw   r5, [r5+8]""", """    lw   r12, [r5+12]           ; w
    lw   r5, [r5+8]""").replace("""    and  r11, r11, r7""", """    bge  r12, r0, .ow%d
    xori r7, r7, 15             ; behind the camera
.ow%d:
    and  r11, r11, r7""" % (k, k))


def NEAR(slot, sub):
    """Faces crossing the near plane (r9 = near, r3 = __sv). The plain loops come to .nb when
    corner 0 is behind the plane (the face is dropped if every corner is) and to .near when
    a later corner is; the subdividing loop's head comes to .nearsub. A face wholly beyond
    one side of the view is dropped here; any other is clipped (or, with subdivide(),
    split first)."""
    out = []
    if not sub:
        out.append(""".nb:
    ; corner 0 is behind the near plane: clip the face, unless they all are""")
        for k in range(1, 3):
            out.append("""    lhu  r5, [r1+%d]
    shli r5, r5, 4
    add  r5, r5, r3
    lw   r11, [r5+12]
    bge  r11, r9, .near""" % (4 + 2 * k))
        out.append("""    andi r11, r4, 4
    beq  r11, r0, .next
    lhu  r5, [r1+10]
    shli r5, r5, 4
    add  r5, r5, r3
    lw   r11, [r5+12]
    blt  r11, r9, .next""")
    out.append('%s:\n    addi r11, r0, 15' % ('.nearsub' if sub else '.near'))
    out += [OUTCODE_W(k) for k in range(3)]
    out.append("""    andi r12, r4, 4
    beq  r12, r0, .near3""")
    out.append(OUTCODE_W(3))
    out.append(""".near3:
    bne  r11, r0, .next         ; wholly beyond one side of the view
    sw   r1, [sp+%d]
    sw   r2, [sp+%d]
    call {%s}     ; r1 = the face
    lw   r1, [sp+%d]
    lw   r2, [sp+%d]
    la   r3, {__sv}
    jmp  .next""" % (slot, slot + 4, '__clip_face_sub' if sub else '__clip_face', slot, slot + 4))
    return '\n'.join(out)


# A face with a corner outside the guard band: drop it if it lies wholly off one side of the
# screen (vproj's clamping keeps every vertex on its side), else hand it to __clip_face.
CLIP_OFFSCREEN = """.clip:
    addi r11, r0, 15
""" + OUTCODE(0) + "\n" + OUTCODE(1) + "\n" + OUTCODE(2) + """
    andi r12, r4, 4
    beq  r12, r0, .clip3
""" + OUTCODE(3) + """
.clip3:
    bne  r11, r0, .next         ; off the screen"""


def BBOX(reg, k):
    """Grows the bounding box at [sp+36..48] by the vertex at reg."""
    return """    lw   r11, [{r}+8]
    shli r15, r11, 16
    sari r15, r15, 16
    sari r11, r11, 16
    lw   r3, [sp+36]
    bge  r15, r3, .bx{k}a
    sw   r15, [sp+36]
.bx{k}a:
    lw   r3, [sp+40]
    bge  r3, r15, .bx{k}b
    sw   r15, [sp+40]
.bx{k}b:
    lw   r3, [sp+44]
    bge  r11, r3, .by{k}a
    sw   r11, [sp+44]
.by{k}a:
    lw   r3, [sp+48]
    bge  r3, r11, .bb{k}
    sw   r11, [sp+48]
.bb{k}:
""".format(r=reg, k=k)


# The subdividing loop: track the nearest and farthest w instead of rejecting at once.
# Frame: [sp+24] candidate flag, [sp+28]/[sp+32] r1/r2 across the call, [sp+36..48]
# screen bounding box (min x, max x, min y, max y).
HEAD_SUB = """    addi sp, sp, -56
    sw   r9, [sp+0]
    sw   r10, [sp+4]
    sw   r11, [sp+8]
    sw   r12, [sp+12]
    sw   r13, [sp+16]
    sw   ra, [sp+20]
    la   r3, {__sv}
    beq  r2, r0, .done
.face:
    lw   r4, [r1]               ; flags, blend, texture, palette
    lw   r9, [r0+{__cam_near}]
    lhu  r5, [r1+4]
    shli r5, r5, 4
    add  r5, r5, r3
    lw   r10, [r5+12]
    mov  r12, r10               ; nearest w
    mov  r13, r10               ; farthest w
    lhu  r6, [r1+6]
    shli r6, r6, 4
    add  r6, r6, r3
    lw   r11, [r6+12]
    add  r10, r10, r11
    bge  r11, r12, .n1
    mov  r12, r11
.n1:
    bge  r13, r11, .f1
    mov  r13, r11
.f1:
    lhu  r7, [r1+8]
    shli r7, r7, 4
    add  r7, r7, r3
    lw   r11, [r7+12]
    add  r10, r10, r11          ; w0 + w1 + w2
    bge  r11, r12, .n2
    mov  r12, r11
.n2:
    bge  r13, r11, .f2
    mov  r13, r11
.f2:
    andi r11, r4, 4
    beq  r11, r0, .mm
    lhu  r8, [r1+10]
    shli r8, r8, 4
    add  r8, r8, r3
    lw   r11, [r8+12]
    bge  r11, r12, .n3
    mov  r12, r11
.n3:
    bge  r13, r11, .mm
    mov  r13, r11
.mm:
    blt  r13, r9, .next         ; wholly behind the near plane
    blt  r12, r9, .nearsub      ; crosses it
    andi r11, r4, 2
    beq  r11, r0, .plain        ; untextured faces are never split
    lw   r11, [r0+{__sub_dist}]
    bge  r12, r11, .nosub       ; nearest vertex beyond the subdivision distance
    lw   r11, [r0+{__sub_q}]
    fmul r11, r12, r11
    add  r11, r11, r12
    bge  r11, r13, .nosub       ; depth spread within the tolerance: no edge can split
    ; screen bounding box
    addi r11, r0, 32767
    sw   r11, [sp+36]
    sw   r11, [sp+44]
    addi r11, r0, -32768
    sw   r11, [sp+40]
    sw   r11, [sp+48]
""" + BBOX('r5', 0) + BBOX('r6', 1) + BBOX('r7', 2) + """    andi r11, r4, 4
    beq  r11, r0, .bbq
""" + BBOX('r8', 3) + """.bbq:
    la   r3, {__sv}
    lw   r11, [sp+40]
    blt  r11, r0, .next         ; all left of the screen
    lw   r11, [sp+36]
    slti r11, r11, 321
    beq  r11, r0, .next         ; all right of it
    lw   r11, [sp+48]
    blt  r11, r0, .next         ; all above
    lw   r11, [sp+44]
    slti r11, r11, 241
    beq  r11, r0, .next         ; all below
    addi r11, r0, 1             ; a candidate (if front-facing)
    sw   r11, [sp+24]
    jmp  .cull
.nosub:
    sw   r0, [sp+24]
    jmp  .cull
.plain:
    sw   r0, [sp+24]
.cull:"""

CULL = """    ; back faces: nclip >= 0 (front faces are counter-clockwise on screen). The positions
    ; are exact here: a corner outside the guard band went to .clip first.
    lw   r12, [r5+8]
    lw   r11, [r6+8]
    lw   r13, [r7+8]
    nclip r12, r11, r13
    blt  r12, r0, .front
    andi r11, r4, 16            ; double-sided
    beq  r11, r0, .next
.front:"""

SUB_GO = """    lw   r11, [sp+24]
    bne  r11, r0, .sub"""

REST = """    andi r11, r4, 4
    bne  r11, r0, .quad
    add  r11, r9, r9
    add  r11, r11, r9
    sub  r12, r10, r11          ; w0 + w1 + w2 - 3 near
    lw   r11, [r0+{__ot_k3}]
    jmp  .depth
.quad:
    lhu  r8, [r1+10]
    shli r8, r8, 4
    add  r8, r8, r3
    lw   r11, [r8+12]
    blt  r11, r9, .near
@GUARD4@    add  r10, r10, r11
    shli r11, r9, 2
    sub  r12, r10, r11          ; w0 + w1 + w2 + w3 - 4 near
    lw   r11, [r0+{__ot_k4}]
.depth:
    lw   r10, [r0+{__ot_bias}]
    otz  r10, r12, r11          ; ordering-table bucket
    lw   r15, [r0+{__arena_ptr}]
    lw   r11, [r0+{__arena_end}]
    addi r12, r15, 52
    bltu r11, r12, .done        ; packet memory full
    lbu  r12, [r0+{__fog_on}]
    andi r9, r4, 15
    or   r9, r9, r12            ; fog makes every face Gouraud
    ; header and ordering-table insertion
    la   r11, {__ot}
    shli r10, r10, 2
    add  r11, r11, r10
    lw   r10, [r11]
    ori  r13, r9, 0x20
    shli r13, r13, 24
    or   r10, r10, r13
    sw   r10, [r15]
    sw   r15, [r11]
    ; dispatch on Gouraud/textured/quad (+ fog)
    andi r9, r9, 7
    shli r12, r12, 3
    or   r9, r9, r12
    shli r9, r9, 2
    la   r11, .table
    add  r11, r11, r9
    lw   r11, [r11]
    jr   r11"""

SUB_CALL = """.sub:
    sw   r1, [sp+28]
    sw   r2, [sp+32]
    call {__subdivide_face}     ; r1 = the face
    lw   r1, [sp+28]
    lw   r2, [sp+32]
    la   r3, {__sv}"""


def face_loop(name, sub, guard=True):
    """guard: test the guard-band marks (a loop without the test serves meshes that __xform
    found wholly inside the band; it still clips faces crossing the near plane)."""
    e('asm fn %s(first: *Face, nf: s32) {' % name)
    if sub:
        e(HEAD_SUB)
        e(GUARD_SUB)
        e(CULL)
        e(SUB_GO)
    else:
        e(HEAD_PLAIN)
        if guard:
            e(GUARD_PLAIN)
        e(CULL)
    # (the subdividing loop has checked every corner against the near plane already)
    e(REST.replace('@GUARD4@', GUARD4 if guard else '').replace('.near', '.next' if sub else '.near'))
    labels = {}
    for fog in (0, 1):
        for q in (0, 1):
            for t in (0, 1):
                for g in (0, 1):
                    if fog and not g:
                        continue
                    labels[(g, t, q, fog)] = variant(g, t, q, fog)
    if sub:
        e(GB_SUB)
        e(SUB_CALL)
        e('    jmp  .next')
    slot = 28 if sub else 24
    e(NEAR(slot, sub))
    if guard:
        e(CLIP_OFFSCREEN)
        e("""    sw   r1, [sp+%d]
    sw   r2, [sp+%d]
    call {__clip_face}          ; r1 = the face
    lw   r1, [sp+%d]
    lw   r2, [sp+%d]
    la   r3, {__sv}""" % (slot, slot + 4, slot, slot + 4))
    frame = 56 if sub else 32
    e(""".next:
    addi r1, r1, 36
    addi r2, r2, -1
    bne  r2, r0, .face
.done:
    lw   r9, [sp+0]
    lw   r10, [sp+4]
    lw   r11, [sp+8]
    lw   r12, [sp+12]
    lw   r13, [sp+16]
    lw   ra, [sp+20]
    addi sp, sp, %d
    ret
    .align 4
.table:""" % frame)
    for fog in (0, 1):
        for idx in range(8):
            g, t, q = idx & 1, (idx >> 1) & 1, (idx >> 2) & 1
            key = (g if not fog else 1, t, q, fog)
            e('    .word %s' % labels[key])
    e('}')


# ---- the subdivision worklist (__sub_run), used by subdiv.akr
#
# A patch is a quad (a b c d in strip order) or a triangle (a b c, d = -1) of scratch
# vertices plus g, four 4-bit edge generations (quad: bottom a-b, right b-d, top d-c, left
# c-a; triangle: a-b, b-c, c-a) and, in bits 16-19, the patch's depth (the generation
# given to a quad's diagonal when it continues as two triangles). An edge's generation
# counts how often the mesh edge was halved to make it; 15 marks an edge already found not
# to need splitting. Both faces of
# a shared edge see the same generation and the same test, so they split it alike.
# Patches wait on __sub_stack (5 words each). Frame slots:
SUB_FRAME = 108
SL = {'top': 24, 'a': 28, 'b': 32, 'c': 36, 'd': 40, 'g': 44,
      'G0': 48, 'G1': 52, 'G2': 56, 'G3': 60, 'W0': 64, 'W1': 68, 'W2': 72, 'W3': 76,
      'm0': 80, 'm1': 84, 'm2': 88, 'X': 92, 'G4': 96, 'W4': 100}
_lab = [0]


def lab(p):
    _lab[0] += 1
    return '.%s%d' % (p, _lab[0])


def ld(reg, spec):
    if isinstance(spec, int):
        return '    addi %s, r0, %d' % (reg, spec)
    return '    lw   %s, [sp+%d]' % (reg, SL[spec])


def gen_word(reg, specs):
    """Packs generations: each spec is ('G', k, inc), ('X', inc) or ('C', value)."""
    out = ['    mov  %s, r0' % reg]
    for i, sp_ in enumerate(specs):
        if sp_[0] == 'C':
            if sp_[1]:
                out.append('    ori  %s, %s, %d' % (reg, reg, sp_[1] << (4 * i)))
            continue
        src = 'G%d' % sp_[1] if sp_[0] == 'G' else 'X'
        inc = sp_[2] if sp_[0] == 'G' else sp_[1]
        out.append(ld('r8', src))
        if inc:
            out.append('    addi r8, r8, %d' % inc)
        if i:
            out.append('    shli r8, r8, %d' % (4 * i))
        out.append('    or   %s, %s, r8' % (reg, reg))
    return '\n'.join(out)


def push(verts, gens):
    out = [ld('r%d' % (i + 1), v) for i, v in enumerate(verts)]
    out.append(gen_word('r5', gens))
    out.append('    lw   r6, [sp+%d]' % SL['top'])
    for i in range(5):
        out.append('    sw   r%d, [r6+%d]' % (i + 1, 4 * i))
    out.append('    addi r6, r6, 20')
    out.append('    sw   r6, [sp+%d]' % SL['top'])
    return '\n'.join(out)


def test(x, y, k):
    """W_k = should edge x-y (generation G_k) split? A 'no' marks G_k as 15."""
    no, yes, done = lab('no'), lab('yes'), lab('dn')
    return '\n'.join([
        '    lw   r6, [sp+%d]' % SL['G%d' % k],
        '    lw   r7, [r0+{__subdiv}]',
        '    bge  r6, r7, %s' % no,
        ld('r1', x), ld('r2', y),
        '    call {__sub_split}',
        '    beq  r1, r0, %s' % no,
        '    addi r7, r0, 2',
        '    bne  r1, r7, %s' % yes,
        '    lw   r6, [sp+%d]' % SL['G%d' % k],
        '    beq  r6, r0, %s         ; crossing the near plane: only halved once' % yes,
        '%s:' % no,
        '    addi r6, r0, 15',
        '    sw   r6, [sp+%d]' % SL['G%d' % k],
        '    sw   r0, [sp+%d]' % SL['W%d' % k],
        '    jmp  %s' % done,
        '%s:' % yes,
        '    addi r6, r0, 1',
        '    sw   r6, [sp+%d]' % SL['W%d' % k],
        '%s:' % done])


def mid(x, y, slot):
    return '\n'.join([ld('r1', x), ld('r2', y), '    call {__sub_mid}',
                      '    sw   r1, [sp+%d]' % SL[slot]])


def both(k1, k2, target_if_not):
    """Branches to target_if_not unless W_k1 and W_k2."""
    return '\n'.join(['    lw   r5, [sp+%d]' % SL['W%d' % k1], '    lw   r6, [sp+%d]' % SL['W%d' % k2],
                      '    and  r5, r5, r6', '    beq  r5, r0, %s' % target_if_not])


def subdiv_run():
    e('')
    e('// The subdivision worklist of subdiv.akr: splits a face held in scratch vertices until')
    e('// no edge needs splitting, queueing the pieces with __sub_emit (see gen_faces_asm.py).')
    e('var __sub_stack: [320]u32')
    e('')
    e('asm fn __sub_run(n: s32) {')
    e('    addi sp, sp, -%d' % SUB_FRAME)
    e('    sw   ra, [sp+20]')
    e('    la   r5, {__sub_stack}')
    e('    sw   r5, [sp+%d]' % SL['top'])
    e('    sw   r0, [sp+%d]' % SL['a'])
    e('    addi r5, r0, 1')
    e('    sw   r5, [sp+%d]' % SL['b'])
    e('    addi r5, r0, 2')
    e('    sw   r5, [sp+%d]' % SL['c'])
    e('    addi r5, r0, -1')
    e('    addi r6, r0, 4')
    e('    bne  {n}, r6, .tri0')
    e('    addi r5, r0, 3')
    e('.tri0:')
    e('    sw   r5, [sp+%d]' % SL['d'])
    e('    sw   r0, [sp+%d]' % SL['g'])
    e('    jmp  .process')
    e('.pop:')
    e('    lw   r5, [sp+%d]' % SL['top'])
    e('    la   r6, {__sub_stack}')
    e('    beq  r5, r6, .end')
    e('    addi r5, r5, -20')
    e('    sw   r5, [sp+%d]' % SL['top'])
    for i, f in enumerate('abcdg'):
        e('    lw   r6, [r5+%d]' % (4 * i))
        e('    sw   r6, [sp+%d]' % SL[f])
    e('.process:')
    e('    lw   r5, [r0+{__sub_n}]')
    e('    slti r5, r5, 122            ; scratch nearly full: draw the patch as it is')
    e('    beq  r5, r0, .emit')
    e('    lw   r5, [sp+%d]' % SL['top'])
    e('    la   r6, {__sub_stack}')
    e('    addi r6, r6, 1200')
    e('    bge  r5, r6, .emit          ; worklist nearly full')
    e('    lw   r5, [sp+%d]' % SL['g'])
    for k in range(5):
        e('    shri r6, r5, %d' % (4 * k))
        e('    andi r6, r6, 15')
        e('    sw   r6, [sp+%d]' % SL['G%d' % k])
    e('    lw   r5, [sp+%d]' % SL['d'])
    e('    blt  r5, r0, .tri')
    e('    ; ---- quad: if the bottom and top both split, cut into left and right halves')
    e(test('a', 'b', 0))
    e(test('d', 'c', 2))
    e(both(0, 2, '.q2'))
    e(mid('a', 'b', 'm0'))
    e(mid('d', 'c', 'm1'))
    e(push(['m0', 'b', 'm1', 'd'], [('G', 0, 1), ('G', 1, 0), ('G', 2, 1), ('G', 0, 1), ('G', 4, 1)]))
    e(push(['a', 'm0', 'c', 'm1'], [('G', 0, 1), ('G', 0, 1), ('G', 2, 1), ('G', 3, 0), ('G', 4, 1)]))
    e('    jmp  .pop')
    e('.q2:')
    e('    ; if the right and left both split, cut into bottom and top halves')
    e(test('b', 'd', 1))
    e(test('c', 'a', 3))
    e(both(1, 3, '.q3'))
    e(mid('b', 'd', 'm0'))
    e(mid('c', 'a', 'm1'))
    e(push(['m1', 'm0', 'c', 'd'], [('G', 1, 1), ('G', 1, 1), ('G', 2, 0), ('G', 3, 1), ('G', 4, 1)]))
    e(push(['a', 'b', 'm1', 'm0'], [('G', 0, 0), ('G', 1, 1), ('G', 1, 1), ('G', 3, 1), ('G', 4, 1)]))
    e('    jmp  .pop')
    e('.q3:')
    e('    ; no edge to split: draw it. Otherwise go on with its two triangles (a b c) and')
    e('    ; (b d c), as the GPU draws it. (Quads are only ever cut into quads or into their')
    e('    ; own two triangles: fanning around a new inner point would bend texture lines')
    e('    ; that run parallel to the edges, such as bricks and floor tiles.)')
    e('    lw   r5, [sp+%d]' % SL['W0'])
    for k in (1, 2, 3):
        e('    lw   r6, [sp+%d]' % SL['W%d' % k])
        e('    or   r5, r5, r6')
    e('    beq  r5, r0, .emit')
    e(push(['b', 'd', 'c', -1], [('G', 1, 0), ('G', 2, 0), ('G', 4, 0), ('C', 0)]))
    e(push(['a', 'b', 'c', -1], [('G', 0, 0), ('G', 4, 0), ('G', 3, 0), ('C', 0)]))
    e('    jmp  .pop')
    e('    ; ---- triangle a b c: split into four if all edges split, else bisect one edge')
    e('.tri:')
    e(test('a', 'b', 0))
    e(test('b', 'c', 1))
    e(test('c', 'a', 2))
    e(both(0, 1, '.t1'))
    e('    lw   r5, [sp+%d]' % SL['W2'])
    e('    beq  r5, r0, .t1')
    e(mid('a', 'b', 'm0'))
    e(mid('b', 'c', 'm1'))
    e(mid('c', 'a', 'm2'))
    e('    lw   r5, [sp+%d]' % SL['G0'])
    e('    lw   r6, [sp+%d]' % SL['G1'])
    e('    bge  r5, r6, .tx1')
    e('    mov  r5, r6')
    e('.tx1:')
    e('    lw   r6, [sp+%d]' % SL['G2'])
    e('    bge  r5, r6, .tx2')
    e('    mov  r5, r6')
    e('.tx2:')
    e('    addi r5, r5, 1')
    e('    sw   r5, [sp+%d]' % SL['X'])
    e(push(['a', 'm0', 'm2', -1], [('G', 0, 1), ('X', 0), ('G', 2, 1), ('C', 0)]))
    e(push(['m0', 'b', 'm1', -1], [('G', 0, 1), ('G', 1, 1), ('X', 0), ('C', 0)]))
    e(push(['m2', 'm1', 'c', -1], [('X', 0), ('G', 1, 1), ('G', 2, 1), ('C', 0)]))
    e(push(['m0', 'm1', 'm2', -1], [('X', 0), ('X', 0), ('X', 0), ('C', 0)]))
    e('    jmp  .pop')
    e('.t1:')
    e('    lw   r5, [sp+%d]' % SL['W0'])
    e('    beq  r5, r0, .t2')
    e(mid('a', 'b', 'm0'))
    e(push(['a', 'm0', 'c', -1], [('G', 0, 1), ('G', 0, 1), ('G', 2, 0), ('C', 0)]))
    e(push(['m0', 'b', 'c', -1], [('G', 0, 1), ('G', 1, 0), ('G', 0, 1), ('C', 0)]))
    e('    jmp  .pop')
    e('.t2:')
    e('    lw   r5, [sp+%d]' % SL['W1'])
    e('    beq  r5, r0, .t3')
    e(mid('b', 'c', 'm0'))
    e(push(['a', 'b', 'm0', -1], [('G', 0, 0), ('G', 1, 1), ('G', 1, 1), ('C', 0)]))
    e(push(['a', 'm0', 'c', -1], [('G', 1, 1), ('G', 1, 1), ('G', 2, 0), ('C', 0)]))
    e('    jmp  .pop')
    e('.t3:')
    e('    lw   r5, [sp+%d]' % SL['W2'])
    e('    beq  r5, r0, .emit')
    e(mid('c', 'a', 'm0'))
    e(push(['a', 'b', 'm0', -1], [('G', 0, 0), ('G', 2, 1), ('G', 2, 1), ('C', 0)]))
    e(push(['m0', 'b', 'c', -1], [('G', 2, 1), ('G', 1, 0), ('G', 2, 1), ('C', 0)]))
    e('    jmp  .pop')
    e('.emit:')
    for i, f in enumerate('abcd'):
        e(ld('r%d' % (i + 1), f))
    e('    call {__sub_emit}')
    e('    jmp  .pop')
    e('.end:')
    e('    lw   ra, [sp+20]')
    e('    addi sp, sp, %d' % SUB_FRAME)
    e('}')


face_loop('__draw_faces', False)
e('')
e('// The same loop without the guard-band test, for meshes wholly inside the band.')
face_loop('__draw_faces_in', False, guard=False)
e('')
e('// The same loop for carts that called subdivide(): see the header of gen_faces_asm.py.')
face_loop('__draw_faces_sub', True)
subdiv_run()
dst = sys.argv[1] if len(sys.argv) > 1 else os.path.join(root, 'stdlib', 'faces.akr')
with open(dst, 'w') as f:
    f.write('\n'.join(l for l in out if l is not None) + '\n')
print('wrote', dst)
