#!/usr/bin/env python3
"""Computes the reverb preset table in src/core/audio.c and rewrites it in place
(between the BEGIN/END generated markers). Run: python3 tools/gen_reverb_tables.py

Presets 1-4 are an 8-line feedback delay network (FDN) with a Hadamard mixing matrix.
Each line's gain and one-pole damping filter follow Jot's absorbent-filter design: a line of
m samples gets gain g = 10^(-3 m / (RT60 fs)) and the filter pole
b = ln(10)/4 * log10(g) * (1 - 1/hf^2), where hf = RT60(Nyquist) / RT60(DC). The gain stored
in the table includes the matrix's 1/sqrt(8). Preset 5 is a ping-pong echo.

`out` was calibrated by measurement (scratch harness): white noise sent at full volume
returns at -3 dB with REV_VOL at 256/256. Measured mid-band (500 Hz-1 kHz) decay times:
room 0.63 s, studio 1.2 s, hall 2.4 s, space 6.3 s; echo repeats every 250 ms at -4.4 dB.
Everything is rounded to integers here, so the console itself never touches floating point.
"""
import math, os, re

SR = 22050
NAMES = ['room', 'studio', 'hall', 'space', 'echo']
PRESETS = {
    # predelay ms, diffuser allpass delays and coefficient, line delays, RT60 at DC, hf ratio
    'room':   dict(pre=4,  ap=[71, 113, 163, 229],  apg=0.7, lines=[419, 461, 523, 587, 659, 727, 811, 887],
                   rt60=0.65, hf=0.45, out=0.2079),
    'studio': dict(pre=8,  ap=[97, 131, 193, 277],  apg=0.7, lines=[557, 613, 701, 787, 881, 977, 1087, 1201],
                   rt60=1.2, hf=0.6, out=0.1745),
    'hall':   dict(pre=20, ap=[142, 107, 379, 277], apg=0.7, lines=[1153, 1327, 1559, 1801, 2087, 2311, 2633, 2903],
                   rt60=2.6, hf=0.4, out=0.2022),
    'space':  dict(pre=45, ap=[173, 233, 409, 557], apg=0.7, lines=[1559, 1801, 2087, 2311, 2633, 2903, 3229, 3571],
                   rt60=6.5, hf=0.5, out=0.1492),
    'echo':   dict(echo=1, delay=5512, feedback=0.6, damp=0.6, out=0.9188),
}
POOL = 24576   # REV_POOL in machine.h


def q15(x):
    return int(round(x * 32768))


def row(p):
    if p.get('echo'):
        d = p['delay']
        return dict(pre=1, ap=[0] * 4, apg=0, lens=[d, d] + [0] * 6, damp=[q15(p['damp'])] * 2 + [0] * 6,
                    gain=[q15(p['feedback'])] * 2 + [0] * 6, out=q15(p['out']), echo=1,
                    note=f"ping-pong, {d} samples per side, feedback {p['feedback']}")
    damp, gain = [], []
    for m in p['lines']:
        g = 10 ** (-3 * m / (p['rt60'] * SR))
        b = math.log(10) / 4 * math.log10(g) * (1 - 1 / p['hf'] ** 2)
        damp.append(q15(1 - b))
        gain.append(q15(g / math.sqrt(8)))
    return dict(pre=max(1, round(p['pre'] * SR / 1000)), ap=p['ap'], apg=q15(p['apg']), lens=p['lines'],
                damp=damp, gain=gain, out=q15(p['out']), echo=0,
                note=f"RT60 {p['rt60']} s at DC, HF ratio {p['hf']}, predelay {p['pre']} ms")


def table():
    out = ["static REV_TABLE_CONST RevPreset rev_presets[6] = {", "    {0},"]
    for i, n in enumerate(NAMES, 1):
        r = row(PRESETS[n])
        size = r['pre'] + sum(r['ap']) + sum(r['lens'])
        assert size <= POOL, (n, size)
        j = lambda v: ', '.join(str(x) for x in v)
        out.append(f"    /* {i} {n}: {r['note']} */")
        out.append(f"    {{{r['pre']}, {{{j(r['ap'])}}}, {r['apg']}, {{{j(r['lens'])}}},")
        out.append(f"     {{{j(r['damp'])}}},")
        out.append(f"     {{{j(r['gain'])}}}, {r['out']}, {r['echo']}}},")
    out.append("};")
    return '\n'.join(out)


if __name__ == '__main__':
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'core', 'audio.c')
    src = open(path).read()
    new = re.sub(r"(/\* BEGIN generated by tools/gen_reverb_tables.py \*/\n).*?(\n/\* END generated \*/)",
                 lambda m: m.group(1) + table() + m.group(2), src, flags=re.S)
    if new != src:
        open(path, 'w').write(new)
    print(table())
