#!/usr/bin/env python3
"""Generates the assets of the "Lantern Lake" cart in carts/lantern/.

Graphics (this file):
  tex0.bin   4-bit world atlas (texture slot 0): terrain, wood, walls, foliage, water, glows
  tex1.bin   4-bit atlas (slot 1): fish (one texture per species, palette-swapped day/night),
             icons, the lake map
  tex2.bin   4-bit atlas (slot 2): the two fonts and the title logo
  keypal.bin time-of-day keyframes of the world palettes (4 keys x NSRC sources x 16 colours)
  statpal.bin static 4-bit palettes (glows, fish, icons, map, fonts, logo) from palette 48
  *.bin      meshes: terrain chunks, docks, village and their mirror images (for the
             reflections under the water), the bobber, the fish (3D) and their shadows
  assets.akr generated declarations: embeds, palette numbers, atlas coordinates, dock
             placements, culling tables, lantern positions, font metrics

Audio is generated by tools/gen_lantern_audio.py (run from here when present).

Time of day: every world material has four palette keyframes (night, dawn, day, dusk). The
cart blends two keys into the live palettes, so lighting changes cost no per-vertex work.
Each material also exists as a darker, bluer "reflection" palette used by the mirrored
geometry drawn under the translucent water. Windows and lanterns are emissive palette
entries that light up at night."""
import math, os, struct, subprocess, sys
import numpy as np
from PIL import Image, ImageDraw, ImageFont, ImageFilter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from meshlib import Mesh, DOUBLE, SEMI

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'carts', 'lantern')
os.makedirs(OUT, exist_ok=True)
rng = np.random.default_rng(77)
# --review DIR: also write atlas / palette previews (PNG) there; --no-audio: skip the audio
DEBUG_PNG = sys.argv[sys.argv.index('--review') + 1] if '--review' in sys.argv else None


def write(name, data):
    with open(os.path.join(OUT, name), 'wb') as f:
        f.write(data)


def c15(c):
    r, g, b = (int(max(0, min(255, round(v)))) for v in c)
    return (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)


def rgbw(r, g, b):
    r, g, b = (int(max(0, min(255, round(v)))) for v in (r, g, b))
    return r | (g << 8) | (b << 16)


def lerp3(a, b, t):
    return tuple(a[i] + (b[i] - a[i]) * t for i in range(3))


def ramp(stops, n=15):
    out = []
    for i in range(n):
        t = i / (n - 1) * (len(stops) - 1)
        k = min(int(t), len(stops) - 2)
        out.append(lerp3(stops[k], stops[k + 1], t - k))
    return out


# ----------------------------------------------------------------------------- noise

def value_noise(w, h, cx, cy, seed):
    r = np.random.default_rng(seed)
    lat = r.random((cy + 1, cx + 1))
    lat[-1, :] = lat[0, :]
    lat[:, -1] = lat[:, 0]
    ys = np.linspace(0, cy, h, endpoint=False)
    xs = np.linspace(0, cx, w, endpoint=False)
    xi = xs.astype(int); yi = ys.astype(int)
    xf = xs - xi; yf = ys - yi
    xf = xf * xf * (3 - 2 * xf); yf = yf * yf * (3 - 2 * yf)
    a = lat[np.ix_(yi, xi)]; b = lat[np.ix_(yi, xi + 1)]
    c = lat[np.ix_(yi + 1, xi)]; d = lat[np.ix_(yi + 1, xi + 1)]
    top = a + (b - a) * xf[None, :]
    bot = c + (d - c) * xf[None, :]
    return top + (bot - top) * yf[:, None]


def fbm(w, h, seed, octs=((2, 0.5), (4, 0.3), (8, 0.2))):
    return sum(wt * value_noise(w, h, o, max(1, o * h // w), seed + i) for i, (o, wt) in enumerate(octs))


def quant(v, lo=1, hi=15):
    v = np.clip(v, 0, 1)
    return (lo + np.round(v * (hi - lo))).astype(np.uint8)


# ----------------------------------------------------------------------------- atlases

class Atlas:
    def __init__(self):
        self.idx = np.zeros((256, 256), np.uint8)

    def put(self, u, v, img):
        h, w = img.shape
        self.idx[v:v + h, u:u + w] = img

    def pack(self):
        a = self.idx
        return (a[:, 0::2] | (a[:, 1::2] << 4)).astype(np.uint8).tobytes()


A0 = Atlas()     # world
A1 = Atlas()     # fish, icons, map
A2 = Atlas()     # fonts, logo
A3 = Atlas()     # the water pattern (a whole slot: per-quad world-anchored texture coordinates)

# ---- world materials: name -> dict(u, v, w, h, key palettes (4 x 16 colours), emissive mask)
# keys: 0 night, 1 dawn, 2 day, 3 dusk
LIGHT = [(0.40, 0.46, 0.80), (0.92, 0.70, 0.70), (1.0, 0.98, 0.94), (1.0, 0.66, 0.46)]
GLOW = [1.0, 0.25, 0.0, 0.55]                 # emissive strength per key
REFL = (0.66, 0.74, 0.86)                     # reflection palettes: darker and bluer
MATS = {}
MAT_ORDER = []


def material(name, u, v, img, cols, emissive=(), lit=None, glow_col=(255, 196, 110), atlas=None):
    """cols: 15 albedo colours for indices 1..15. emissive: indices that glow at night."""
    (atlas or A0).put(u, v, img)
    assert len(cols) == 15, (name, len(cols))
    keys = []
    for k in range(4):
        pal = [(0, 0, 0)]
        for i, c in enumerate(cols):
            ii = i + 1
            L = LIGHT[k] if lit is None else lit[k]
            col = tuple(c[j] * L[j] for j in range(3))
            if ii in emissive:
                g = GLOW[k]
                col = lerp3(col, glow_col, g)
            pal.append(col)
        keys.append(pal)
    MATS[name] = dict(u=u, v=v, w=img.shape[1], h=img.shape[0], keys=keys, src=len(MAT_ORDER))
    MAT_ORDER.append(name)


yy, xx = np.mgrid[0:32, 0:32]

# grass: tileable noise + blades
n = fbm(32, 32, 10, ((2, 0.45), (4, 0.35), (8, 0.2)))
bl = (rng.random((32, 32)) > 0.8) * 0.22
img = quant(n * 0.85 + bl, 1, 12)
material('grass', 0, 0, img, ramp([(34, 58, 30), (62, 98, 44), (98, 134, 58), (150, 170, 80)], 12)
         + [(160, 120, 160), (220, 200, 120), (240, 240, 230)])
# grass with flowers
img2 = img.copy()
fl = rng.random((32, 32))
img2[fl > 0.975] = 13
img2[(fl > 0.962) & (fl <= 0.975)] = 14
img2[(fl > 0.955) & (fl <= 0.962)] = 15
material('flowers', 32, 0, img2, ramp([(34, 58, 30), (62, 98, 44), (98, 134, 58), (150, 170, 80)], 12)
         + [(230, 150, 190), (245, 225, 120), (240, 240, 235)])
# shore mud & pebbles
n = fbm(32, 32, 20)
img = quant(n, 1, 10)
peb = value_noise(32, 32, 8, 8, 33)
img[peb > 0.78] = 11 + (peb[peb > 0.78] * 20 % 4).astype(np.uint8)
material('mud', 64, 0, img, ramp([(52, 44, 36), (88, 74, 56), (126, 108, 80)], 10)
         + [(110, 110, 104), (140, 136, 128), (170, 166, 156), (196, 190, 180), (0, 0, 0)])
# sandy path
n = fbm(32, 32, 30, ((4, 0.6), (16, 0.4)))
material('sand', 96, 0, quant(n, 1, 15), ramp([(120, 100, 70), (176, 150, 108), (214, 192, 150)]))
# wooden planks (run along u): 4 boards of 8 texels, grain, gaps, nails
img = np.zeros((32, 32), np.uint8)
g = fbm(32, 32, 40, ((1, 0.3), (16, 0.7)))
for b in range(4):
    shade = 0.15 * ((b * 7) % 3)
    for y in range(b * 8, b * 8 + 8):
        row = g[y] * 0.6 + 0.25 + shade + 0.08 * np.sin(np.arange(32) * 0.9 + b)
        img[y] = quant(row, 2, 13)
    img[b * 8 + 7, :] = 1
    img[b * 8 + 3, (b * 11) % 32] = 14
    img[b * 8 + 3, (b * 11 + 16) % 32] = 14
material('planks', 128, 0, img, ramp([(40, 26, 16), (90, 60, 36), (138, 98, 60), (176, 136, 90)], 13)
         + [(70, 70, 76), (0, 0, 0)])
# log / post: vertical grain
g = fbm(32, 32, 50, ((8, 0.6), (1, 0.4)))
img = quant(g.T * 0.8 + 0.1, 1, 15)
img[:, 0] = 1; img[:, 31] = 1
material('log', 160, 0, img, ramp([(36, 24, 16), (82, 56, 36), (120, 86, 56), (150, 116, 80)]))
# stone blocks (bridge)
img = np.zeros((32, 32), np.uint8)
n = fbm(32, 32, 60)
for r in range(4):
    off = 8 if r % 2 else 0
    for y in range(r * 8, r * 8 + 8):
        img[y] = quant(n[y] * 0.7 + 0.2 + 0.05 * ((r * 5 + y) % 3), 3, 14)
    img[r * 8, :] = 1
    for x in range(0, 32, 16):
        img[r * 8:r * 8 + 8, (x + off) % 32] = 1
mossm = value_noise(32, 32, 4, 4, 61) > 0.7
img[mossm & (img > 4)] = 15
material('stone', 192, 0, img, ramp([(50, 50, 56), (100, 100, 104), (150, 146, 140), (190, 186, 176)], 14)
         + [(70, 100, 50)])
# roof tiles (rows of rounded tiles), warm terracotta / blue-grey per house via palette
img = np.zeros((32, 32), np.uint8)
for y in range(32):
    for x in range(32):
        row = y // 6
        xo = (x + (3 if row % 2 else 0)) % 6
        d = (xo - 2.5) ** 2 / 9 + ((y % 6) - 1) ** 2 / 30
        img[y, x] = 2 + int(np.clip((1 - d) * 11, 0, 12))
    if y % 6 == 5:
        img[y, :] = 1
material('roof', 224, 0, img, ramp([(50, 20, 18), (120, 52, 40), (176, 86, 60), (210, 130, 96)]))
material('roofb', 224, 0, img, ramp([(24, 30, 50), (52, 66, 96), (86, 104, 140), (130, 146, 176)]))

# walls with a window: plaster or timber, window texels 12-15 are emissive (lit house)
def wall_img(timber):
    img = np.zeros((32, 32), np.uint8)
    n = fbm(32, 32, 70 + timber)
    img[:, :] = quant(n * 0.6 + 0.25, 2, 9)
    if timber:
        for x in (0, 1, 30, 31):
            img[:, x] = 10
        img[0:2, :] = 10
        img[30:32, :] = 10
        for x in range(32):
            img[15, x] = 10
    # window 12x12 centred, with a cross frame
    wx0, wy0 = 10, 9
    img[wy0 - 1:wy0 + 13, wx0 - 1:wx0 + 13] = 11
    for y in range(12):
        for x in range(12):
            img[wy0 + y, wx0 + x] = 12 + min(3, int((x + y) / 7))
    img[wy0:wy0 + 12, wx0 + 5:wx0 + 7] = 11
    img[wy0 + 5:wy0 + 7, wx0:wx0 + 12] = 11
    return img


WALLC = ramp([(150, 132, 108), (214, 198, 170), (236, 226, 204)], 9) + [(96, 64, 40), (70, 48, 32)]
GLASS_DAY = [(60, 76, 100), (80, 100, 128), (104, 126, 150), (140, 160, 180)]
material('wall_dark', 0, 32, wall_img(0), WALLC + GLASS_DAY)
material('wall_lit', 0, 32, wall_img(0), WALLC + GLASS_DAY, emissive=(12, 13, 14, 15))
material('timber_dark', 32, 32, wall_img(1), WALLC + GLASS_DAY)
material('timber_lit', 32, 32, wall_img(1), WALLC + GLASS_DAY, emissive=(12, 13, 14, 15))
A0.put(32, 32, wall_img(1))

# reeds: alpha blades (32x32), u across, v up=0
img = np.zeros((32, 32), np.uint8)
for k in range(9):
    x0 = 2 + k * 3.3 + rng.uniform(-1, 1)
    lean = rng.uniform(-4, 4)
    top = int(rng.uniform(0, 10))
    for y in range(top, 32):
        t = (y - top) / (32 - top)
        x = int(round(x0 + lean * (1 - t) ** 2))
        if 0 <= x < 32:
            img[y, x] = 2 + int(t * 9)
            if t > 0.4 and x + 1 < 32:
                img[y, x + 1] = 1 + int(t * 8)
    if k % 3 == 0:  # cattail head
        x = int(round(x0 + lean))
        for y in range(top, top + 5):
            for dx in (0, 1):
                if 0 <= x + dx < 32:
                    img[y, x + dx] = 13 + (y - top) % 2
material('reeds', 64, 32, img, ramp([(150, 170, 90), (90, 130, 60), (40, 70, 34)], 12)
         + [(80, 50, 30), (110, 70, 40), (0, 0, 0)])
# lily pad with a notch, some with flowers (32x32), centred
img = np.zeros((32, 32), np.uint8)
for y in range(32):
    for x in range(32):
        dx, dy = x - 15.5, y - 15.5
        r = math.hypot(dx, dy)
        a = math.atan2(dy, dx)
        if r < 15 and not (abs(a - 0.3) < 0.28 and r > 2):
            vein = abs(math.sin(a * 6)) < 0.12
            img[y, x] = 3 + int(np.clip(r / 15 * 7, 0, 7)) if not vein else 11
            if r > 13.5:
                img[y, x] = 2
material('lily', 96, 32, img, ramp([(30, 60, 30), (60, 110, 50), (110, 160, 70)], 10)
         + [(150, 190, 100), (240, 180, 200), (250, 230, 240), (250, 220, 100), (0, 0, 0)])
# lily flower: a separate small cell (16x16 at 128,32)
fimg = np.zeros((16, 16), np.uint8)
for y in range(16):
    for x in range(16):
        dx, dy = x - 7.5, y - 7.5
        r = math.hypot(dx, dy)
        a = math.atan2(dy, dx)
        petal = 6.5 * (0.6 + 0.4 * abs(math.cos(a * 4)))
        if r < 2.2:
            fimg[y, x] = 14
        elif r < petal:
            fimg[y, x] = 12 if r < petal * 0.65 else 13
A0.put(128, 32, fimg)

# swatches: 16 flat colours in 8x8 blocks (a 32x32 cell): props and the angler
SWATCH = [None,
          (46, 66, 120),     # 1 coat blue
          (30, 44, 84),      # 2 coat dark
          (224, 196, 120),   # 3 straw hat
          (176, 142, 80),    # 4 straw dark
          (232, 186, 150),   # 5 skin
          (52, 36, 30),      # 6 hair / boots
          (120, 84, 50),     # 7 rod / wood
          (210, 50, 44),     # 8 bobber red
          (240, 236, 226),   # 9 bobber white / cloth
          (40, 40, 46),      # 10 iron
          (255, 200, 110),   # 11 lantern glow (emissive)
          (196, 60, 50),     # 12 red paper / scarf
          (150, 120, 84),    # 13 rope / basket
          (86, 110, 70),     # 14 trousers olive
          (250, 236, 170)]   # 15 lantern bright (emissive)
img = np.zeros((32, 32), np.uint8)
for i in range(1, 16):
    img[(i // 4) * 8:(i // 4) * 8 + 8, (i % 4) * 8:(i % 4) * 8 + 8] = i
material('swatch', 160, 32, img, SWATCH[1:], emissive=(11, 15))
SW_UV = {i: (160 + (i % 4) * 8 + 4, 32 + (i // 4) * 8 + 4) for i in range(1, 16)}

# paper lantern texture (festival lanterns and pier lanterns): 16x24 at (192, 32)
img = np.zeros((24, 16), np.uint8)
for y in range(24):
    for x in range(16):
        dx = (x - 7.5) / 7.5
        dy = (y - 12) / 10
        if y < 2 or y > 21:
            if abs(dx) < 0.45:
                img[y, x] = 1
        elif dx * dx + dy * dy * 0.55 < 1:
            v = 1 - (dx * dx + dy * dy * 0.4)
            img[y, x] = 3 + int(np.clip(v * 12, 0, 12))
            if y % 5 == 0:
                img[y, x] = 2
material('paper', 192, 32, img, [(40, 30, 30), (150, 50, 40)] + ramp([(170, 60, 44), (230, 120, 70), (255, 220, 150)], 13),
         emissive=tuple(range(3, 16)), glow_col=(255, 200, 120))
# rowboat / bench wood re-uses planks; window shutters re-use timber.

# treeline: 256x64 silhouette of tree crowns with alpha above, at (0, 64)
TW, TH = 256, 64
img = np.zeros((TH, TW), np.uint8)
hgt = np.zeros(TW)
xs = np.arange(TW)
for k in range(46):
    cx = rng.uniform(0, TW)
    conifer = rng.random() < 0.55
    h = rng.uniform(34, 60)
    wdt = rng.uniform(7, 14) if conifer else rng.uniform(10, 18)
    d = np.minimum(np.abs(xs - cx), TW - np.abs(xs - cx))
    if conifer:
        prof = h - d * (h / wdt) * 1.1
    else:
        prof = np.sqrt(np.clip(wdt * wdt - d * d, 0, None)) * (h / wdt) * 0.55 + h * 0.45
        prof[d > wdt] = -1
    hgt = np.maximum(hgt, prof)
hgt = np.clip(hgt, 26, 62)
sh = fbm(TW, TH, 90, ((16, 0.5), (32, 0.3), (64, 0.2)))
for x in range(TW):
    top = TH - int(hgt[x])
    for y in range(top, TH):
        depth = (y - top) / max(1, TH - top)
        v = sh[y, x] * 0.7 + (1 - depth) * 0.4 - 0.1
        img[y, x] = quant(v, 2, 13)
    img[top, x] = 1
    if top + 1 < TH:
        img[top + 1, x] = max(img[top + 1, x], 12)
trunk = (rng.random(TW) > 0.93)
for x in np.where(trunk)[0]:
    img[TH - 10:TH, x] = 14
material('trees', 0, 64, img, [(20, 34, 26)] + ramp([(16, 30, 22), (30, 56, 34), (52, 86, 46), (90, 120, 60)], 12)
         + [(60, 44, 30), (0, 0, 0)])
# distant hills: 256x32 at (0, 128), blue-green, alpha above
img = np.zeros((32, 256), np.uint8)
hh = np.zeros(256)
for k, (fr, am) in enumerate([(1, 7), (2, 5), (5, 2.5), (11, 1.2), (23, 0.6)]):
    ph = rng.uniform(0, 2 * math.pi)
    hh += am * np.sin(2 * math.pi * fr * xs / 256 + ph)
hh = 16 + hh
hh = np.clip(hh, 4, 31)
hn = fbm(256, 32, 95, ((16, 0.6), (64, 0.4)))
for x in range(256):
    top = 32 - int(hh[x])
    for y in range(top, 32):
        img[y, x] = quant(hn[y, x] * 0.5 + (y - top) / 32 * 0.6, 1, 15)
material('hills', 0, 128, img, ramp([(110, 140, 170), (80, 110, 130), (60, 86, 96)]),
         lit=[(0.28, 0.32, 0.55), (0.95, 0.72, 0.76), (1, 1, 1), (0.95, 0.62, 0.55)])

# water: a 256x256 slot of a 64-periodic wave pattern (slot 3). Indices are bands that the
# cart rotates through the palette (shimmer). Quads take world-anchored coordinates.
wy, wx = np.mgrid[0:256, 0:256]
T = 2 * math.pi / 64
pat = (wx / 64.0 + 0.16 * np.sin(T * wy * 2 + 0.5) + 0.07 * np.sin(T * (wx + wy)) + 0.05 * np.sin(T * (3 * wx - wy))
       + 0.04 * np.sin(T * (2 * wy - wx) * 2))
img = (1 + ((pat * 30) % 15)).astype(np.uint8)
WATER_DAY = []
for i in range(15):
    s_ = 0.5 + 0.5 * math.cos(2 * math.pi * i / 15)
    WATER_DAY.append(lerp3((44, 96, 124), (126, 180, 198), s_ ** 3))
material('water', 0, 0, img, WATER_DAY, atlas=A3,
         lit=[(0.30, 0.38, 0.66), (0.85, 0.72, 0.80), (1, 1, 1), (0.95, 0.70, 0.62)])

NSRC = len(MAT_ORDER)
# ---- static (unlit) art in slot 0 with grey ramps: tinted by polygon colour
STAT = []          # list of 16-colour palettes (static), numbered from STAT_BASE
STAT_BASE = 48


def stat_pal(cols):
    cols = [(0, 0, 0)] + list(cols)
    cols = cols + [(0, 0, 0)] * (16 - len(cols))
    STAT.append(cols[:16])
    return STAT_BASE + len(STAT) - 1


GREY = stat_pal([(v, v, v) for v in np.linspace(17, 255, 15)])
# halo 64x64 (32, 160): soft radial
img = np.zeros((64, 64), np.uint8)
for y in range(64):
    for x in range(64):
        r = math.hypot(x - 31.5, y - 31.5) / 32
        v = max(0, 1 - r) ** 1.7
        if v > 0.02:
            img[y, x] = max(1, int(round(v * 15)))
A0.put(32, 160, img)
# ripple ring 64x64 (96, 160)
img = np.zeros((64, 64), np.uint8)
for y in range(64):
    for x in range(64):
        r = math.hypot(x - 31.5, y - 31.5) / 31.5
        v = math.exp(-((r - 0.82) / 0.09) ** 2) + 0.35 * math.exp(-((r - 0.6) / 0.07) ** 2)
        if v > 0.06 and r < 1:
            img[y, x] = max(1, min(15, int(round(v * 15))))
A0.put(96, 160, img)
# sparkle 16x16 (160, 160)
img = np.zeros((16, 16), np.uint8)
for y in range(16):
    for x in range(16):
        dx, dy = abs(x - 7.5), abs(y - 7.5)
        v = max(0, 1 - (dx * dy) / 6 - (dx + dy) / 11)
        if v > 0.05:
            img[y, x] = max(1, int(round(v * 15)))
A0.put(160, 160, img)
# soft dot 16x16 (176, 160)
img = np.zeros((16, 16), np.uint8)
for y in range(16):
    for x in range(16):
        r = math.hypot(x - 7.5, y - 7.5) / 8
        v = max(0, 1 - r) ** 1.2
        if v > 0.05:
            img[y, x] = max(1, int(round(v * 15)))
A0.put(176, 160, img)
# fish shadow 32x16 (192, 160): fish silhouette, blurred
sim = Image.new('L', (128, 64), 0)
d = ImageDraw.Draw(sim)
d.ellipse((14, 18, 96, 46), fill=255)
d.polygon([(90, 32), (122, 14), (114, 32), (122, 50)], fill=255)
sim = sim.filter(ImageFilter.GaussianBlur(5)).resize((32, 16), Image.BOX)
a = np.asarray(sim, np.float32) / 255
A0.put(192, 160, np.where(a > 0.06, np.clip(np.round(a * 15), 1, 15), 0).astype(np.uint8))
# moon 32x32 (224, 160): disc with maria (own palette)
img = np.zeros((32, 32), np.uint8)
mn = fbm(32, 32, 120, ((3, 0.6), (6, 0.4)))
for y in range(32):
    for x in range(32):
        r = math.hypot(x - 15.5, y - 15.5)
        if r < 14.6:
            v = 0.75 + 0.25 * (1 - r / 15) - (mn[y, x] > 0.58) * 0.25
            img[y, x] = max(1, int(round(np.clip(v, 0, 1) * 15)))
        elif r < 15.5:
            img[y, x] = 6
A0.put(224, 160, img)
MOON_PAL = stat_pal(ramp([(120, 130, 160), (200, 210, 230), (255, 252, 240)]))
# cloud 64x32 (0, 192): puffy, alpha outside, grey ramp (tinted)
cim = Image.new('L', (256, 128), 0)
d = ImageDraw.Draw(cim)
for k in range(12):
    cx = rng.uniform(50, 206)
    cy = rng.uniform(56, 84)
    r = rng.uniform(18, 34) * (1 - abs(cx - 128) / 200)
    d.ellipse((cx - r * 1.3, cy - r, cx + r * 1.3, cy + r), fill=255)
d.rectangle((40, 84, 216, 128), fill=0)
cim = cim.filter(ImageFilter.GaussianBlur(4)).resize((64, 32), Image.BOX)
ca = np.asarray(cim, np.float32) / 255
shade = np.linspace(1.0, 0.55, 32)[:, None]
img = np.where(ca > 0.35, np.clip(np.round((0.45 + 0.55 * ca) * shade * 15), 1, 15), 0).astype(np.uint8)
A0.put(0, 224, img)
# light beam: vertical gradient 16x32 (64, 224)
img = np.zeros((32, 16), np.uint8)
for y in range(32):
    for x in range(16):
        v = (1 - y / 32) * max(0, 1 - abs(x - 7.5) / 8) ** 0.7
        if v > 0.03:
            img[y, x] = max(1, int(round(v * 15)))
A0.put(64, 224, img)
# glitter streak 16x8 (80, 224): a horizontal sparkle for the moon/sun path
img = np.zeros((8, 16), np.uint8)
for y in range(8):
    for x in range(16):
        v = max(0, 1 - abs(x - 7.5) / 8) * max(0, 1 - abs(y - 3.5) / 3) ** 1.5
        if v > 0.05:
            img[y, x] = max(1, int(round(v * 15)))
A0.put(80, 224, img)

UV = dict(halo=(32, 160, 64, 64), ring=(96, 160, 64, 64), spark=(160, 160, 16, 16),
          dot=(176, 160, 16, 16), shadow=(192, 160, 32, 16), moon=(224, 160, 32, 32),
          cloud=(0, 224, 64, 32), beam=(64, 224, 16, 32), glint=(80, 224, 16, 8),
          lilyflower=(128, 32, 16, 16), paper=(192, 32, 16, 24))

# ----------------------------------------------------------------------------- world layout

WATER_Y = 0.0
NA = 60          # azimuth segments of the shore
NCHUNK = 15


def bump(x):
    return math.exp(-x * x)


def angdiff(a, b):
    d = (a - b + math.pi) % (2 * math.pi) - math.pi
    return d


A_BRIDGE = 0.0
A_RIVER = -1.80
A_LILY = 1.05
A_PIER = math.pi
A_REEDS = -1.42
VILLAGE_A = (2.15, 2.92)


def shore_r(a):
    r = 25.0 + 2.4 * math.sin(2 * a + 0.7) + 1.4 * math.sin(3 * a + 2.1) + 0.9 * math.sin(5 * a + 0.4)
    r += 14.0 * bump(angdiff(a, A_BRIDGE) / 0.085)
    r += 9.0 * bump(angdiff(a, A_RIVER) / 0.10)
    r += 2.5 * bump(angdiff(a, A_LILY + 0.25) / 0.35)        # the lily cove
    return r


def apos(a, r, y=0.0):
    return (r * math.sin(a), y, r * math.cos(a))


RING_OFF = [0.0, 1.0, 3.0, 6.5, 12.0]
RING_H = [0.0, 0.3, 0.72, 1.5, 2.7]


def in_village(a):
    return VILLAGE_A[0] - 0.1 < (a % (2 * math.pi)) < VILLAGE_A[1] + 0.1


def ring_height(a, k):
    if k == 0:
        return 0.0
    h = RING_H[k]
    if in_village(a) and 1 <= k <= 4:
        h = min(h, 0.42 + 0.08 * k)
    # the river mouth and the bridge inlet: low banks
    h *= 1 - 0.45 * bump(angdiff(a, A_RIVER) / 0.18)
    h += 0.25 * k / 5 * math.sin(a * 7 + k) + 0.15 * math.sin(a * 13 + 2 * k)
    return max(0.12 * k, h)


def lit_tint(n, ao=1.0, base=1.0):
    """Baked tint (0x808080 = unchanged) from a soft sky light and ambient occlusion."""
    sky = 0.62 + 0.38 * max(0.0, n[1]) + 0.12 * max(0.0, -n[0] * 0.6 + n[2] * 0.3)
    v = 128 * sky * ao * base
    return rgbw(v, v, v)


class Face:
    __slots__ = ('pts', 'uvs', 'cols', 'mat', 'flags', 'n', 'blend', 'refl', 'lo', 'hi')

    def __init__(self, pts, uvs, cols, mat, n, flags=0, blend=0, refl=True, lo=True, hi=True):
        self.pts, self.uvs, self.cols, self.mat, self.n = pts, uvs, cols, mat, n
        self.flags, self.blend, self.refl, self.lo, self.hi = flags, blend, refl, lo, hi


def sub(a, b):
    return tuple(a[i] - b[i] for i in range(3))


def cross(a, b):
    return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0])


def dot(a, b):
    return sum(a[i] * b[i] for i in range(3))


def norm(v):
    l = math.sqrt(dot(v, v)) or 1
    return tuple(c / l for c in v)


def emit(faces, mirror=False, centre=None, lo=False):
    """Builds a Mesh from logical faces. Corners are BL, BR, TL, TR (quads) as seen from
    the side the normal points to; the winding is fixed up from the normal. mirror: y -> -y
    and reflection palettes."""
    m = Mesh()
    vmap = {}

    def vid(p):
        key = tuple(round(c, 4) for c in p)
        if key not in vmap:
            vmap[key] = m.vertex(*p)
        return vmap[key]

    for f in faces:
        if mirror and not f.refl:
            continue
        if lo and not f.lo:
            continue
        if not lo and not f.hi:
            continue
        pts = list(f.pts)
        n = f.n
        if mirror:
            pts = [(p[0], 2 * WATER_Y - p[1], p[2]) for p in pts]
            n = (n[0], -n[1], n[2])
        uvs, cols = (list(f.uvs) if f.uvs else None), list(f.cols)
        c = cross(sub(pts[1], pts[0]), sub(pts[2], pts[0]))
        if dot(c, n) > 0:          # wrong winding: mirror the corner order
            if len(pts) == 4:
                order = [1, 0, 3, 2]
            else:
                order = [1, 0, 2]
            pts = [pts[i] for i in order]
            if uvs:
                uvs = [uvs[i] for i in order]
            cols = [cols[i] for i in order]
        mat = f.mat
        if isinstance(mat, str):
            pal = PALNUM[mat] + (REFL_OFF if mirror else 0)
            slot, fourbit = 0, True
        else:
            slot, fourbit, pal = mat
        if mirror:
            cols = [scale_tint(c, 0.92) for c in cols]
        idx = [vid(p) for p in pts]
        m.face(idx, cols, uvs, f.flags, slot=slot, four_bit=fourbit, palette=pal, blend=f.blend)
    return m


def scale_tint(c, k):
    r, g, b = c & 255, (c >> 8) & 255, (c >> 16) & 255
    return rgbw(r * k, g * k, b * k)


# ---- palette numbering: live world palettes 0..23 (dest), reflections at +24
DEST = []          # dest palette -> source material name
PALNUM = {}


def dest(name, src=None):
    PALNUM[name] = len(DEST)
    DEST.append(src or name)


for nm in ('grass', 'flowers', 'mud', 'sand', 'planks', 'log', 'stone', 'roof', 'roofb', 'reeds', 'lily',
           'swatch', 'paper', 'trees', 'hills', 'water'):
    dest(nm)
NHOUSE = 8
for i in range(NHOUSE):
    dest('house%d' % i, 'wall_dark' if i % 2 == 0 else 'timber_dark')
REFL_OFF = 24
assert len(DEST) <= REFL_OFF

# ---- terrain: a polar grid around the lake (ring 0 on the waterline), in 12 chunks


def cell_uv(mat, w=None, h=None):
    M = MATS[mat]
    u0, v0 = M['u'], M['v']
    w = w or M['w']
    h = h or M['h']
    return [(u0, v0 + h - 1), (u0 + w - 1, v0 + h - 1), (u0, v0), (u0 + w - 1, v0)]


ring_pts = []
for i in range(NA + 1):
    a = 2 * math.pi * i / NA - math.pi
    R = shore_r(a)
    row = []
    for k, off in enumerate(RING_OFF):
        row.append(apos(a, R + off, ring_height(a, k)))
    ring_pts.append(row)
for k in range(len(RING_OFF)):
    ring_pts[NA][k] = ring_pts[0][k]

chunk_faces = [[] for _ in range(NCHUNK)]     # near version: every ring
chunk_far = [[] for _ in range(NCHUNK)]       # far version: rings 0-2-4
chunk_refl = [[] for _ in range(NCHUNK)]      # for the reflection: treelines and the top ring
chunk_pts = [[] for _ in range(NCHUNK)]
tree_h = []
for i in range(NA + 1):
    a = 2 * math.pi * i / NA - math.pi
    th = 5.5 + 2.0 * math.sin(a * 5 + 1) + 1.2 * math.sin(a * 11)
    if in_village(a):
        th *= 0.7
    th *= 1 - 0.6 * bump(angdiff(a, A_RIVER) / 0.22)
    tree_h.append(th)
tree_h[NA] = tree_h[0]
seg_mat = {}


def ground_face(i, k0, k1, a0):
    p00, p01 = ring_pts[i][k0], ring_pts[i + 1][k0]
    p10, p11 = ring_pts[i][k1], ring_pts[i + 1][k1]
    nrm = norm(cross(sub(p01, p00), sub(p10, p00)))
    if nrm[1] < 0:
        nrm = tuple(-c for c in nrm)
    key = (i, k0)
    if key not in seg_mat:
        if k0 == 0:
            mat = 'mud'
        elif k0 == 1:
            mat = 'sand' if (in_village(a0) or rng.random() < 0.3) else 'grass'
        else:
            mat = 'flowers' if rng.random() < 0.22 else 'grass'
        if in_village(a0) and k0 in (2, 3) and (i % 3 == 0):
            mat = 'sand'
        seg_mat[key] = mat
    mat = seg_mat[key]
    cols = []
    for p in (p00, p01, p10, p11):
        ao = 0.82 if p[1] < 0.05 else 1.0
        ao *= 0.92 + 0.08 * math.sin(p[0] * 0.7 + p[2] * 0.4)
        cols.append(lit_tint(nrm, ao))
    return Face([p00, p01, p10, p11], cell_uv(mat), cols, mat, nrm), [p00, p01, p10, p11]


TOP = len(RING_OFF) - 1


def tree_face(i0, i1, k, hk, u0, uw):
    pb0, pb1 = ring_pts[i0][k], ring_pts[i1][k]
    pt0 = (pb0[0], pb0[1] + tree_h[i0] * hk, pb0[2])
    pt1 = (pb1[0], pb1[1] + tree_h[i1] * hk, pb1[2])
    nin = norm((-(pb0[0] + pb1[0]), 0, -(pb0[2] + pb1[2])))
    uvs = [(u0, 127), (u0 + uw, 127), (u0, 64), (u0 + uw, 64)]
    tcol = [lit_tint((0, 0.3, 0), 0.85)] * 2 + [lit_tint((0, 1, 0), 1.0)] * 2
    return Face([pb0, pb1, pt0, pt1], uvs, tcol, 'trees', nin), [pt0, pt1]


def front_row(i):
    a0 = 2 * math.pi * i / NA - math.pi
    return not in_village(a0) and i % 2 == 0 and abs(angdiff(a0, A_RIVER)) > 0.2 and abs(angdiff(a0, A_BRIDGE)) > 0.15


SEGS = NA // NCHUNK
for i in range(NA):
    ch = i // SEGS
    a0 = 2 * math.pi * i / NA - math.pi
    for k in range(TOP):
        f, pts = ground_face(i, k, k + 1, a0)
        chunk_faces[ch].append(f)
        chunk_pts[ch] += pts
    f, _ = ground_face(i, TOP - 1, TOP, a0)
    chunk_refl[ch].append(f)
    tf, pts = tree_face(i, i + 1, TOP, 1.0, (i % 4) * 64, 63)
    chunk_faces[ch].append(tf)
    chunk_refl[ch].append(tf)
    chunk_pts[ch] += pts
    if front_row(i):
        tf, _ = tree_face(i, i + 1, TOP - 1, 0.55, ((i * 3) % 4) * 64, 63)
        chunk_faces[ch].append(tf)
        chunk_refl[ch].append(tf)
# the far version: every other column; one forested bank from the waterline up to the
# treeline (tree texture), and the treeline itself
for i in range(0, NA, 2):
    ch = i // SEGS
    a0 = 2 * math.pi * i / NA - math.pi
    p00, p01 = ring_pts[i][0], ring_pts[i + 2][0]
    p10, p11 = ring_pts[i][TOP - 1], ring_pts[i + 2][TOP - 1]
    nrm = norm(cross(sub(p01, p00), sub(p10, p00)))
    if nrm[1] < 0:
        nrm = tuple(-c for c in nrm)
    if in_village(a0):
        mat = 'grass'
        uvs = cell_uv('grass')
    else:
        mat = 'trees'
        u0 = (i % 2) * 128
        uvs = [(u0, 127), (u0 + 127, 127), (u0, 100), (u0 + 127, 100)]
    chunk_far[ch].append(Face([p00, p01, p10, p11], uvs, [lit_tint(nrm, 0.8)] * 2 + [lit_tint(nrm, 0.95)] * 2, mat, nrm))
    q00, q01 = ring_pts[i][TOP - 1], ring_pts[i + 2][TOP - 1]
    q10, q11 = ring_pts[i][TOP], ring_pts[i + 2][TOP]
    nrm = norm(cross(sub(q01, q00), sub(q10, q00)))
    if nrm[1] < 0:
        nrm = tuple(-c for c in nrm)
    chunk_far[ch].append(Face([q00, q01, q10, q11], cell_uv('grass'), [lit_tint(nrm, 0.85)] * 4, 'grass', nrm))
    tf, _ = tree_face(i, i + 2, TOP, 1.0, (i % 2) * 128, 127)
    chunk_far[ch].append(tf)

CHUNKS = []
for ch in range(NCHUNK):
    pts = np.array(chunk_pts[ch])
    c = pts.mean(axis=0)
    r = np.sqrt(((pts - c) ** 2).sum(axis=1)).max()
    write('terr%d.bin' % ch, emit(chunk_faces[ch]).pack())
    write('terr%d_lo.bin' % ch, emit(chunk_far[ch]).pack())
    write('terr%d_r.bin' % ch, emit(chunk_far[ch], mirror=True).pack())
    CHUNKS.append((tuple(c), r, len(chunk_faces[ch]), len(chunk_far[ch]), len(chunk_refl[ch])))

# ---- far hills ring (radius 120) and its reflection
hill_faces = []
NH = 24
for i in range(NH):
    a0 = 2 * math.pi * i / NH
    a1 = 2 * math.pi * (i + 1) / NH
    R = 125.0
    p0, p1 = apos(a0, R, -0.5), apos(a1, R, -0.5)
    h = 22.0
    t0, t1 = apos(a0, R, h), apos(a1, R, h)
    u0 = (i % 4) * 64
    uvs = [(u0, 159), (u0 + 63, 159), (u0, 128), (u0 + 63, 128)]
    nin = norm((-(p0[0] + p1[0]), 0, -(p0[2] + p1[2])))
    hill_faces.append(Face([p0, p1, t0, t1], uvs, [0x808080] * 4, 'hills', nin))
write('hills.bin', emit(hill_faces).pack())
write('hills_r.bin', emit(hill_faces, mirror=True).pack())

# ---- props


def box_faces(x0, y0, z0, x1, y1, z1, mat, uvs=None, top=True, bottom=False, sides='nsew', base=1.0, refl=True,
              topmat=None, lod=True):
    """Axis-aligned box faces. uvs: corner uvs for every face (default: whole cell)."""
    out = []
    uv = uvs or cell_uv(mat)
    tm = topmat or mat
    tuv = uvs or cell_uv(tm)
    if top:
        out.append(Face([(x0, y1, z0), (x1, y1, z0), (x0, y1, z1), (x1, y1, z1)], tuv,
                        [lit_tint((0, 1, 0), 1, base)] * 4, tm, (0, 1, 0), refl=refl, lo=lod))
    if bottom:
        out.append(Face([(x0, y0, z0), (x1, y0, z0), (x0, y0, z1), (x1, y0, z1)], uv,
                        [lit_tint((0, -1, 0), 0.7, base)] * 4, mat, (0, -1, 0), refl=refl, lo=lod))
    lo = lit_tint((0, 0, 0), 0.75, base)
    hi = None
    if 's' in sides:
        n = (0, 0, -1); hi = lit_tint(n, 1, base)
        out.append(Face([(x0, y0, z0), (x1, y0, z0), (x0, y1, z0), (x1, y1, z0)], uv, [lo, lo, hi, hi], mat, n, refl=refl, lo=lod))
    if 'n' in sides:
        n = (0, 0, 1); hi = lit_tint(n, 1, base)
        out.append(Face([(x1, y0, z1), (x0, y0, z1), (x1, y1, z1), (x0, y1, z1)], uv, [lo, lo, hi, hi], mat, n, refl=refl, lo=lod))
    if 'w' in sides:
        n = (-1, 0, 0); hi = lit_tint(n, 1, base)
        out.append(Face([(x0, y0, z1), (x0, y0, z0), (x0, y1, z1), (x0, y1, z0)], uv, [lo, lo, hi, hi], mat, n, refl=refl, lo=lod))
    if 'e' in sides:
        n = (1, 0, 0); hi = lit_tint(n, 1, base)
        out.append(Face([(x1, y0, z0), (x1, y0, z1), (x1, y1, z0), (x1, y1, z1)], uv, [lo, lo, hi, hi], mat, n, refl=refl, lo=lod))
    return out


def transform(faces, yaw, origin):
    """Rotates faces about +Y by yaw (turning +Z toward +X) and moves them to origin."""
    s, c = math.sin(yaw), math.cos(yaw)

    def tp(p):
        return (origin[0] + p[0] * c + p[2] * s, origin[1] + p[1], origin[2] - p[0] * s + p[2] * c)

    def tn(n):
        return (n[0] * c + n[2] * s, n[1], -n[0] * s + n[2] * c)
    out = []
    for f in faces:
        out.append(Face([tp(p) for p in f.pts], f.uvs, f.cols, f.mat, tn(f.n), f.flags, f.blend, f.refl, f.lo, f.hi))
    return out


def sw_uv(i):
    u, v = SW_UV[i]
    return [(u - 2, v + 2), (u + 2, v + 2), (u - 2, v - 2), (u + 2, v - 2)]


def sw_box(x0, y0, z0, x1, y1, z1, i, **kw):
    return box_faces(x0, y0, z0, x1, y1, z1, 'swatch', uvs=sw_uv(i), **kw)


def plank_uv(len_texels=32):
    M = MATS['planks']
    return [(M['u'], M['v'] + 31), (M['u'] + len_texels - 1, M['v'] + 31), (M['u'], M['v']), (M['u'] + len_texels - 1, M['v'])]


def deck(length, width, y, seg=1.6, thick=0.12, posts=True, post_every=2.0, x_off=0.0, sag=0.0, wob=0.0):
    """A plank deck in local space: along +Z from z=0 to z=length, x in +-width/2."""
    out = []
    nseg = max(1, int(round(length / seg)))
    w2 = width / 2
    for s_ in range(nseg):
        z0 = length * s_ / nseg
        z1 = length * (s_ + 1) / nseg
        yy0 = y + wob * math.sin(s_ * 2.1)
        yy1 = y + wob * math.sin((s_ + 1) * 2.1)
        # top: planks run across x, so u along x
        M = MATS['planks']
        uvs = [(M['u'], M['v'] + 31), (M['u'] + 31, M['v'] + 31), (M['u'], M['v']), (M['u'] + 31, M['v'])]
        # rotate: v along z (boards across the deck)
        uvs = [(M['u'], M['v']), (M['u'], M['v'] + 31), (M['u'] + 31, M['v']), (M['u'] + 31, M['v'] + 31)]
        tint = [lit_tint((0, 1, 0), 1.0, 0.95 + 0.1 * ((s_ * 37) % 3) / 2)] * 4
        out.append(Face([(-w2 + x_off, yy0, z0), (w2 + x_off, yy0, z0), (-w2 + x_off, yy1, z1), (w2 + x_off, yy1, z1)],
                        uvs, tint, 'planks', (0, 1, 0)))
        # sides
        lo = lit_tint((0, 0, 0), 0.6)
        hi = lit_tint((1, 0.2, 0), 0.85)
        for sx in (-1, 1):
            x = sx * w2 + x_off
            n = (sx, 0, 0)
            out.append(Face([(x, yy0 - thick, z0), (x, yy1 - thick, z1), (x, yy0, z0), (x, yy1, z1)],
                            plank_uv(), [lo, lo, hi, hi], 'planks', n))
    # end cap
    lo = lit_tint((0, 0, 0), 0.6)
    out.append(Face([(-w2 + x_off, y - thick, length), (w2 + x_off, y - thick, length), (-w2 + x_off, y, length),
                     (w2 + x_off, y, length)], plank_uv(), [lo] * 4, 'planks', (0, 0, 1)))
    if posts:
        z = 0.3
        while z < length:
            for sx in (-1, 1):
                x = sx * (w2 - 0.08) + x_off
                out += box_faces(x - 0.1, -0.1, z - 0.1, x + 0.1, y - thick, z + 0.1, 'log', top=False, base=0.8,
                                 refl=False, lod=False)
            z += post_every
    return out


def lantern_post(x, z, y, h=1.5, side=0):
    """A wooden post with a hanging paper lantern; returns faces and the lantern centre."""
    out = box_faces(x - 0.06, y, z - 0.06, x + 0.06, y + h, z + 0.06, 'log', base=0.9, top=False, lod=False)
    lx = x + 0.3 * side
    ly = y + h - 0.3
    if side:
        out += box_faces(min(x, lx) - 0.03, y + h - 0.06, z - 0.03, max(x, lx) + 0.03, y + h, z + 0.03, 'log',
                         base=0.9, sides='ns', lod=False)
    pu = [(192, 55), (207, 55), (192, 32), (207, 32)]
    out += box_faces(lx - 0.11, ly - 0.16, z - 0.11, lx + 0.11, ly + 0.16, z + 0.11, 'paper', uvs=pu, refl=False, lod=False,
                     top=False)
    out += sw_box(lx - 0.07, ly + 0.16, z - 0.07, lx + 0.07, ly + 0.2, z + 0.07, 10, refl=False, lod=False)
    return out, (lx, ly, z)


DOCKS = []          # dicts: name, stand, yaw, faces, lanterns


def place(faces, lanterns, yaw, origin):
    s, c = math.sin(yaw), math.cos(yaw)
    lt = [(origin[0] + p[0] * c + p[2] * s, origin[1] + p[1], origin[2] - p[0] * s + p[2] * c) for p in lanterns]
    return transform(faces, yaw, origin), lt


def dock_basic(a, length, width, y, extra=None, lanterns_every=None, wob=0.0, post_every=2.0, end_lantern=True):
    R = shore_r(a)
    base = apos(a, R + 1.6)
    yaw = math.atan2(-base[0], -base[2])          # facing the lake centre
    f = deck(length + 1.6, width, y, wob=wob, post_every=post_every)
    lan = []
    if lanterns_every:
        # in lighting order: the far end first (in view), then back toward the shore
        for z in (length + 1.4, 3.2, 0.9):
            for side in (1, -1):
                lf, lp = lantern_post(side * (width / 2 - 0.1), z, y, side=-side)
                f += lf; lan.append(lp)
    elif end_lantern:
        lf, lp = lantern_post(width / 2 - 0.1, length + 1.2, y, side=-1)
        f += lf; lan.append(lp)
    if extra:
        ef, el = extra(length, width, y)
        f += ef; lan += el
    faces, lt = place(f, lan, yaw, (base[0], 0, base[2]))
    s, c = math.sin(yaw), math.cos(yaw)
    sz = length + 1.6 - 0.9
    stand = (base[0] + s * sz, y, base[2] + c * sz)
    return dict(stand=stand, yaw=yaw, faces=faces, lanterns=lt, base=base)


# The Village Pier: long, lantern posts along both sides (lit as the village grows)
pier = dock_basic(A_PIER, 9.0, 2.4, 0.62, lanterns_every=2.4, post_every=3.0)
pier['name'] = 'VILLAGE PIER'


# The Lily Dock: a short dock with a bench and a little roof
def lily_extra(length, width, y):
    f = []
    # bench at the end, facing out
    z = 1.7
    f += box_faces(-0.6, y + 0.35, z - 0.15, 0.6, y + 0.42, z + 0.15, 'planks', base=0.95, lod=False)
    for sx in (-0.5, 0.5):
        f += box_faces(sx - 0.05, y, z - 0.1, sx + 0.05, y + 0.35, z + 0.1, 'log', top=False, lod=False)
    # posts and a small gable roof over the end
    for sx in (-1, 1):
        for zz in (0.6, 2.8):
            f += box_faces(sx * (width / 2 - 0.05) - 0.06, y, zz - 0.06, sx * (width / 2 - 0.05) + 0.06, y + 2.2, zz + 0.06, 'log', top=False, lod=False)
    ry = y + 2.2
    w2 = width / 2 + 0.25
    z0, z1 = 0.2, 3.2
    for sx in (-1, 1):
        n = norm((sx * 0.6, 1, 0))
        f.append(Face([(sx * w2, ry, z0), (0, ry + 0.7, z0), (sx * w2, ry, z1), (0, ry + 0.7, z1)],
                      cell_uv('roofb'), [lit_tint(n)] * 4, 'roofb', n))
        f.append(Face([(sx * w2, ry - 0.02, z0), (0, ry + 0.68, z0), (sx * w2, ry - 0.02, z1), (0, ry + 0.68, z1)],
                      cell_uv('roofb'), [lit_tint((0, -1, 0), 0.6)] * 4, 'roofb', (-n[0], -n[1], 0)))
    return f, [(0.0, y + 2.0, 1.7)]


lily = dock_basic(A_LILY, 6.0, 1.9, 0.5, extra=lily_extra)
lily['faces'] += []
lily['name'] = 'LILY DOCK'


# The Reedy Cove: a short, rickety dock and a moored rowboat
def reed_extra(length, width, y):
    f = []
    # rowboat moored beside the dock (local +x side)
    bx, bz = width / 2 + 0.9, length - 1.6
    L, W, H = 2.6, 0.9, 0.35
    pts = lambda sx, z, yy: (bx + sx, yy, bz + z)
    for sx in (-1, 1):
        n = (sx, 0.3, 0)
        f.append(Face([pts(sx * W / 2 * 0.7, -L / 2, 0.02), pts(sx * W / 2 * 0.7, L / 2, 0.02),
                       pts(sx * W / 2, -L / 2, H), pts(sx * W / 2, L / 2, H)], plank_uv(), [lit_tint(n, 0.8)] * 4,
                      'planks', n, flags=DOUBLE))
    for sz in (-1, 1):
        n = (0, 0.3, sz)
        f.append(Face([pts(-W / 2 * 0.7, sz * L / 2, 0.02), pts(W / 2 * 0.7, sz * L / 2, 0.02),
                       pts(-W / 2 * 0.2, sz * (L / 2 + 0.3), H + 0.05), pts(W / 2 * 0.2, sz * (L / 2 + 0.3), H + 0.05)],
                      plank_uv(), [lit_tint(n, 0.8)] * 4, 'planks', n, flags=DOUBLE))
    f.append(Face([pts(-W / 2 * 0.7, -L / 2, 0.06), pts(W / 2 * 0.7, -L / 2, 0.06), pts(-W / 2 * 0.7, L / 2, 0.06),
                   pts(W / 2 * 0.7, L / 2, 0.06)], plank_uv(), [lit_tint((0, 1, 0), 0.7)] * 4, 'planks', (0, 1, 0)))
    f += box_faces(bx - W / 2 + 0.05, 0.2, bz - 0.15, bx + W / 2 - 0.05, 0.27, bz + 0.15, 'planks')
    # mooring rope post
    f += box_faces(width / 2 - 0.15, y, bz - 0.08, width / 2 - 0.0, y + 0.5, bz + 0.08, 'log')
    return f, []


reedy = dock_basic(A_REEDS, 5.0, 1.6, 0.45, extra=reed_extra, wob=0.05, post_every=1.6)
reedy['name'] = 'REEDY COVE'

# The Old Bridge: a stone and timber bridge across the north inlet; stand mid-span, face south
Rb = shore_r(A_BRIDGE + 0.3) + 1.0
bz = 26.5 + 4.0
bridge_faces = []
span = 10.0
BY = 1.35
# stone piers in the water and abutments
for px in (-span / 2 - 0.5, -1.6, 1.6, span / 2 + 0.5):
    bridge_faces += box_faces(px - 0.45, -0.2, bz - 1.4, px + 0.45, BY - 0.15, bz + 1.4, 'stone', top=False)
# deck: stone top along x, segmented (near); one piece each in the far version
nseg = 5
for s_ in range(nseg):
    x0 = -span / 2 - 1.0 + (span + 2.0) * s_ / nseg
    x1 = -span / 2 - 1.0 + (span + 2.0) * (s_ + 1) / nseg
    bridge_faces.append(Face([(x0, BY, bz - 1.3), (x1, BY, bz - 1.3), (x0, BY, bz + 1.3), (x1, BY, bz + 1.3)],
                             cell_uv('planks'), [lit_tint((0, 1, 0))] * 4, 'planks', (0, 1, 0), lo=False))
    for sz in (-1, 1):
        z = bz + sz * 1.3
        bridge_faces.append(Face([(x0, BY - 0.35, z), (x1, BY - 0.35, z), (x0, BY, z), (x1, BY, z)],
                                 cell_uv('stone'), [lit_tint((0, 0, sz), 0.7)] * 2 + [lit_tint((0, 0, sz))] * 2,
                                 'stone', (0, 0, sz), lo=False))
        bridge_faces += box_faces(x0, BY, z - 0.12 if sz > 0 else z, x1, BY + 0.55, z if sz > 0 else z + 0.12, 'stone',
                                  sides='ns', base=0.95, lod=False)
x0, x1 = -span / 2 - 1.0, span / 2 + 1.0
bridge_faces.append(Face([(x0, BY, bz - 1.3), (x1, BY, bz - 1.3), (x0, BY, bz + 1.3), (x1, BY, bz + 1.3)],
                         cell_uv('planks'), [lit_tint((0, 1, 0))] * 4, 'planks', (0, 1, 0), hi=False))
for sz in (-1, 1):
    z = bz + sz * 1.3
    bridge_faces.append(Face([(x0, BY - 0.35, z), (x1, BY - 0.35, z), (x0, BY, z), (x1, BY, z)],
                             cell_uv('stone'), [lit_tint((0, 0, sz), 0.7)] * 2 + [lit_tint((0, 0, sz))] * 2,
                             'stone', (0, 0, sz), hi=False))
    for f_ in box_faces(x0, BY, z - 0.12 if sz > 0 else z, x1, BY + 0.55, z if sz > 0 else z + 0.12, 'stone',
                        sides='ns', base=0.95):
        f_.hi = False
        bridge_faces.append(f_)
bl = []
for lx in (-span / 2 - 0.6, span / 2 + 0.6):
    lf, lp = lantern_post(lx, bz - 1.25, BY, h=1.6)
    bridge_faces += lf
    bl.append(lp)
bridge = dict(name='OLD BRIDGE', stand=(0.0, BY, bz - 0.4), yaw=math.pi, faces=bridge_faces, lanterns=bl,
              base=(0, 0, bz))

DOCK_LIST = [pier, lily, bridge, reedy]

# reeds: clusters of crossed alpha quads, around the Reedy Cove and the river mouth
reed_faces = []


def reed_clump(x, z, h=1.6, w=1.4, yaw=0.0):
    out = []
    M = MATS['reeds']
    for k in range(2):
        a = yaw + k * math.pi / 2
        dx, dz = math.cos(a) * w / 2, -math.sin(a) * w / 2
        pts = [(x - dx, -0.05, z - dz), (x + dx, -0.05, z + dz), (x - dx, h, z - dz), (x + dx, h, z + dz)]
        n = (math.sin(a), 0, math.cos(a))
        out.append(Face(pts, [(M['u'], M['v'] + 31), (M['u'] + 31, M['v'] + 31), (M['u'], M['v']), (M['u'] + 31, M['v'])],
                        [lit_tint((0, 0.4, 0), 0.8)] * 2 + [lit_tint((0, 1, 0), 1.05)] * 2, 'reeds', n, flags=DOUBLE))
    return out


REED_SPOTS = []
for k in range(17):
    a = A_REEDS + rng.uniform(-0.65, 0.5)
    if abs(angdiff(a, A_REEDS)) < 0.06:
        continue
    R = shore_r(a)
    r = R - rng.uniform(0.3, 3.5)
    p = apos(a, r)
    REED_SPOTS.append(p)
    reed_faces += reed_clump(p[0], p[2], rng.uniform(1.2, 2.1), rng.uniform(1.0, 1.8), rng.uniform(0, 3))
for k in range(8):   # a few at the other docks, near the shore
    a = rng.choice([A_LILY - 0.5, A_LILY + 0.6, A_PIER - 0.35, A_PIER + 0.45, A_BRIDGE - 0.4, A_BRIDGE + 0.45])
    a += rng.uniform(-0.08, 0.08)
    p = apos(a, shore_r(a) - rng.uniform(0.3, 1.5))
    reed_faces += reed_clump(p[0], p[2], rng.uniform(1.0, 1.6), rng.uniform(0.9, 1.4), rng.uniform(0, 3))

# reed meshes by sector (4) for culling
reed_groups = [[] for _ in range(4)]
reed_gpts = [[] for _ in range(4)]
for fc in range(0, len(reed_faces), 2):
    p = reed_faces[fc].pts[0]
    g = min(range(4), key=lambda k: (p[0] - DOCK_LIST[k]['stand'][0]) ** 2 + (p[2] - DOCK_LIST[k]['stand'][2]) ** 2)
    reed_groups[g] += reed_faces[fc:fc + 2]
    reed_gpts[g].append(p)
REED_C = []
for g in range(4):
    pts = np.array(reed_gpts[g] or [(0, 0, 0)])
    c = pts.mean(axis=0)
    REED_C.append((tuple(c), float(np.sqrt(((pts - c) ** 2).sum(axis=1)).max()) + 1.5))

# lily pads: flat quads on the water (not reflected), with some flowers
lily_faces = []
LILY_SPOTS = []
for k in range(34):
    a = A_LILY + rng.uniform(-0.75, 0.7)
    R = shore_r(a)
    r = R - rng.uniform(1.0, 9.0)
    p = apos(a, r, 0.02)
    if math.hypot(p[0] - lily['stand'][0], p[2] - lily['stand'][2]) < 2.5:
        continue
    LILY_SPOTS.append(p)
    s = rng.uniform(0.5, 1.0)
    rot = rng.uniform(0, 2 * math.pi)
    cs, sn = math.cos(rot) * s, math.sin(rot) * s
    pts = [(p[0] - cs + sn, 0.02, p[2] - sn - cs), (p[0] + cs + sn, 0.02, p[2] + sn - cs),
           (p[0] - cs - sn, 0.02, p[2] - sn + cs), (p[0] + cs - sn, 0.02, p[2] + sn + cs)]
    lily_faces.append(Face(pts, cell_uv('lily'), [lit_tint((0, 1, 0), 0.95)] * 4, 'lily', (0, 1, 0), refl=False))
    if rng.random() < 0.3:
        fu, fv, fw, fh = UV['lilyflower']
        q = 0.32
        fp = (p[0] + rng.uniform(-0.2, 0.2), 0.12, p[2] + rng.uniform(-0.2, 0.2))
        for kk in range(2):
            ang = kk * math.pi / 2 + rot
            dx, dz = math.cos(ang) * q, -math.sin(ang) * q
            pts = [(fp[0] - dx, 0.02, fp[2] - dz), (fp[0] + dx, 0.02, fp[2] + dz), (fp[0] - dx, 0.3, fp[2] - dz),
                   (fp[0] + dx, 0.3, fp[2] + dz)]
            lily_faces.append(Face(pts, [(fu, fv + 15), (fu + 15, fv + 15), (fu, fv + 7), (fu + 15, fv + 7)],
                                   [lit_tint((0, 1, 0))] * 4, 'lily', (math.sin(ang), 0, math.cos(ang)), flags=DOUBLE,
                                   refl=False))
write('lilies.bin', emit(lily_faces).pack())

# ---- the village on the south-east bank: houses (each with its own wall palette), the
# festival hall and lantern garlands
village_faces = {i: [] for i in range(NHOUSE)}
HOUSES = []


def house(i, a, roff, w, d, h, yaw_off=0.0, timber=False, stilts=False, roofmat='roof'):
    R = shore_r(a)
    c = apos(a, R + roff)
    gy = 0.45 if not stilts else 0.5
    yaw = math.atan2(-c[0], -c[2]) + yaw_off
    mat = 'house%d' % i
    f = []
    x0, x1, z0, z1 = -w / 2, w / 2, -d / 2, d / 2
    y0, y1 = (-0.3 if not stilts else 0.35), gy + h
    M = MATS['wall_dark']
    wuv = [(M['u'], M['v'] + 31), (M['u'] + 31, M['v'] + 31), (M['u'], M['v']), (M['u'] + 31, M['v'])]
    # walls, split into window-sized panels along the long sides
    for side, n, (pa, pb) in (('s', (0, 0, 1), ((x1, z1), (x0, z1))), ('n', (0, 0, -1), ((x0, z0), (x1, z0))),
                              ('e', (1, 0, 0), ((x1, z0), (x1, z1))), ('w', (-1, 0, 0), ((x0, z1), (x0, z0)))):
        L = math.hypot(pb[0] - pa[0], pb[1] - pa[1])
        nseg = max(1, int(round(L / 1.6)))
        lo = lit_tint(n, 0.7)
        hi = lit_tint(n, 1.0)
        for s_ in range(nseg):
            t0, t1 = s_ / nseg, (s_ + 1) / nseg
            qa = (pa[0] + (pb[0] - pa[0]) * t0, pa[1] + (pb[1] - pa[1]) * t0)
            qb = (pa[0] + (pb[0] - pa[0]) * t1, pa[1] + (pb[1] - pa[1]) * t1)
            f.append(Face([(qa[0], y0, qa[1]), (qb[0], y0, qb[1]), (qa[0], y1, qa[1]), (qb[0], y1, qb[1])], wuv,
                          [lo, lo, hi, hi], mat, n, lo=(nseg == 1)))
        if nseg > 1:
            f.append(Face([(pa[0], y0, pa[1]), (pb[0], y0, pb[1]), (pa[0], y1, pa[1]), (pb[0], y1, pb[1])], wuv,
                          [lo, lo, hi, hi], mat, n, hi=False))
    # gable roof along x
    rh = h * 0.55
    ov = 0.3
    for sz in (-1, 1):
        n = norm((0, 1, sz * 0.8))
        zz = sz * (d / 2 + ov)
        f.append(Face([(x0 - ov, y1 - 0.1, zz), (x1 + ov, y1 - 0.1, zz), (x0 - ov, y1 + rh, 0), (x1 + ov, y1 + rh, 0)],
                      cell_uv(roofmat), [lit_tint(n, 0.95)] * 4, roofmat, n))
        f.append(Face([(x0 - ov, y1 - 0.12, zz), (x1 + ov, y1 - 0.12, zz), (x0 - ov, y1 + rh - 0.02, 0),
                       (x1 + ov, y1 + rh - 0.02, 0)], cell_uv(roofmat), [lit_tint((0, -1, 0), 0.5)] * 4, roofmat,
                      (0, -n[1], -n[2])))
    for sx in (-1, 1):   # gable ends (triangles, wall material)
        n = (sx, 0, 0)
        xx = x0 if sx < 0 else x1
        f.append(Face([(xx, y1, -d / 2), (xx, y1, d / 2), (xx, y1 + rh * 0.9, 0)],
                      [(M['u'], M['v'] + 31), (M['u'] + 31, M['v'] + 31), (M['u'] + 16, M['v'] + 20)],
                      [lit_tint(n)] * 3, mat, n))
    if stilts:
        for sx in (x0 + 0.15, x1 - 0.15):
            for sz in (z0 + 0.15, z1 - 0.15):
                f += box_faces(sx - 0.08, -0.1, sz - 0.08, sx + 0.08, 0.36, sz + 0.08, 'log', top=False)
    faces = transform(f, yaw, (c[0], 0, c[2]))
    village_faces[i] += faces
    HOUSES.append(dict(i=i, pos=c, yaw=yaw, w=w, h=h))
    return c


VILLAGE_SPEC = [  # a, roff, w, d, h, timber, stilts, roof, yaw_off
    (2.86, 1.6, 2.6, 2.0, 1.6, False, True, 'roof', 0.15),
    (2.72, 3.4, 3.2, 2.4, 2.0, True, False, 'roofb', -0.1),
    (2.58, 1.8, 2.4, 2.0, 1.5, False, True, 'roof', 0.2),
    (2.46, 4.6, 3.6, 2.8, 2.4, True, False, 'roof', 0.0),
    (2.33, 2.4, 2.6, 2.2, 1.7, False, False, 'roofb', -0.25),
    (2.62, 7.2, 3.0, 2.4, 2.2, False, False, 'roof', 0.05),
    (2.21, 4.8, 2.8, 2.2, 1.8, True, False, 'roof', 0.3),      # 6: built after festival 2
    (2.98, 5.2, 4.4, 3.0, 2.9, True, False, 'roofb', -0.05),   # 7: the festival hall (fest 4)
]
for i, (a, roff, w, d, h, tim, st, rm, yo) in enumerate(VILLAGE_SPEC):
    house(i, a, roff, w, d, h, yo, tim, st, rm)
    DEST[PALNUM['house%d' % i]] = 'timber_dark' if tim else 'wall_dark'
# festival hall: a lantern tower roof spire on top
hall = HOUSES[7]
hc = hall['pos']
village_faces[7] += box_faces(hc[0] - 0.3, 2.9, hc[2] - 0.3, hc[0] + 0.3, 5.2, hc[2] + 0.3, 'log')
village_faces[7] += sw_box(hc[0] - 0.42, 4.6, hc[2] - 0.42, hc[0] + 0.42, 5.3, hc[2] + 0.42, 15)
village_faces[7] += box_faces(hc[0] - 0.6, 5.3, hc[2] - 0.6, hc[0] + 0.6, 5.45, hc[2] + 0.6, 'roof')
for i in range(NHOUSE):
    write('house%d.bin' % i, emit(village_faces[i]).pack())
    write('house%d_r.bin' % i, emit(village_faces[i], mirror=True, lo=True).pack())
    write('house%d_lo.bin' % i, emit(village_faces[i], lo=True).pack())
VILLAGE_LANTERNS = [(hc[0], 4.95, hc[2])]

# garlands: strings of little lanterns between houses (each with the village level it needs)
GARLANDS = []


def garland(p0, p1, y0, y1, n, level):
    for k in range(n):
        t = (k + 0.5) / n
        x = p0[0] + (p1[0] - p0[0]) * t
        z = p0[2] + (p1[2] - p0[2]) * t
        y = y0 + (y1 - y0) * t - 0.5 * math.sin(math.pi * t)
        GARLANDS.append((x, y, z, level))


hp = [h['pos'] for h in HOUSES]
garland(hp[0], hp[1], 2.0, 2.4, 5, 1)
garland(hp[1], hp[3], 2.4, 2.8, 6, 1)
garland(hp[2], hp[4], 2.0, 2.2, 5, 2)
garland(hp[3], hp[5], 2.8, 2.6, 6, 2)
garland(hp[4], hp[6], 2.2, 2.3, 5, 3)
garland(hp[0], hp[7], 2.0, 3.5, 6, 3)
garland(hp[7], hp[5], 3.5, 2.6, 7, 4)
garland(hp[3], hp[6], 2.8, 2.3, 6, 4)
garland(hp[1], hp[7], 2.4, 3.5, 6, 5)

# docks: meshes and reflections
for k, dk in enumerate(DOCK_LIST):
    write('dock%d.bin' % k, emit(dk['faces']).pack())
    write('dock%d_lo.bin' % k, emit(dk['faces'], lo=True).pack())
    write('dock%d_r.bin' % k, emit(dk['faces'], mirror=True, lo=True).pack())
for g in range(4):
    write('reeds%d.bin' % g, emit(reed_groups[g]).pack())
    write('reeds%d_r.bin' % g, emit(reed_groups[g], mirror=True).pack())

# the first-person hand: glove, thumb, cork grip, reel and sleeve, in "hand space" (origin
# at the hand, +z along the rod, +y up); the cart places it in camera space each frame
hand = []
hand += sw_box(-0.03, -0.054, -0.07, 0.05, 0.018, 0.03, 6)          # glove
hand += sw_box(-0.014, -0.012, -0.22, 0.014, 0.012, 0.05, 13)       # cork grip
hand += sw_box(-0.022, -0.064, 0.11, 0.022, -0.016, 0.146, 9)       # reel
hand += sw_box(-0.02, -0.125, -0.26, 0.1, -0.015, -0.05, 1)         # sleeve
write('hand.bin', emit(hand).pack())

# bobber: a small red/white diamond
bob = []
for k in range(4):
    a0 = k * math.pi / 2
    a1 = (k + 1) * math.pi / 2
    p0 = (0.11 * math.sin(a0), 0.0, 0.11 * math.cos(a0))
    p1 = (0.11 * math.sin(a1), 0.0, 0.11 * math.cos(a1))
    n = norm((math.sin(a0 + math.pi / 4), 0.7, math.cos(a0 + math.pi / 4)))
    bob.append(Face([p0, p1, (0, 0.2, 0)], sw_uv(8)[:3], [lit_tint(n, 1.1)] * 3, 'swatch', n))
    n2 = (n[0], -n[1], n[2])
    bob.append(Face([p0, p1, (0, -0.12, 0)], sw_uv(9)[:3], [lit_tint(n2, 0.9)] * 3, 'swatch', n2))
    bob.append(Face([(0.0, 0.2, 0.0), (0.0, 0.2, 0.0), (0.0, 0.3, 0.0)], sw_uv(10)[:3], [0x606060] * 3, 'swatch', n))
bob = [f for f in bob if len(set(f.pts)) == len(f.pts)]
write('bobber.bin', emit(bob).pack())

# ----------------------------------------------------------------------------- fish (slot 1)
# Each species is one 64x32 side view (facing left). Index plan:
# 1 outline, 2-6 back->flank shades, 7-8 belly, 9-10 markings, 11-12 fins, 13 eye white,
# 14 pupil, 15 glint. Day and night forms share the texture and differ only in palette.
SPECIES = [
    # name, night name, shape, markings, day colours, night colours
    dict(key='perch', shape=dict(L=0.78, H=0.42, tail=0.28, dorsal='spiny', snout=0.5),
         marks='bars',
         day=dict(back=(70, 86, 30), flank=(214, 176, 46), belly=(246, 226, 160), mark=(60, 70, 24), fin=(230, 104, 40)),
         night=dict(back=(36, 46, 92), flank=(150, 176, 224), belly=(226, 230, 250), mark=(30, 34, 80), fin=(90, 200, 210))),
    dict(key='pike', shape=dict(L=0.96, H=0.24, tail=0.22, dorsal='rear', snout=0.9),
         marks='spots',
         day=dict(back=(40, 70, 36), flank=(96, 140, 60), belly=(224, 226, 170), mark=(220, 220, 120), fin=(140, 120, 50)),
         night=dict(back=(70, 64, 100), flank=(196, 190, 226), belly=(244, 244, 252), mark=(140, 230, 240), fin=(170, 170, 210))),
    dict(key='carp', shape=dict(L=0.86, H=0.46, tail=0.3, dorsal='long', snout=0.35),
         marks='scales',
         day=dict(back=(100, 70, 30), flank=(200, 150, 60), belly=(240, 220, 160), mark=(150, 100, 40), fin=(220, 140, 60)),
         night=dict(back=(60, 30, 80), flank=(200, 96, 140), belly=(250, 200, 180), mark=(120, 50, 100), fin=(230, 130, 150))),
    dict(key='catfish', shape=dict(L=0.94, H=0.32, tail=0.26, dorsal='small', snout=0.2, whiskers=True),
         marks='mottle',
         day=dict(back=(54, 46, 40), flank=(120, 106, 90), belly=(200, 194, 180), mark=(70, 60, 52), fin=(80, 70, 60)),
         night=dict(back=(16, 30, 54), flank=(30, 84, 96), belly=(110, 150, 150), mark=(255, 220, 90), fin=(24, 60, 80))),
    dict(key='trout', shape=dict(L=0.86, H=0.34, tail=0.27, dorsal='mid', snout=0.55),
         marks='band',
         day=dict(back=(70, 90, 50), flank=(210, 200, 180), belly=(250, 246, 236), mark=(230, 110, 120), fin=(160, 140, 100)),
         night=dict(back=(50, 80, 120), flank=(200, 226, 240), belly=(255, 255, 255), mark=(110, 220, 250), fin=(150, 190, 220))),
    dict(key='bream', shape=dict(L=0.74, H=0.52, tail=0.27, dorsal='tall', snout=0.4),
         marks='sheen',
         day=dict(back=(90, 90, 70), flank=(196, 186, 150), belly=(236, 230, 210), mark=(240, 236, 220), fin=(130, 120, 100)),
         night=dict(back=(110, 60, 20), flank=(250, 170, 70), belly=(255, 230, 160), mark=(255, 250, 200), fin=(230, 120, 50))),
    dict(key='koi', shape=dict(L=0.84, H=0.42, tail=0.32, dorsal='long', snout=0.35, whiskers=True),
         marks='patches',
         day=dict(back=(200, 130, 20), flank=(250, 196, 50), belly=(255, 240, 180), mark=(255, 250, 240), fin=(255, 170, 60)),
         night=dict(back=(130, 140, 170), flank=(220, 226, 240), belly=(255, 255, 255), mark=(150, 190, 250), fin=(190, 210, 250))),
]
NSPEC = len(SPECIES)


def fish_image(sp, seed):
    """Renders a 64x32 index image (fish facing left)."""
    S = 8
    W, H = 64 * S, 32 * S
    sh = sp['shape']
    L = sh['L'] * W * 0.86
    Hh = sh['H'] * H
    x0 = W * 0.06
    cy = H * 0.5
    mask = Image.new('L', (W, H), 0)
    fins = Image.new('L', (W, H), 0)
    dm = ImageDraw.Draw(mask)
    df = ImageDraw.Draw(fins)
    body_len = L * (1 - sh['tail'] * 0.6)
    top, bot = [], []
    for k in range(65):
        t = k / 64
        # thickness profile: blunt head, taper to the tail stalk
        prof = (math.sin(math.pi * min(1, t * 1.15) ** (0.6 + sh['snout'] * 0.5)) ** 0.8)
        prof = max(prof, 0.18 if t > 0.8 else 0)
        x = x0 + t * body_len
        top.append((x, cy - Hh * 0.5 * prof * 1.05))
        bot.append((x, cy + Hh * 0.5 * prof * 0.95))
    dm.polygon(top + bot[::-1], fill=255)
    tx = x0 + body_len - 4 * S
    tl = sh['tail'] * W * 0.42
    df.polygon([(tx, cy - 2 * S), (tx + tl, cy - Hh * 0.62), (tx + tl * 0.72, cy), (tx + tl, cy + Hh * 0.62), (tx, cy + 2 * S)], fill=255)
    d = sh['dorsal']
    if d == 'spiny':
        df.polygon([(x0 + body_len * 0.3, cy - Hh * 0.42), (x0 + body_len * 0.38, cy - Hh * 0.82), (x0 + body_len * 0.5, cy - Hh * 0.75),
                    (x0 + body_len * 0.62, cy - Hh * 0.8), (x0 + body_len * 0.75, cy - Hh * 0.38)], fill=255)
    elif d == 'rear':
        df.polygon([(x0 + body_len * 0.7, cy - Hh * 0.35), (x0 + body_len * 0.82, cy - Hh * 0.9), (x0 + body_len * 0.92, cy - Hh * 0.3)], fill=255)
        df.polygon([(x0 + body_len * 0.72, cy + Hh * 0.35), (x0 + body_len * 0.84, cy + Hh * 0.85), (x0 + body_len * 0.93, cy + Hh * 0.3)], fill=255)
    elif d == 'long':
        df.polygon([(x0 + body_len * 0.35, cy - Hh * 0.45), (x0 + body_len * 0.45, cy - Hh * 0.72), (x0 + body_len * 0.85, cy - Hh * 0.5),
                    (x0 + body_len * 0.9, cy - Hh * 0.25)], fill=255)
    elif d == 'tall':
        df.polygon([(x0 + body_len * 0.42, cy - Hh * 0.45), (x0 + body_len * 0.5, cy - Hh * 0.95), (x0 + body_len * 0.66, cy - Hh * 0.4)], fill=255)
        df.polygon([(x0 + body_len * 0.55, cy + Hh * 0.4), (x0 + body_len * 0.66, cy + Hh * 0.8), (x0 + body_len * 0.86, cy + Hh * 0.3)], fill=255)
    elif d == 'mid':
        df.polygon([(x0 + body_len * 0.42, cy - Hh * 0.42), (x0 + body_len * 0.5, cy - Hh * 0.82), (x0 + body_len * 0.62, cy - Hh * 0.4)], fill=255)
        df.polygon([(x0 + body_len * 0.8, cy - Hh * 0.28), (x0 + body_len * 0.84, cy - Hh * 0.5), (x0 + body_len * 0.88, cy - Hh * 0.25)], fill=255)
    else:
        df.polygon([(x0 + body_len * 0.36, cy - Hh * 0.4), (x0 + body_len * 0.42, cy - Hh * 0.7), (x0 + body_len * 0.5, cy - Hh * 0.38)], fill=255)
    # pectoral and pelvic fins
    df.polygon([(x0 + body_len * 0.28, cy + Hh * 0.1), (x0 + body_len * 0.42, cy + Hh * 0.38), (x0 + body_len * 0.36, cy + Hh * 0.08)], fill=255)
    df.polygon([(x0 + body_len * 0.45, cy + Hh * 0.4), (x0 + body_len * 0.52, cy + Hh * 0.7), (x0 + body_len * 0.58, cy + Hh * 0.4)], fill=255)
    if sh.get('whiskers'):
        for k in (-1, 1):
            df.line([(x0 + 3 * S, cy + 1 * S), (x0 - 1 * S, cy + (6 + 4 * k) * S)], fill=255, width=S)
    small = lambda im: np.asarray(im.resize((64, 32), Image.BOX), np.float32) / 255
    mb = small(mask)
    mf = small(fins)
    # shading: vertical position within the body
    ys = (np.arange(32)[:, None] + 0.5 - 16) / (Hh / S * 0.5 + 1e-6)
    xs_ = (np.arange(64)[None, :] + 0.5 - x0 / S) / (body_len / S)
    r = np.random.default_rng(seed)
    idx = np.zeros((32, 64), np.uint8)
    body = mb > 0.45
    fin = (mf > 0.45) & ~body
    shade = np.broadcast_to(np.clip((ys + 1) / 2, 0, 1), (32, 64))   # 0 top .. 1 bottom
    xs_ = np.broadcast_to(xs_, (32, 64))
    lvl = np.clip((shade * 6.2).astype(int), 0, 6)
    tbl = np.array([2, 3, 4, 5, 6, 7, 8], np.uint8)
    idx[body] = tbl[lvl[body]]
    m = sp['marks']
    if m == 'bars':
        bars = (np.sin(xs_ * 2 * math.pi * 3.5) > 0.45) & (shade < 0.75)
        idx[body & bars] = 9
    elif m == 'spots':
        sp_ = value_noise(64, 32, 16, 8, seed + 3) > 0.68
        idx[body & sp_ & (shade < 0.8)] = 9
    elif m == 'scales':
        sc = ((np.arange(64)[None, :] + (np.arange(32)[:, None] // 3) * 2) % 4 == 0) & ((np.arange(32)[:, None]) % 3 == 0)
        idx[body & sc & (shade < 0.8)] = 9
    elif m == 'mottle':
        mt = value_noise(64, 32, 12, 6, seed + 5) > 0.6
        idx[body & mt & (shade < 0.55)] = 1
        dots = value_noise(64, 32, 24, 12, seed + 6) > 0.8
        idx[body & dots & (shade > 0.3) & (shade < 0.75)] = 9
    elif m == 'band':
        band = (np.abs(shade - 0.5) < 0.1) & (xs_ > 0.15) & (xs_ < 0.92)
        idx[body & band] = 9
        dots = value_noise(64, 32, 20, 10, seed + 7) > 0.74
        idx[body & dots & (shade < 0.45)] = 1
    elif m == 'sheen':
        sh_ = (np.sin(xs_ * 9 + shade * 3) > 0.7) & (shade > 0.25) & (shade < 0.65)
        idx[body & sh_] = 10
    elif m == 'patches':
        pt = value_noise(64, 32, 5, 3, seed + 9) > 0.55
        idx[body & pt & (shade < 0.85)] = 10
    idx[fin] = np.where(mf[fin] > 0.75, 11, 12)
    # outline: transparent neighbour
    solid = idx > 0
    edge = solid & ~(np.roll(solid, 1, 0) & np.roll(solid, -1, 0) & np.roll(solid, 1, 1) & np.roll(solid, -1, 1))
    idx[edge & body] = 1
    # gill line and eye
    gx = int(x0 / S + body_len / S * 0.24)
    for y in range(32):
        if body[y, gx] and abs(y - 16) < Hh / S * 0.32:
            idx[y, gx] = 1
    ex = int(x0 / S + body_len / S * 0.11) + 1
    ey = int(16 - Hh / S * 0.1)
    idx[ey - 1:ey + 2, ex - 1:ex + 2] = 13
    idx[ey, ex] = 14
    idx[ey - 1, ex - 1] = 15
    return idx


def fish_pal(c):
    back, flank, belly, mark, fin = c['back'], c['flank'], c['belly'], c['mark'], c['fin']
    sh = [lerp3(back, flank, t) for t in (0.0, 0.35, 0.7, 1.0)] + [lerp3(flank, belly, 0.4)]
    outline = tuple(v * 0.35 for v in back)
    return [outline] + sh + [lerp3(flank, belly, 0.75), belly, mark, lerp3(mark, (255, 255, 255), 0.5),
                             fin, lerp3(fin, back, 0.45), (250, 250, 240), (16, 16, 24), (255, 255, 255)]


FISH_UV = []
FISH_PAL = []      # (day palette, night palette)
for s, sp in enumerate(SPECIES):
    u = (s % 4) * 64
    v = (s // 4) * 32
    A1.put(u, v, fish_image(sp, 300 + s))
    FISH_UV.append((u, v))
    pd = stat_pal(fish_pal(sp['day']))
    pn = stat_pal(fish_pal(sp['night']))
    FISH_PAL.append((pd, pn))
SIL_PAL = stat_pal([(40, 44, 76)] * 15)
SIL_PAL2 = stat_pal([(70, 74, 110)] + [(36, 40, 70)] * 14)

# ---- 3D fish: a lofted body whose side profile is the texture's outline, so the side view
# maps straight onto the 64x32 texture (both flanks share it). Fins, tail and whiskers are
# "cards" in the fish's middle plane that show the texture's fin texels (index 0 is never
# drawn, so the cards take the fins' shapes). Model space: nose toward +z, the body 1 unit
# long from z = +0.5 to -0.5, the tail beyond; y up. The night twin is the same mesh drawn
# with the night palette (the cart patches the palette in a RAM copy).
THICK = dict(perch=0.42, pike=0.55, carp=0.5, catfish=0.9, trout=0.5, bream=0.28, koi=0.55)
FISH_LIGHT = norm((0.45, 0.8, 0.35))


def fish_tint(n, k=1.0):
    d = max(0.0, dot(n, FISH_LIGHT))
    v = 128 * (0.5 + 0.62 * d) * k
    return rgbw(v, v, v)


def fish_model(si, sp):
    sh = sp['shape']
    u0, v0 = FISH_UV[si]
    x0 = 64 * 0.06
    body_px = sh['L'] * 64 * 0.86 * (1 - sh['tail'] * 0.6)
    Hh = sh['H'] * 32
    thick = THICK[sp['key']]

    def prof(t):
        p_ = math.sin(math.pi * min(1, t * 1.15) ** (0.6 + sh['snout'] * 0.5)) ** 0.8
        return max(p_, 0.18 if t > 0.8 else 0)

    def to_uv(z, y):
        px = x0 + (0.5 - z) * body_px
        py = 16 - y * body_px
        return (int(round(min(max(px, 0), 63))) + u0, int(round(min(max(py, 0), 31))) + v0)

    pal = (1, True, FISH_PAL[si][0])
    T = [0.0, 0.05, 0.13, 0.25, 0.4, 0.55, 0.7, 0.84, 1.0]
    NS = 6
    rings = []
    for t in T:
        pr = prof(t)
        yt = Hh * 0.5 * pr * 1.05 / body_px
        yb = -Hh * 0.5 * pr * 0.95 / body_px
        yc = (yt + yb) / 2
        hh = (yt - yb) / 2
        hw = hh * thick
        z = 0.5 - t
        ring = []
        for k in range(NS):
            ang = 2 * math.pi * k / NS
            ring.append((hw * math.sin(ang), yc + hh * math.cos(ang), z))
        rings.append((ring, yc, hh, hw, z))
    faces = []
    nose = (0.0, rings[1][1] - 0.01, 0.52)
    for i in range(len(T) - 1):
        ra, rb = rings[i][0], rings[i + 1][0]
        for k in range(NS):
            k1 = (k + 1) % NS
            a0, a1, b0, b1 = ra[k], ra[k1], rb[k], rb[k1]
            mid = tuple((a0[j] + a1[j] + b0[j] + b1[j]) / 4 for j in range(3))
            cen = (0.0, rings[i][1], mid[2])
            n = norm(sub(mid, cen))
            cols = [fish_tint(norm(sub(q, (0, rings[i][1], q[2]))) if (abs(q[0]) + abs(q[1] - rings[i][1])) > 1e-6 else (0, 1, 0)) for q in (a0, a1, b0, b1)]
            uvs = [to_uv(q[2], q[1]) for q in (a0, a1, b0, b1)]
            if i == 0:
                faces.append(Face([nose, b0, b1], [to_uv(nose[2], nose[1]), uvs[2], uvs[3]], [cols[0], cols[2], cols[3]], pal, n))
            else:
                faces.append(Face([a0, a1, b0, b1], uvs, cols, pal, n))
    # fin cards in the middle plane, split along the body so they sort with it
    zt_end = 0.5 - (64 - x0) / body_px              # the texture's far edge (tail tip side)
    ztop = 16 / body_px
    cuts = [0.62, 0.25, -0.15, -0.45, zt_end]
    for c in range(len(cuts) - 1):
        za, zb = cuts[c], cuts[c + 1]
        pts = [(0.0, -ztop, za), (0.0, -ztop, zb), (0.0, ztop, za), (0.0, ztop, zb)]
        faces.append(Face(pts, [to_uv(q[2], q[1]) for q in pts], [fish_tint((0.6, 0.6, 0.5), 1.05)] * 4, pal, (1, 0, 0),
                          flags=DOUBLE))
    m = emit(faces)
    write('fish%d.bin' % si, m.pack())
    # the shadow: the body seen from above, widened a little (untextured, subtractive; the
    # cart sets its colour)
    sfaces = []
    W = 1.5
    tail_z = 0.5 - (x0 + body_px + sh['tail'] * 64 * 0.42 * 0.8 - x0) / body_px
    pts = [(rings[i][3] * W + 0.02, rings[i][4]) for i in range(len(T))]
    for i in range(len(T) - 1):
        (wa, za), (wb, zb) = pts[i], pts[i + 1]
        sfaces.append(Face([(-wa, 0, za), (wa, 0, za), (-wb, 0, zb), (wb, 0, zb)], None, [rgbw(60, 56, 44)] * 4,
                           (0, False, 0), (0, 1, 0), flags=SEMI, blend=2))
    wb, zb = pts[-1]
    sfaces.append(Face([(-wb, 0, zb), (wb, 0, zb), (-0.1, 0, tail_z), (0.1, 0, tail_z)], None, [rgbw(60, 56, 44)] * 4,
                       (0, False, 0), (0, 1, 0), flags=SEMI, blend=2))
    write('fishsh%d.bin' % si, emit(sfaces).pack())
    return len(m.faces), len(m.verts), len(sfaces)


FISH_MODEL_STATS = [fish_model(si, sp) for si, sp in enumerate(SPECIES)]
print('fish models (faces, verts, shadow faces):', FISH_MODEL_STATS)

# ---- icons 16x16 at (0..255, 64..95)
ICONS = {}
icon_list = []


def icon(name, fn, cols):
    S = 8
    im = Image.new('RGBA', (16 * S, 16 * S), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    fn(d, S)
    sm = im.resize((16, 16), Image.LANCZOS)
    a = np.asarray(sm, np.float32) / 255
    rgb = a[..., :3] * 255
    idx = np.zeros((16, 16), np.uint8)
    # map each pixel to the nearest palette colour (cols = list of up to 15 colours)
    pal = np.array(cols, np.float32)
    for y in range(16):
        for x in range(16):
            if a[y, x, 3] > 0.45:
                dd = ((pal - rgb[y, x]) ** 2).sum(axis=1)
                idx[y, x] = 1 + int(dd.argmin())
    n = len(icon_list)
    u, v = (n % 16) * 16, 64 + (n // 16) * 16
    A1.put(u, v, idx)
    ICONS[name] = (u, v, stat_pal(cols))
    icon_list.append(name)


def ic_sun(d, S):
    for k in range(8):
        a = k * math.pi / 4
        d.line([(8 * S + 4.5 * S * math.cos(a), 8 * S + 4.5 * S * math.sin(a)),
                (8 * S + 7 * S * math.cos(a), 8 * S + 7 * S * math.sin(a))], fill=(255, 170, 40, 255), width=int(1.6 * S))
    d.ellipse((4 * S, 4 * S, 12 * S, 12 * S), fill=(255, 220, 80, 255), outline=(230, 120, 30, 255), width=S)


def ic_moon(d, S):
    d.ellipse((2 * S, 2 * S, 14 * S, 14 * S), fill=(240, 236, 200, 255))
    d.ellipse((5.5 * S, 0.5 * S, 16.5 * S, 11.5 * S), fill=(0, 0, 0, 0))


def ic_coin(d, S):
    d.ellipse((2 * S, 2 * S, 14 * S, 14 * S), fill=(250, 200, 60, 255), outline=(170, 110, 30, 255), width=S)
    d.rectangle((7 * S, 5 * S, 9 * S, 11 * S), fill=(200, 140, 40, 255))


def ic_lantern(d, S):
    d.rectangle((6 * S, 1 * S, 10 * S, 2.5 * S), fill=(60, 40, 40, 255))
    d.ellipse((2.5 * S, 2.5 * S, 13.5 * S, 13.5 * S), fill=(240, 110, 60, 255), outline=(150, 50, 40, 255), width=S)
    d.ellipse((5 * S, 4.5 * S, 11 * S, 11.5 * S), fill=(255, 220, 140, 255))
    d.rectangle((6 * S, 13.5 * S, 10 * S, 15 * S), fill=(60, 40, 40, 255))


def ic_spoon(d, S):
    d.line([(3 * S, 3 * S), (7 * S, 7 * S)], fill=(160, 160, 170, 255), width=S)
    d.ellipse((6 * S, 6 * S, 14 * S, 12 * S), fill=(220, 220, 230, 255), outline=(120, 120, 140, 255), width=S)
    d.ellipse((12 * S, 11 * S, 15 * S, 14 * S), fill=(200, 60, 50, 255))


def ic_glow(d, S):
    d.ellipse((1 * S, 1 * S, 15 * S, 15 * S), fill=(80, 200, 160, 120))
    d.ellipse((4 * S, 5 * S, 12 * S, 11 * S), fill=(160, 255, 200, 255), outline=(60, 150, 120, 255), width=S)
    d.ellipse((6 * S, 6.5 * S, 8 * S, 8.5 * S), fill=(255, 255, 255, 255))


def ic_float(d, S):
    d.ellipse((4 * S, 2 * S, 12 * S, 9 * S), fill=(210, 50, 44, 255))
    d.ellipse((4 * S, 7 * S, 12 * S, 14 * S), fill=(240, 236, 226, 255))
    d.line([(8 * S, 0), (8 * S, 2 * S)], fill=(40, 40, 46, 255), width=S)
    d.line([(1 * S, 12 * S), (15 * S, 12 * S)], fill=(80, 140, 200, 255), width=S)


def ic_rod(d, S):
    d.line([(2 * S, 14 * S), (14 * S, 2 * S)], fill=(150, 100, 50, 255), width=int(1.5 * S))
    d.ellipse((3 * S, 9 * S, 7 * S, 13 * S), fill=(120, 120, 130, 255))


def ic_reel(d, S):
    d.ellipse((2 * S, 2 * S, 14 * S, 14 * S), fill=(170, 170, 180, 255), outline=(90, 90, 100, 255), width=S)
    d.ellipse((6 * S, 6 * S, 10 * S, 10 * S), fill=(90, 90, 100, 255))
    d.line([(8 * S, 8 * S), (14 * S, 3 * S)], fill=(60, 60, 70, 255), width=S)


def ic_line(d, S):
    for k in range(3):
        d.arc((2 * S + k * S, 2 * S + k * S, 14 * S - k * S, 14 * S - k * S), 0, 300, fill=(220, 230, 250, 255), width=S)


def ic_bait(d, S):
    d.arc((2 * S, 3 * S, 14 * S, 13 * S), 200, 340, fill=(220, 120, 130, 255), width=int(2.4 * S))
    d.arc((4 * S, 6 * S, 12 * S, 15 * S), 20, 160, fill=(200, 100, 110, 255), width=int(2.4 * S))


def ic_lock(d, S):
    d.arc((4 * S, 1 * S, 12 * S, 10 * S), 180, 360, fill=(180, 180, 190, 255), width=int(1.6 * S))
    d.rectangle((3 * S, 7 * S, 13 * S, 15 * S), fill=(200, 160, 60, 255), outline=(120, 90, 30, 255), width=S)


def ic_star(d, S):
    pts = []
    for k in range(10):
        a = -math.pi / 2 + k * math.pi / 5
        r = 7 * S if k % 2 == 0 else 3 * S
        pts.append((8 * S + r * math.cos(a), 8.5 * S + r * math.sin(a)))
    d.polygon(pts, fill=(255, 230, 90, 255), outline=(220, 140, 40, 255))


def ic_dock(d, S):
    d.rectangle((1 * S, 7 * S, 15 * S, 10 * S), fill=(170, 120, 70, 255), outline=(90, 60, 30, 255), width=S)
    for x in (3, 8, 13):
        d.rectangle((x * S - S, 10 * S, x * S + S, 14 * S), fill=(100, 70, 40, 255))


def ic_fish(d, S):
    d.ellipse((2 * S, 5 * S, 12 * S, 11 * S), fill=(120, 170, 220, 255), outline=(50, 80, 120, 255), width=S)
    d.polygon([(11 * S, 8 * S), (15 * S, 4.5 * S), (15 * S, 11.5 * S)], fill=(90, 140, 200, 255))
    d.ellipse((4 * S, 6.5 * S, 6 * S, 8.5 * S), fill=(20, 20, 30, 255))


def ic_check(d, S):
    d.line([(2 * S, 9 * S), (6 * S, 13 * S), (14 * S, 3 * S)], fill=(120, 230, 120, 255), width=int(2.2 * S))


def ic_book(d, S):
    d.rectangle((2 * S, 2 * S, 14 * S, 14 * S), fill=(150, 70, 60, 255), outline=(80, 30, 30, 255), width=S)
    d.rectangle((4 * S, 4 * S, 12 * S, 8 * S), fill=(240, 220, 170, 255))


def ic_arrow(d, S):
    d.polygon([(3 * S, 2 * S), (13 * S, 8 * S), (3 * S, 14 * S)], fill=(255, 240, 200, 255))


COLS_WARM = [(255, 230, 120), (255, 170, 40), (230, 120, 30), (255, 220, 80), (255, 255, 255), (170, 110, 30),
             (200, 140, 40), (250, 200, 60)]
icon('sun', ic_sun, [(255, 220, 80), (255, 170, 40), (230, 120, 30), (255, 250, 200)])
icon('moon', ic_moon, [(240, 236, 200), (200, 200, 170), (255, 255, 240)])
icon('coin', ic_coin, [(250, 200, 60), (170, 110, 30), (200, 140, 40), (255, 240, 160)])
icon('lantern', ic_lantern, [(60, 40, 40), (240, 110, 60), (150, 50, 40), (255, 220, 140), (255, 170, 100)])
icon('spoon', ic_spoon, [(160, 160, 170), (220, 220, 230), (120, 120, 140), (200, 60, 50), (250, 250, 255)])
icon('glow', ic_glow, [(80, 200, 160), (160, 255, 200), (60, 150, 120), (255, 255, 255)])
icon('float', ic_float, [(210, 50, 44), (240, 236, 226), (40, 40, 46), (80, 140, 200)])
icon('rod', ic_rod, [(150, 100, 50), (120, 120, 130), (200, 150, 90)])
icon('reel', ic_reel, [(170, 170, 180), (90, 90, 100), (60, 60, 70), (230, 230, 240)])
icon('line', ic_line, [(220, 230, 250), (160, 180, 220)])
icon('bait', ic_bait, [(220, 120, 130), (200, 100, 110), (250, 170, 170)])
icon('lock', ic_lock, [(180, 180, 190), (200, 160, 60), (120, 90, 30), (240, 210, 110)])
icon('star', ic_star, [(255, 230, 90), (220, 140, 40), (255, 250, 200)])
icon('dock', ic_dock, [(170, 120, 70), (90, 60, 30), (100, 70, 40)])
icon('fish', ic_fish, [(120, 170, 220), (50, 80, 120), (90, 140, 200), (20, 20, 30)])
icon('check', ic_check, [(120, 230, 120), (60, 160, 60)])
icon('book', ic_book, [(150, 70, 60), (80, 30, 30), (240, 220, 170)])
icon('arrow', ic_arrow, [(255, 240, 200), (200, 180, 140)])

# ---- the lake map: 128x96 top view at (128, 128) in slot 1 (painted, then quantised)
MW, MH = 128, 96
MAPX0, MAPZ0, MSCALE = -64.0, 48.0, 1.0      # world x = MAPX0 + px * MSCALE; z = MAPZ0 - py
S = 4
mim = Image.new('RGB', (MW * S, MH * S), (226, 210, 166))
md = ImageDraw.Draw(mim)
mp = np.zeros((MH * S, MW * S, 3), np.float32)
ys_, xs_ = np.mgrid[0:MH * S, 0:MW * S]
wx = MAPX0 + (xs_ + 0.5) / S * MSCALE
wz = MAPZ0 - (ys_ + 0.5) / S * MSCALE
ra = np.arctan2(wx, wz)
rr = np.hypot(wx, wz)
Rv = np.vectorize(shore_r)(ra)
d_ = rr - Rv
paper = np.array([226, 210, 166], np.float32)
land = np.array([150, 176, 104], np.float32)
forest = np.array([86, 128, 80], np.float32)
waterc = np.array([110, 170, 200], np.float32)
deep = np.array([70, 130, 176], np.float32)
img = np.zeros_like(mp)
t = np.clip(-d_ / 10, 0, 1)[..., None]
img[:] = waterc * (1 - t) + deep * t
lm = (d_ > 0)[..., None]
img = np.where(lm, land, img)
fm = ((d_ > 11) & (d_ < 30))[..., None]
img = np.where(fm, forest, img)
pm = ((d_ > 30) | (np.abs(wx) > 62) | (np.abs(wz - (MAPZ0 - MH / 2)) > 46))[..., None]
img = np.where(pm, paper, img)
mim = Image.fromarray(np.clip(img, 0, 255).astype(np.uint8))
md = ImageDraw.Draw(mim)
# shoreline ink
for a_i in range(720):
    a = a_i / 720 * 2 * math.pi
    r = shore_r(a)
    x, _, z = apos(a, r)
    px, py = (x - MAPX0) * S, (MAPZ0 - z) * S
    md.ellipse((px - 2, py - 2, px + 2, py + 2), fill=(60, 90, 110))


def mpt(p):
    return ((p[0] - MAPX0) * S, (MAPZ0 - p[2]) * S)


for h in HOUSES:
    px, py = mpt(h['pos'])
    md.rectangle((px - 5, py - 4, px + 5, py + 4), fill=(200, 90, 70), outline=(90, 40, 30), width=2)
for k in range(60):
    a = rng.uniform(-math.pi, math.pi)
    if in_village(a):
        continue
    p = apos(a, shore_r(a) + rng.uniform(13, 22))
    px, py = mpt(p)
    md.ellipse((px - 7, py - 7, px + 7, py + 7), fill=(60, 100, 64), outline=(40, 70, 44), width=2)
for p in REED_SPOTS:
    px, py = mpt(p)
    md.line([(px - 3, py + 3), (px, py - 5), (px + 3, py + 3)], fill=(110, 140, 70), width=2)
for p in LILY_SPOTS:
    px, py = mpt(p)
    md.ellipse((px - 3, py - 3, px + 3, py + 3), fill=(80, 150, 80))
for dk in DOCK_LIST:
    f = dk['faces']
    pass
# docks drawn as brown strokes from base to stand
for dk in DOCK_LIST:
    a = mpt(dk['base'])
    b = mpt(dk['stand'])
    md.line([a, b], fill=(120, 80, 40), width=8)
# stream lines
for a0, L in ((A_BRIDGE, 30), (A_RIVER, 26)):
    R = shore_r(a0)
    pts = [mpt(apos(a0 + 0.02 * math.sin(k * 0.7), R + k)) for k in range(0, L)]
    md.line(pts, fill=(110, 170, 200), width=10)
mim = mim.filter(ImageFilter.SMOOTH)
sm = mim.resize((MW, MH), Image.LANCZOS)
q = sm.quantize(colors=15, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
qi = np.asarray(q, np.uint8) + 1
qp = q.getpalette()[:45]
MAP_PAL = stat_pal([tuple(qp[i * 3:i * 3 + 3]) for i in range(15)])
A1.put(128, 128, qi)
MAP_UV = (128, 128, MW, MH)
DOCK_MAP = [((dk['stand'][0] - MAPX0), (MAPZ0 - dk['stand'][2])) for dk in DOCK_LIST]
VILLAGE_MAP = ((HOUSES[3]['pos'][0] - MAPX0), (MAPZ0 - HOUSES[3]['pos'][2]))

# ---- pattern-guide art in slot 1: a ring (64x64 at 0, 192) and a soft dot (16x16 at 64, 192)
img = np.zeros((64, 64), np.uint8)
for y in range(64):
    for x in range(64):
        r = math.hypot(x - 31.5, y - 31.5)
        v = math.exp(-((r - 27) / 2.0) ** 2)
        if r < 27:
            v = max(v, 0.18)
        if v > 0.05:
            img[y, x] = max(1, min(15, int(round(v * 15))))
A1.put(0, 192, img)
img = np.zeros((16, 16), np.uint8)
for y in range(16):
    for x in range(16):
        r = math.hypot(x - 7.5, y - 7.5) / 7.5
        if r < 1:
            img[y, x] = max(1, int(round((1 - r * r) * 15)))
A1.put(64, 192, img)
UI_GREY = stat_pal([(v, v, v) for v in np.linspace(17, 255, 15)])
# a panel corner texture is not needed: panels are flat semi-transparent quads

# ----------------------------------------------------------------------------- fonts & logo (slot 2)
FONT_SMALL = '/System/Library/Fonts/Supplemental/Arial Rounded Bold.ttf'
FONT_BIG = '/System/Library/Fonts/Supplemental/Georgia Bold Italic.ttf'
HIRA_ROUND = '/System/Library/Fonts/ヒラギノ丸ゴ ProN W4.ttc'
SHADOW = (16, 14, 36)
FONT_PAL = stat_pal([SHADOW] + [tuple(int(SHADOW[k] + (255 - SHADOW[k]) * (i / 13.0) ** 0.85) for k in range(3))
                                for i in range(14)])


class Shelf:
    def __init__(self, atlas, x0, y0, x1, y1):
        self.a, self.x0, self.y0, self.x1, self.y1 = atlas, x0, y0, x1, y1
        self.x, self.y, self.rowh = x0, y0, 0

    def put(self, img):
        h, w = img.shape
        if self.x + w > self.x1:
            self.x = self.x0
            self.y += self.rowh + 1
            self.rowh = 0
        assert self.y + h <= self.y1, 'atlas full'
        self.a.put(self.x, self.y, img)
        u, v = self.x, self.y
        self.x += w + 1
        self.rowh = max(self.rowh, h)
        return u, v


def render_font(shelf, path, size, track=0, firm=True):
    font = ImageFont.truetype(path, size)
    big = ImageFont.truetype(path, size * 4)
    asc, desc = font.getmetrics()
    H = asc + desc + 2
    metrics = []
    for code in range(32, 127):
        ch = chr(code)
        adv = font.getlength(ch)
        cw = int(math.ceil(adv)) + 4
        S = 4
        img = Image.new('L', (cw * S, H * S), 0)
        d = ImageDraw.Draw(img)
        d.text((1 * S, 0), ch, font=big, fill=255)
        a = np.asarray(img.resize((cw, H), Image.BOX), np.float32) / 255.0
        if firm:
            a = np.clip((a - 0.1) / 0.75, 0, 1)
        sh = np.zeros_like(a)
        sh[1:, 1:] = a[:-1, :-1]
        idx = np.zeros(a.shape, np.uint8)
        vis = (a > 0.18) | (sh > 0.4)
        lvl = np.clip(np.round(a * 13), 0, 13).astype(np.uint8) + 2
        idx[vis] = np.where(a[vis] > 0.18, lvl[vis], 1)
        cols = np.where(idx.any(axis=0))[0]
        if len(cols) == 0:
            metrics.append((0, 0, 0, int(round(adv)) + track))
            continue
        w = int(cols.max()) + 1
        idx = idx[:, :w]
        u, v = shelf.put(idx)
        metrics.append((u, v, w, int(round(adv)) + track))
    return metrics, H


shelf = Shelf(A2, 0, 0, 255, 183)
FS_METRICS, FS_H = render_font(shelf, FONT_SMALL, 10, track=0)
shelf.x = 0; shelf.y += shelf.rowh + 2; shelf.rowh = 0
FB_METRICS, FB_H = render_font(shelf, FONT_BIG, 15, track=0)
print('fonts: small h=%d big h=%d, atlas used to row %d' % (FS_H, FB_H, shelf.y + shelf.rowh))

# logo: "Lantern Lake" + a little Japanese subtitle, 4-bit, up to 256 x 72 at (0, 180)
LW, LH = 256, 72
S = 4
lim = Image.new('RGBA', (LW * S, LH * S), (0, 0, 0, 0))
font = ImageFont.truetype(FONT_BIG, 36 * S)
txt = 'Lantern Lake'
bb = font.getbbox(txt)
tw = bb[2] - bb[0]
ox = (LW * S - tw) // 2 - bb[0]
oy = 2 * S - bb[1]
mask = Image.new('L', lim.size, 0)
ImageDraw.Draw(mask).text((ox, oy), txt, font=font, fill=255)
outline = mask.filter(ImageFilter.MaxFilter(int(2 * S) * 2 + 1))
glow = mask.filter(ImageFilter.MaxFilter(int(3 * S) * 2 + 1)).filter(ImageFilter.GaussianBlur(3 * S))
grad = np.zeros((LH * S, LW * S, 3), np.float32)
gy = np.linspace(0, 1, LH * S)[:, None]
top_c = np.array([255, 250, 214], np.float32)
mid_c = np.array([255, 206, 110], np.float32)
bot_c = np.array([236, 120, 64], np.float32)
yrel = np.clip((np.arange(LH * S) - oy - bb[1]) / (bb[3] - bb[1]), 0, 1)[:, None, None]
grad = np.where(yrel < 0.5, top_c + (mid_c - top_c) * (yrel / 0.5), mid_c + (bot_c - mid_c) * ((yrel - 0.5) / 0.5))
grad = np.broadcast_to(grad, (LH * S, LW * S, 3))
m = np.asarray(mask, np.float32)[..., None] / 255
o = np.asarray(outline, np.float32)[..., None] / 255
gl = np.asarray(glow, np.float32)[..., None] / 255
col = np.zeros((LH * S, LW * S, 3), np.float32)
alpha = np.zeros((LH * S, LW * S, 1), np.float32)
outc = np.array([70, 30, 50], np.float32)
col = outc * o + grad * m * 1.0
col = np.where(m > 0.5, grad, np.where(o > 0.5, outc, col))
alpha = np.maximum(o, m)
# subtitle
jf = ImageFont.truetype(HIRA_ROUND, 13 * S)
sub_ = 'ランタン湖  ·  a lakeside fishing tale'
jm = Image.new('L', lim.size, 0)
jb = jf.getbbox(sub_)
ImageDraw.Draw(jm).text(((LW * S - (jb[2] - jb[0])) // 2 - jb[0], 52 * S), sub_, font=jf, fill=255)
jo = jm.filter(ImageFilter.MaxFilter(int(1.2 * S) * 2 + 1))
jmn = np.asarray(jm, np.float32)[..., None] / 255
jon = np.asarray(jo, np.float32)[..., None] / 255
col = np.where(jmn > 0.5, np.array([236, 230, 255], np.float32), np.where(jon > 0.5, outc, col))
alpha = np.maximum(alpha, jon)
rgba = np.concatenate([col, alpha * 255], axis=2).astype(np.uint8)
lsmall = Image.fromarray(rgba, 'RGBA').resize((LW, LH), Image.LANCZOS)
la = np.asarray(lsmall, np.float32)
op = la[..., 3] > 110
pix = la[..., :3][op].astype(np.uint8)
pimg = Image.fromarray(pix.reshape(1, -1, 3), 'RGB')
q = pimg.quantize(colors=15, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
lidx = np.zeros((LH, LW), np.uint8)
lidx[op] = np.asarray(q, np.uint8).reshape(-1) + 1
qp = q.getpalette()[:45]
LOGO_PAL = stat_pal([tuple(qp[i * 3:i * 3 + 3]) for i in range(15)])
A2.put(0, 184, lidx)
LOGO_UV = (0, 184, LW, LH)

# ----------------------------------------------------------------------------- write textures, palettes

write('tex0.bin', A0.pack())
write('tex1.bin', A1.pack())
write('tex2.bin', A2.pack())
write('tex3.bin', A3.pack())
# the memory card save icon: a paper lantern bobbing over the water, 3 frames
from mei_icon import make_meta
frames = []
for k in range(3):
    S = 8
    im = Image.new('RGBA', (16 * S, 16 * S), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    oy = [0, -1, 0][k] * S
    d.rectangle((0, 12 * S, 16 * S, 16 * S), fill=(40, 70, 120, 255))
    for x in range(0, 16, 4):
        d.line([((x + k) * S, 13.5 * S), ((x + k + 2) * S, 13.5 * S)], fill=(110, 160, 210, 255), width=S)
    d.ellipse((5 * S, 13 * S, 11 * S, 15.5 * S), fill=(200, 140, 70, 255))
    d.rectangle((6.5 * S, 0.5 * S + oy, 9.5 * S, 2 * S + oy), fill=(60, 40, 40, 255))
    d.ellipse((3 * S, 2 * S + oy, 13 * S, 11 * S + oy), fill=(236, 110, 60, 255), outline=(140, 50, 40, 255), width=S)
    d.ellipse((5.5 * S, 3.5 * S + oy, 10.5 * S, 9.5 * S + oy), fill=(255, 220, 140, 255))
    d.rectangle((6.5 * S, 11 * S + oy, 9.5 * S, 12 * S + oy), fill=(60, 40, 40, 255))
    frames.append(im.resize((16, 16), Image.LANCZOS))
write('save_icon.bin', make_meta(frames, title='Lantern Lake', quantize=True))

SRC_ORDER = MAT_ORDER
keypal = bytearray()
for k in range(4):
    for name in SRC_ORDER:
        for c in MATS[name]['keys'][k]:
            keypal += struct.pack('<H', c15(c))
# reflection keys: same order, darker and bluer
for k in range(4):
    for name in SRC_ORDER:
        for c in MATS[name]['keys'][k]:
            keypal += struct.pack('<H', c15(tuple(c[j] * REFL[j] for j in range(3))))
write('keypal.bin', bytes(keypal))
statpal = bytearray()
for p in STAT:
    for c in p:
        statpal += struct.pack('<H', c15(c))
write('statpal.bin', bytes(statpal))
assert STAT_BASE + len(STAT) <= 255
if DEBUG_PNG:
    os.makedirs(DEBUG_PNG, exist_ok=True)

    def colorize(idx, pal):
        pa = np.array([(0, 0, 0)] + [tuple(int(v) for v in c) for c in pal[1:16]], np.uint8)
        return pa[idx]
    # fish: day row, night row, silhouette row
    rows = []
    for which in (0, 1, 2):
        row = []
        for s_ in range(NSPEC):
            u, v = FISH_UV[s_]
            pn = FISH_PAL[s_][min(which, 1)] if which < 2 else SIL_PAL
            row.append(colorize(A1.idx[v:v + 32, u:u + 64], STAT[pn - STAT_BASE]))
        rows.append(np.concatenate(row, axis=1))
    Image.fromarray(np.concatenate(rows, axis=0)).resize((64 * NSPEC * 3, 96 * 3), Image.NEAREST).save(
        os.path.join(DEBUG_PNG, 'fish.png'))
    Image.fromarray(colorize(A1.idx[128:224, 128:256], STAT[MAP_PAL - STAT_BASE])).resize((512, 384), Image.NEAREST).save(
        os.path.join(DEBUG_PNG, 'map.png'))
    Image.fromarray(colorize(A2.idx[184:256, 0:256], STAT[LOGO_PAL - STAT_BASE])).resize((768, 216), Image.NEAREST).save(
        os.path.join(DEBUG_PNG, 'logo.png'))
    Image.fromarray(colorize(A2.idx[0:184, 0:256], STAT[FONT_PAL - STAT_BASE])).resize((768, 552), Image.NEAREST).save(
        os.path.join(DEBUG_PNG, 'fonts.png'))
    for k in range(4):
        img = np.zeros((256, 256, 3), np.uint8)
        for nm in MAT_ORDER:
            if nm == 'water':
                continue
            M = MATS[nm]
            img[M['v']:M['v'] + M['h'], M['u']:M['u'] + M['w']] = colorize(A0.idx[M['v']:M['v'] + M['h'], M['u']:M['u'] + M['w']], M['keys'][k])
        Image.fromarray(img).resize((512, 512), Image.NEAREST).save(os.path.join(DEBUG_PNG, 'world%d.png' % k))
    icons = []
    for nm in icon_list:
        u, v, p = ICONS[nm]
        icons.append(colorize(A1.idx[v:v + 16, u:u + 16], STAT[p - STAT_BASE]))
    Image.fromarray(np.concatenate(icons, axis=1)).resize((16 * len(icons) * 4, 64), Image.NEAREST).save(
        os.path.join(DEBUG_PNG, 'icons.png'))
    for nm, at, pals in (('tex0', A0, None), ('tex1', A1, None), ('tex2', A2, None)):
        Image.fromarray((at.idx * 17).astype(np.uint8)).resize((512, 512), Image.NEAREST).save(
            os.path.join(DEBUG_PNG, nm + '.png'))

# ----------------------------------------------------------------------------- assets.akr


def fx(v):
    s = '%.4f' % v
    return s


L = ['// Generated by tools/gen_lantern_assets.py - do not edit.', '']
L.append('embed TEX0: u8 = "tex0.bin"')
L.append('embed TEX1: u8 = "tex1.bin"')
L.append('embed TEX2: u8 = "tex2.bin"')
L.append('embed TEX3: u8 = "tex3.bin"')
L.append('embed KEYPAL: u16 = "keypal.bin"      // [2 (normal, reflection)][4 keys][NSRC][16]')
L.append('embed STATPAL: u16 = "statpal.bin"    // static palettes from STAT_BASE')
L.append('embed SAVE_ICON: SaveMeta = "save_icon.bin"')
L.append('const NSRC = %d' % NSRC)
L.append('const NDEST = %d' % len(DEST))
L.append('const REFL_OFF = %d' % REFL_OFF)
L.append('const STAT_BASE = %d' % STAT_BASE)
L.append('const NSTAT = %d' % len(STAT))
L.append('// source material of each live palette (houses switch between dark and lit walls)')
L.append('const DEST_SRC: [%d]u8 = [%s]' % (len(DEST), ', '.join(str(MATS[s]['src']) for s in DEST)))
for nm in ('wall_dark', 'wall_lit', 'timber_dark', 'timber_lit', 'water'):
    L.append('const SRC_%s = %d' % (nm.upper(), MATS[nm]['src']))
for nm, p in PALNUM.items():
    L.append('const PAL_%s = %d' % (nm.upper(), p))
L.append('const PAL_GREY = %d' % GREY)
L.append('const PAL_MOON = %d' % MOON_PAL)
L.append('const PAL_SIL = %d' % SIL_PAL)
L.append('const PAL_SIL2 = %d' % SIL_PAL2)
L.append('const PAL_MAP = %d' % MAP_PAL)
L.append('const PAL_UI = %d' % UI_GREY)
L.append('const PAL_FONT = %d' % FONT_PAL)
L.append('const PAL_LOGO = %d' % LOGO_PAL)
for k, v in UV.items():
    L.append('const UV_%s_U = %d' % (k.upper(), v[0]))
    L.append('const UV_%s_V = %d' % (k.upper(), v[1]))
L.append('const LOGO_U = %d' % LOGO_UV[0])
L.append('const LOGO_V = %d' % LOGO_UV[1])
L.append('const LOGO_W = %d' % LOGO_UV[2])
L.append('const LOGO_H = %d' % LOGO_UV[3])
L.append('const MAP_U = %d' % MAP_UV[0])
L.append('const MAP_V = %d' % MAP_UV[1])
L.append('const MAP_W = %d' % MAP_UV[2])
L.append('const MAP_H = %d' % MAP_UV[3])
L.append('const SW_U: [16]u8 = [%s]' % ', '.join(str(SW_UV.get(i, (0, 0))[0]) for i in range(16)))
L.append('const SW_V: [16]u8 = [%s]' % ', '.join(str(SW_UV.get(i, (0, 0))[1]) for i in range(16)))
L.append('')
L.append('// icons (slot 1): u, v, palette')
for nm in icon_list:
    u, v, p = ICONS[nm]
    L.append('const IC_%s: Icon = Icon { u: %d, v: %d, pal: %d }' % (nm.upper(), u, v, p))
L.append('')
L.append('// fish textures (slot 1): 64x32 each; palettes: day, night')
L.append('const NSPEC = %d' % NSPEC)
L.append('const FISH_U: [%d]u8 = [%s]' % (NSPEC, ', '.join(str(u) for u, v in FISH_UV)))
L.append('const FISH_V: [%d]u8 = [%s]' % (NSPEC, ', '.join(str(v) for u, v in FISH_UV)))
L.append('const FISH_PDAY: [%d]u8 = [%s]' % (NSPEC, ', '.join(str(a) for a, b in FISH_PAL)))
L.append('const FISH_PNIGHT: [%d]u8 = [%s]' % (NSPEC, ', '.join(str(b) for a, b in FISH_PAL)))
L.append('')
L.append('// meshes')
for ch in range(NCHUNK):
    L.append('embed TERR%d: Mesh = "terr%d.bin"' % (ch, ch))
    L.append('embed TERR%d_R: Mesh = "terr%d_r.bin"' % (ch, ch))
    L.append('embed TERR%d_LO: Mesh = "terr%d_lo.bin"' % (ch, ch))
L.append('const NCHUNK = %d' % NCHUNK)
L.append('const CHUNK_C: [%d]vec3 = [%s]' % (NCHUNK, ', '.join('vec3(%s, %s, %s)' % (fx(c[0]), fx(c[1]), fx(c[2])) for c, r, *n in CHUNKS)))
L.append('const CHUNK_R: [%d]fixed = [%s]' % (NCHUNK, ', '.join(fx(r) for c, r, *n in CHUNKS)))
L.append('embed HILLS: Mesh = "hills.bin"')
L.append('embed HILLS_R: Mesh = "hills_r.bin"')
for k in range(len(DOCK_LIST)):
    L.append('embed DOCK%d: Mesh = "dock%d.bin"' % (k, k))
    L.append('embed DOCK%d_R: Mesh = "dock%d_r.bin"' % (k, k))
    L.append('embed DOCK%d_LO: Mesh = "dock%d_lo.bin"' % (k, k))
for g in range(4):
    L.append('embed REEDS%d: Mesh = "reeds%d.bin"' % (g, g))
    L.append('embed REEDS%d_R: Mesh = "reeds%d_r.bin"' % (g, g))
for i in range(NHOUSE):
    L.append('embed HOUSE%d: Mesh = "house%d.bin"' % (i, i))
    L.append('embed HOUSE%d_R: Mesh = "house%d_r.bin"' % (i, i))
    L.append('embed HOUSE%d_LO: Mesh = "house%d_lo.bin"' % (i, i))
L.append('const REED_C: [4]vec3 = [%s]' % ', '.join('vec3(%s, 1.0, %s)' % (fx(c[0]), fx(c[2])) for c, r in REED_C))
L.append('const REED_R: [4]fixed = [%s]' % ', '.join(fx(r) for c, r in REED_C))
L.append('embed LILIES: Mesh = "lilies.bin"')
L.append('embed BOBBER: Mesh = "bobber.bin"')
L.append('embed HAND: Mesh = "hand.bin"')
for si in range(len(SPECIES)):
    L.append('embed FISH%d: Mesh = "fish%d.bin"' % (si, si))
    L.append('embed FISHSH%d: Mesh = "fishsh%d.bin"' % (si, si))
L.append('fn fish_mesh(sp: s32) -> *Mesh {')
L.append('    match sp {')
for si in range(len(SPECIES)):
    L.append('        %d => return FISH%d' % (si, si))
L.append('        else => return FISH0')
L.append('    }')
L.append('}')
L.append('fn fish_shadow_mesh(sp: s32) -> *Mesh {')
L.append('    match sp {')
for si in range(len(SPECIES)):
    L.append('        %d => return FISHSH%d' % (si, si))
L.append('        else => return FISHSH0')
L.append('    }')
L.append('}')
L.append('')
L.append('fn terr_mesh(i: s32, refl: bool, far: bool) -> *Mesh {')
L.append('    match i {')
for ch in range(NCHUNK):
    L.append('        %d => { if refl { return TERR%d_R } if far { return TERR%d_LO } return TERR%d }' % (ch, ch, ch, ch))
L.append('        else => { if refl { return TERR0_R } return TERR0 }')
L.append('    }')
L.append('}')
L.append('fn dock_mesh(i: s32, refl: bool, far: bool) -> *Mesh {')
L.append('    match i {')
for k in range(len(DOCK_LIST)):
    L.append('        %d => { if refl { return DOCK%d_R } if far { return DOCK%d_LO } return DOCK%d }' % (k, k, k, k))
L.append('        else => { if refl { return DOCK0_R } return DOCK0 }')
L.append('    }')
L.append('}')
L.append('fn reed_mesh(i: s32, refl: bool) -> *Mesh {')
L.append('    match i {')
for g in range(4):
    L.append('        %d => { if refl { return REEDS%d_R } return REEDS%d }' % (g, g, g))
L.append('        else => { if refl { return REEDS0_R } return REEDS0 }')
L.append('    }')
L.append('}')
L.append('fn house_mesh(i: s32, refl: bool, far: bool) -> *Mesh {')
L.append('    match i {')
for i in range(NHOUSE):
    L.append('        %d => { if refl { return HOUSE%d_R } if far { return HOUSE%d_LO } return HOUSE%d }' % (i, i, i, i))
L.append('        else => { if refl { return HOUSE0_R } return HOUSE0 }')
L.append('    }')
L.append('}')
L.append('const NHOUSE = %d' % NHOUSE)
L.append('const HOUSE_POS: [%d]vec3 = [%s]' % (NHOUSE, ', '.join('vec3(%s, 0.0, %s)' % (fx(h['pos'][0]), fx(h['pos'][2])) for h in HOUSES)))
L.append('const HOUSE_TIMBER: [%d]u8 = [%s]' % (NHOUSE, ', '.join('1' if s[5] else '0' for s in VILLAGE_SPEC)))
L.append('')
L.append('// docks: where the angler stands, the yaw facing the lake, lantern positions')
L.append('const NDOCK = %d' % len(DOCK_LIST))
L.append('const DOCK_STAND: [%d]vec3 = [%s]' % (len(DOCK_LIST), ', '.join('vec3(%s, %s, %s)' % tuple(fx(c) for c in dk['stand']) for dk in DOCK_LIST)))
L.append('const DOCK_YAW: [%d]fixed = [%s]' % (len(DOCK_LIST), ', '.join(fx(dk['yaw']) for dk in DOCK_LIST)))
L.append('const DOCK_MAPX: [%d]s32 = [%s]' % (len(DOCK_LIST), ', '.join(str(int(round(x))) for x, y in DOCK_MAP)))
L.append('const DOCK_MAPY: [%d]s32 = [%s]' % (len(DOCK_LIST), ', '.join(str(int(round(y))) for x, y in DOCK_MAP)))
L.append('const VILLAGE_MAPX = %d' % int(round(VILLAGE_MAP[0])))
L.append('const VILLAGE_MAPY = %d' % int(round(VILLAGE_MAP[1])))
lan = []
lan_dock = []
for k, dk in enumerate(DOCK_LIST):
    for p in dk['lanterns']:
        lan.append(p)
        lan_dock.append(k)
for p in VILLAGE_LANTERNS:
    lan.append(p)
    lan_dock.append(9)
L.append('const NLANTERN = %d' % len(lan))
L.append('const LANTERN_POS: [%d]vec3 = [%s]' % (len(lan), ', '.join('vec3(%s, %s, %s)' % tuple(fx(c) for c in p) for p in lan)))
L.append('const LANTERN_DOCK: [%d]u8 = [%s]' % (len(lan), ', '.join(str(d) for d in lan_dock)))
L.append('const NGARLAND = %d' % len(GARLANDS))
L.append('const GARLAND_POS: [%d]vec3 = [%s]' % (len(GARLANDS), ', '.join('vec3(%s, %s, %s)' % (fx(g[0]), fx(g[1]), fx(g[2])) for g in GARLANDS)))
L.append('const GARLAND_LVL: [%d]u8 = [%s]' % (len(GARLANDS), ', '.join(str(g[3]) for g in GARLANDS)))
L.append('const NLILY = %d' % len(LILY_SPOTS))
L.append('const LILY_POS: [%d]vec3 = [%s]' % (len(LILY_SPOTS), ', '.join('vec3(%s, 0.0, %s)' % (fx(p[0]), fx(p[2])) for p in LILY_SPOTS)))
L.append('const NREEDSPOT = %d' % len(REED_SPOTS))
L.append('const REED_POS: [%d]vec3 = [%s]' % (len(REED_SPOTS), ', '.join('vec3(%s, 0.0, %s)' % (fx(p[0]), fx(p[2])) for p in REED_SPOTS)))
L.append('')
# shore radius table for gameplay (is a point on water? casting limits): 64 samples
L.append('// lake shore radius by azimuth (64 steps from -PI)')
L.append('const SHORE_R: [65]fixed = [%s]' % ', '.join(fx(shore_r(-math.pi + 2 * math.pi * i / 64)) for i in range(65)))
L.append('')
L.append('// fonts (slot 2): u, v, width, advance per character 32..126')
for nm, met, h in (('FS', FS_METRICS, FS_H), ('FB', FB_METRICS, FB_H)):
    L.append('const %s_H = %d' % (nm, h))
    L.append('const %s_U: [95]u8 = [%s]' % (nm, ', '.join(str(m[0]) for m in met)))
    L.append('const %s_V: [95]u8 = [%s]' % (nm, ', '.join(str(m[1]) for m in met)))
    L.append('const %s_W: [95]u8 = [%s]' % (nm, ', '.join(str(m[2]) for m in met)))
    L.append('const %s_A: [95]u8 = [%s]' % (nm, ', '.join(str(m[3]) for m in met)))
with open(os.path.join(OUT, 'assets.akr'), 'w') as f:
    f.write('\n'.join(L) + '\n')

print('materials', NSRC, 'dest palettes', len(DEST), 'static palettes', len(STAT))
print('chunks faces (near, far, refl)', [c[2:] for c in CHUNKS])
print('docks faces', [(len(d['faces']), sum(1 for f in d['faces'] if f.lo)) for d in DOCK_LIST], 'reeds', [len(g) for g in reed_groups],
      'houses', [len(village_faces[i]) for i in range(NHOUSE)], 'lilies', len(lily_faces))
print('docks stand/yaw', [(tuple(round(c, 2) for c in d['stand']), round(d['yaw'], 3)) for d in DOCK_LIST])

# audio
aud = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'gen_lantern_audio.py')
if os.path.exists(aud) and '--no-audio' not in sys.argv:
    subprocess.check_call([sys.executable, aud] + (['--review', DEBUG_PNG] if DEBUG_PNG else []))
